// <auto-generated/>
#if NET8_0_OR_GREATER
using System.Runtime.CompilerServices;

namespace Qyl.OpenTelemetry.AutoInstrumentation.Hosting;

internal static class QylAutoInstrumentationConsumerBootstrap
{
    [ModuleInitializer]
    internal static void Initialize()
        => QylAutoInstrumentationBootstrap.Boot();
}
#endif
