using System.Collections.Immutable;

namespace Qyl.OpenTelemetry.AutoInstrumentation.SourceGenerators;

public sealed partial class QylAutoInstrumentationGenerator
{
    private static ImmutableArray<InterceptorMatcherDescriptor> CreateGeneratedMatcherDescriptors()
        => ImmutableArray.Create(
            new InterceptorMatcherDescriptor("HttpClient", "global::System.Net.Http.HttpClient", InterceptorKind.HttpClient, ContractKeys("signals.traces.HTTPCLIENT", "signals.metrics.HTTPCLIENT"), InterceptorEmitterFamily.HttpClient, InterceptorMethodShape.AsyncValue, TryGetHttpClientInvocation),
            new InterceptorMatcherDescriptor("HttpWebRequest", "global::System.Net.HttpWebRequest", InterceptorKind.HttpWebRequest, ContractKeys("signals.traces.HTTPCLIENT", "signals.metrics.HTTPCLIENT"), InterceptorEmitterFamily.HttpClient, InterceptorMethodShape.AsyncOrSyncValue, TryGetHttpWebRequestInvocation),
            new InterceptorMatcherDescriptor("AspNetCoreWebApplicationBuilderBuild", "global::Microsoft.AspNetCore.Builder.WebApplicationBuilder", InterceptorKind.AspNetCoreWebApplicationBuilderBuild, "signals.traces.ASPNETCORE", InterceptorEmitterFamily.AspNetCore, InterceptorMethodShape.BuilderInitialization, TryGetAspNetCoreWebApplicationBuilderBuildInvocation),
            new InterceptorMatcherDescriptor("AspNetCoreRequestDelegate", "global::Microsoft.AspNetCore.Http.RequestDelegate", InterceptorKind.AspNetCoreRequestDelegate, "signals.traces.ASPNETCORE", InterceptorEmitterFamily.AspNetCore, InterceptorMethodShape.AsyncTask, TryGetAspNetCoreRequestDelegateInvocation),
            new InterceptorMatcherDescriptor("AspNetCoreEndpointMap", "global::Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions", InterceptorKind.AspNetCoreEndpointMap, "signals.traces.ASPNETCORE", InterceptorEmitterFamily.AspNetCore, InterceptorMethodShape.EndpointRegistration, TryGetAspNetCoreEndpointMapInvocation),
            new InterceptorMatcherDescriptor("MeterProviderBuilderAddMeter", "global::OpenTelemetry.Metrics.MeterProviderBuilder", InterceptorKind.MeterProviderBuilderAddMeter, ContractKeys("signals.metrics.ASPNETCORE", "signals.metrics.HTTPCLIENT", "signals.metrics.NETRUNTIME", "signals.metrics.NPGSQL", "signals.metrics.NSERVICEBUS", "signals.metrics.PROCESS", "signals.metrics.SQLCLIENT"), InterceptorEmitterFamily.Meter, InterceptorMethodShape.BuilderRegistration, TryGetMeterProviderBuilderAddMeterInvocation),
            new InterceptorMatcherDescriptor("AzureClient", "Azure.*Client", InterceptorKind.AzureClient, "signals.traces.AZURE", InterceptorEmitterFamily.Azure, InterceptorMethodShape.AsyncOrSyncValue, TryGetAzureClientInvocation),
            new InterceptorMatcherDescriptor("Elastic", "Elastic.Clients.Elasticsearch.*Client|Elastic.Transport.ITransport", InterceptorKinds(InterceptorKind.ElasticsearchClient, InterceptorKind.ElasticTransport), ContractKeys("signals.traces.ELASTICSEARCH", "signals.traces.ELASTICTRANSPORT"), InterceptorEmitterFamily.Search, InterceptorMethodShape.AsyncOrSyncValue, TryGetElasticInvocation),
            new InterceptorMatcherDescriptor("WcfClient", "global::System.ServiceModel.ClientBase<TChannel>", InterceptorKind.WcfClient, "signals.traces.WCFCLIENT", InterceptorEmitterFamily.Wcf, InterceptorMethodShape.AsyncOrSyncValue, TryGetWcfClientInvocation),
            new InterceptorMatcherDescriptor("GrpcNetClientUnary", "global::Grpc.Core.ClientBase<T>", InterceptorKind.GrpcNetClientAsyncUnaryCall, "signals.traces.GRPCNETCLIENT", InterceptorEmitterFamily.Grpc, InterceptorMethodShape.GrpcUnary, TryGetGrpcNetClientAsyncUnaryInvocation),
            new InterceptorMatcherDescriptor("GrpcNetClientStreaming", "global::Grpc.Core.ClientBase<T>", InterceptorKinds(InterceptorKind.GrpcNetClientAsyncServerStreamingCall, InterceptorKind.GrpcNetClientAsyncClientStreamingCall, InterceptorKind.GrpcNetClientAsyncDuplexStreamingCall), "signals.traces.GRPCNETCLIENT", InterceptorEmitterFamily.Grpc, InterceptorMethodShape.GrpcStreaming, TryGetGrpcNetClientStreamingInvocation),
            new InterceptorMatcherDescriptor("Kafka", "Confluent.Kafka.IProducer<TKey,TValue>|Confluent.Kafka.IConsumer<TKey,TValue>", InterceptorKinds(InterceptorKind.KafkaProducer, InterceptorKind.KafkaConsumer), "signals.traces.KAFKA", InterceptorEmitterFamily.Messaging, InterceptorMethodShape.AsyncOrSyncValue, TryGetKafkaInvocation),
            new InterceptorMatcherDescriptor("MassTransit", "MassTransit.IPublishEndpoint|MassTransit.ISendEndpoint|MassTransit.ISendEndpointProvider", InterceptorKind.MassTransitMessageOperation, "signals.traces.MASSTRANSIT", InterceptorEmitterFamily.Messaging, InterceptorMethodShape.AsyncTask, TryGetMassTransitInvocation),
            new InterceptorMatcherDescriptor("NServiceBus", "NServiceBus.IMessageSession|NServiceBus.IEndpointInstance|NServiceBus.IPipelineContext", InterceptorKind.NServiceBusMessageOperation, ContractKeys("signals.traces.NSERVICEBUS", "signals.metrics.NSERVICEBUS"), InterceptorEmitterFamily.Messaging, InterceptorMethodShape.AsyncTask, TryGetNServiceBusInvocation),
            new InterceptorMatcherDescriptor("Quartz", "Quartz.IJob", InterceptorKind.QuartzJobExecute, "signals.traces.QUARTZ", InterceptorEmitterFamily.Scheduler, InterceptorMethodShape.AsyncTask, TryGetQuartzInvocation),
            new InterceptorMatcherDescriptor("StackExchangeRedis", "StackExchange.Redis.IDatabase", InterceptorKind.StackExchangeRedisCommandAsync, "signals.traces.STACKEXCHANGEREDIS", InterceptorEmitterFamily.Cache, InterceptorMethodShape.AsyncValue, TryGetStackExchangeRedisInvocation),
            new InterceptorMatcherDescriptor("GraphQL", "GraphQL.IDocumentExecuter", InterceptorKind.GraphQlDocumentExecuter, "signals.traces.GRAPHQL", InterceptorEmitterFamily.GraphQl, InterceptorMethodShape.AsyncTask, TryGetGraphQlInvocation),
            new InterceptorMatcherDescriptor("EntityFrameworkCoreDbContext", "global::Microsoft.EntityFrameworkCore.DbContext", InterceptorKind.EntityFrameworkCoreDbContext, "signals.traces.ENTITYFRAMEWORKCORE", InterceptorEmitterFamily.Database, InterceptorMethodShape.AsyncOrSyncValue, TryGetEntityFrameworkCoreDbContextInvocation),
            new InterceptorMatcherDescriptor("EntityFrameworkCoreQueryable", "global::Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions", InterceptorKind.EntityFrameworkCoreQueryable, "signals.traces.ENTITYFRAMEWORKCORE", InterceptorEmitterFamily.Database, InterceptorMethodShape.AsyncValue, TryGetEntityFrameworkCoreQueryableInvocation),
            new InterceptorMatcherDescriptor("MongoDb", "MongoDB.Driver.IMongoCollection<TDocument>", InterceptorKind.MongoDbCollection, "signals.traces.MONGODB", InterceptorEmitterFamily.Database, InterceptorMethodShape.AsyncOrSyncValue, TryGetMongoDbInvocation),
            new InterceptorMatcherDescriptor("DbCommand", "global::System.Data.Common.DbCommand", InterceptorKind.DbCommand, ContractKeys("signals.traces.ADONET", "signals.traces.MYSQLCONNECTOR", "signals.traces.MYSQLDATA", "signals.traces.NPGSQL", "signals.traces.ORACLEMDA", "signals.traces.SQLCLIENT", "signals.traces.SQLITE", "signals.metrics.NPGSQL", "signals.metrics.SQLCLIENT"), InterceptorEmitterFamily.Database, InterceptorMethodShape.AsyncOrSyncValue, TryGetDbCommandInvocation),
            new InterceptorMatcherDescriptor("RabbitMq", "RabbitMQ.Client.IModel|RabbitMQ.Client.IChannel", InterceptorKind.RabbitMqBasicPublish, "signals.traces.RABBITMQ", InterceptorEmitterFamily.Messaging, InterceptorMethodShape.AsyncOrSyncVoid, TryGetRabbitMqInvocation),
            new InterceptorMatcherDescriptor("LoggerExtensions", "global::Microsoft.Extensions.Logging.LoggerExtensions", InterceptorKind.ILoggerExtensionLog, "signals.logs.ILOGGER", InterceptorEmitterFamily.Logging, InterceptorMethodShape.Void, TryGetLoggerExtensionInvocation),
            new InterceptorMatcherDescriptor("ILogger", "global::Microsoft.Extensions.Logging.ILogger", InterceptorKind.ILoggerLog, "signals.logs.ILOGGER", InterceptorEmitterFamily.Logging, InterceptorMethodShape.Void, TryGetLoggerInvocation),
            new InterceptorMatcherDescriptor("NLog", "NLog.Logger", InterceptorKind.NLogLogger, "signals.logs.NLOG", InterceptorEmitterFamily.Logging, InterceptorMethodShape.Void, TryGetNLogInvocation),
            new InterceptorMatcherDescriptor("Log4Net", "log4net.ILog|log4net.Core.ILogger", InterceptorKind.Log4NetLogger, "signals.logs.LOG4NET", InterceptorEmitterFamily.Logging, InterceptorMethodShape.Void, TryGetLog4NetInvocation));

    private static ImmutableArray<InterceptorEmissionDescriptor> CreateGeneratedEmissionDescriptors()
        => ImmutableArray.Create(
            new InterceptorEmissionDescriptor(InterceptorKind.HttpClient, InterceptorEmitterFamily.HttpClient, InterceptorMethodShape.AsyncValue, InterceptorSignalOwnership.TraceAndMetric, InterceptorErrorPolicy.HttpStatusAndException, InterceptorDurationPolicy.RuntimeMetric, ForwardingBody: new ForwardingInterceptorBodyDescriptor("HttpClient", "client", "global::Qyl.OpenTelemetry.AutoInstrumentation.QylInterceptedHttpClient", ReceiverTypeOverride: "global::System.Net.Http.HttpClient")),
            new InterceptorEmissionDescriptor(InterceptorKind.HttpWebRequest, InterceptorEmitterFamily.HttpClient, InterceptorMethodShape.AsyncOrSyncValue, InterceptorSignalOwnership.TraceAndMetric, InterceptorErrorPolicy.HttpStatusAndException, InterceptorDurationPolicy.RuntimeMetric, HttpWebRequestBody: new HttpWebRequestBodyDescriptor("HttpWebRequest", "request", "global::System.Net.HttpWebRequest", "global::Qyl.OpenTelemetry.AutoInstrumentation.QylInterceptedHttpWebRequest", "GetStartTimeUtc", "StartActivity", "RecordResult", "RecordException")),
            new InterceptorEmissionDescriptor(InterceptorKind.AspNetCoreWebApplicationBuilderBuild, InterceptorEmitterFamily.AspNetCore, InterceptorMethodShape.BuilderInitialization, InterceptorSignalOwnership.Trace, InterceptorErrorPolicy.RuntimeDelegate, InterceptorDurationPolicy.None, ForwardingBody: new ForwardingInterceptorBodyDescriptor("AspNetCoreWebApplicationBuilder", "builder", "global::Qyl.OpenTelemetry.AutoInstrumentation.QylInterceptedAspNetCore", HelperMethodName: "Build")),
            new InterceptorEmissionDescriptor(InterceptorKind.AspNetCoreRequestDelegate, InterceptorEmitterFamily.AspNetCore, InterceptorMethodShape.AsyncTask, InterceptorSignalOwnership.Trace, InterceptorErrorPolicy.Exception, InterceptorDurationPolicy.None, ForwardingBody: new ForwardingInterceptorBodyDescriptor("AspNetCoreRequestDelegate", "requestDelegate", "global::Qyl.OpenTelemetry.AutoInstrumentation.QylInterceptedAspNetCore", HelperMethodName: "InvokeAsync")),
            new InterceptorEmissionDescriptor(InterceptorKind.AspNetCoreEndpointMap, InterceptorEmitterFamily.AspNetCore, InterceptorMethodShape.EndpointRegistration, InterceptorSignalOwnership.Trace, InterceptorErrorPolicy.RuntimeDelegate, InterceptorDurationPolicy.None, ForwardingBody: new ForwardingInterceptorBodyDescriptor("AspNetCoreEndpointMap", "endpoints", "global::Qyl.OpenTelemetry.AutoInstrumentation.QylInterceptedAspNetCore")),
            new InterceptorEmissionDescriptor(InterceptorKind.MeterProviderBuilderAddMeter, InterceptorEmitterFamily.Meter, InterceptorMethodShape.BuilderRegistration, InterceptorSignalOwnership.Metric, InterceptorErrorPolicy.None, InterceptorDurationPolicy.None, MeterProviderBuilderBody: new MeterProviderBuilderBodyDescriptor("MeterProviderBuilder", "builder", "global::Qyl.OpenTelemetry.AutoInstrumentation.QylMetricMeters.GetEnabledMeterNames()")),
            new InterceptorEmissionDescriptor(InterceptorKind.AzureClient, InterceptorEmitterFamily.Azure, InterceptorMethodShape.AsyncOrSyncValue, InterceptorSignalOwnership.Trace, InterceptorErrorPolicy.Exception, InterceptorDurationPolicy.None, TraceBody: new TraceInterceptorBodyDescriptor("AzureClient", "client", RuntimeHelper: new TraceRuntimeHelperDescriptor("global::Qyl.OpenTelemetry.AutoInstrumentation.QylInterceptedAzure", "StartActivity", "RecordException", TraceStartActivityArgumentKind.TargetMethodName))),
            new InterceptorEmissionDescriptor(InterceptorKind.ElasticsearchClient, InterceptorEmitterFamily.Search, InterceptorMethodShape.AsyncOrSyncValue, InterceptorSignalOwnership.Trace, InterceptorErrorPolicy.Exception, InterceptorDurationPolicy.None, TraceBody: new TraceInterceptorBodyDescriptor("Elastic", "client", MethodPrefixKind: TraceMethodPrefixKind.InstrumentationIdAndTargetMethodName, AsyncObservation: new TraceAsyncObservationDescriptor("global::Qyl.OpenTelemetry.AutoInstrumentation.QylInterceptedElastic.ObserveAsync", TraceAsyncObservationCondition.AsyncWithByRefParameters), RuntimeHelper: new TraceRuntimeHelperDescriptor("global::Qyl.OpenTelemetry.AutoInstrumentation.QylInterceptedElastic", "StartActivity", "RecordException", TraceStartActivityArgumentKind.InstrumentationIdAndTargetMethodName))),
            new InterceptorEmissionDescriptor(InterceptorKind.ElasticTransport, InterceptorEmitterFamily.Search, InterceptorMethodShape.AsyncOrSyncValue, InterceptorSignalOwnership.Trace, InterceptorErrorPolicy.Exception, InterceptorDurationPolicy.None, TraceBody: new TraceInterceptorBodyDescriptor("Elastic", "client", MethodPrefixKind: TraceMethodPrefixKind.InstrumentationIdAndTargetMethodName, AsyncObservation: new TraceAsyncObservationDescriptor("global::Qyl.OpenTelemetry.AutoInstrumentation.QylInterceptedElastic.ObserveAsync", TraceAsyncObservationCondition.AsyncWithByRefParameters), RuntimeHelper: new TraceRuntimeHelperDescriptor("global::Qyl.OpenTelemetry.AutoInstrumentation.QylInterceptedElastic", "StartActivity", "RecordException", TraceStartActivityArgumentKind.InstrumentationIdAndTargetMethodName))),
            new InterceptorEmissionDescriptor(InterceptorKind.WcfClient, InterceptorEmitterFamily.Wcf, InterceptorMethodShape.AsyncOrSyncValue, InterceptorSignalOwnership.Trace, InterceptorErrorPolicy.Exception, InterceptorDurationPolicy.None, TraceBody: new TraceInterceptorBodyDescriptor("WcfClient", "client", RuntimeHelper: new TraceRuntimeHelperDescriptor("global::Qyl.OpenTelemetry.AutoInstrumentation.QylInterceptedWcfClient", "StartActivity", "RecordException", TraceStartActivityArgumentKind.ReceiverTypeAndTargetMethodName))),
            new InterceptorEmissionDescriptor(InterceptorKind.GrpcNetClientAsyncUnaryCall, InterceptorEmitterFamily.Grpc, InterceptorMethodShape.GrpcUnary, InterceptorSignalOwnership.Trace, InterceptorErrorPolicy.GrpcStatusAndException, InterceptorDurationPolicy.None, GrpcClientBody: new GrpcClientBodyDescriptor(GrpcClientCallShape.Unary, "GrpcNetClientAsyncUnary", "client", "global::Qyl.OpenTelemetry.AutoInstrumentation.QylInterceptedGrpcNetClient")),
            new InterceptorEmissionDescriptor(InterceptorKind.GrpcNetClientAsyncServerStreamingCall, InterceptorEmitterFamily.Grpc, InterceptorMethodShape.GrpcStreaming, InterceptorSignalOwnership.Trace, InterceptorErrorPolicy.GrpcStatusAndException, InterceptorDurationPolicy.None, GrpcClientBody: new GrpcClientBodyDescriptor(GrpcClientCallShape.ServerStreaming, "GrpcNetClientAsyncServerStreaming", "client", "global::Qyl.OpenTelemetry.AutoInstrumentation.QylInterceptedGrpcNetClient")),
            new InterceptorEmissionDescriptor(InterceptorKind.GrpcNetClientAsyncClientStreamingCall, InterceptorEmitterFamily.Grpc, InterceptorMethodShape.GrpcStreaming, InterceptorSignalOwnership.Trace, InterceptorErrorPolicy.GrpcStatusAndException, InterceptorDurationPolicy.None, GrpcClientBody: new GrpcClientBodyDescriptor(GrpcClientCallShape.ClientStreaming, "GrpcNetClientAsyncClientStreaming", "client", "global::Qyl.OpenTelemetry.AutoInstrumentation.QylInterceptedGrpcNetClient")),
            new InterceptorEmissionDescriptor(InterceptorKind.GrpcNetClientAsyncDuplexStreamingCall, InterceptorEmitterFamily.Grpc, InterceptorMethodShape.GrpcStreaming, InterceptorSignalOwnership.Trace, InterceptorErrorPolicy.GrpcStatusAndException, InterceptorDurationPolicy.None, GrpcClientBody: new GrpcClientBodyDescriptor(GrpcClientCallShape.DuplexStreaming, "GrpcNetClientAsyncDuplexStreaming", "client", "global::Qyl.OpenTelemetry.AutoInstrumentation.QylInterceptedGrpcNetClient")),
            new InterceptorEmissionDescriptor(InterceptorKind.KafkaProducer, InterceptorEmitterFamily.Messaging, InterceptorMethodShape.AsyncOrSyncValue, InterceptorSignalOwnership.Trace, InterceptorErrorPolicy.Exception, InterceptorDurationPolicy.None, TraceBody: new TraceInterceptorBodyDescriptor("KafkaProducer", "producer", RuntimeHelper: new TraceRuntimeHelperDescriptor("global::Qyl.OpenTelemetry.AutoInstrumentation.QylInterceptedKafka", "StartProducerActivity", "RecordException"))),
            new InterceptorEmissionDescriptor(InterceptorKind.KafkaConsumer, InterceptorEmitterFamily.Messaging, InterceptorMethodShape.AsyncOrSyncValue, InterceptorSignalOwnership.Trace, InterceptorErrorPolicy.Exception, InterceptorDurationPolicy.None, TraceBody: new TraceInterceptorBodyDescriptor("KafkaConsumer", "consumer", RuntimeHelper: new TraceRuntimeHelperDescriptor("global::Qyl.OpenTelemetry.AutoInstrumentation.QylInterceptedKafka", "StartConsumerActivity", "RecordException"))),
            new InterceptorEmissionDescriptor(InterceptorKind.MassTransitMessageOperation, InterceptorEmitterFamily.Messaging, InterceptorMethodShape.AsyncTask, InterceptorSignalOwnership.Trace, InterceptorErrorPolicy.Exception, InterceptorDurationPolicy.None, TraceBody: new TraceInterceptorBodyDescriptor("MassTransit", "endpoint", RuntimeHelper: new TraceRuntimeHelperDescriptor("global::Qyl.OpenTelemetry.AutoInstrumentation.QylInterceptedMassTransit", "StartActivity", "RecordException", TraceStartActivityArgumentKind.TargetMethodName))),
            new InterceptorEmissionDescriptor(InterceptorKind.NServiceBusMessageOperation, InterceptorEmitterFamily.Messaging, InterceptorMethodShape.AsyncTask, InterceptorSignalOwnership.TraceAndMetric, InterceptorErrorPolicy.Exception, InterceptorDurationPolicy.RuntimeMetric, TraceBody: new TraceInterceptorBodyDescriptor("NServiceBus", "endpoint", DurationMetric: new TraceDurationMetricDescriptor("global::Qyl.OpenTelemetry.AutoInstrumentation.QylInterceptedNServiceBus", "GetTimestamp", "RecordDuration", TraceDurationMetricArgumentKind.TargetMethodName), RuntimeHelper: new TraceRuntimeHelperDescriptor("global::Qyl.OpenTelemetry.AutoInstrumentation.QylInterceptedNServiceBus", "StartActivity", "RecordException", TraceStartActivityArgumentKind.TargetMethodName))),
            new InterceptorEmissionDescriptor(InterceptorKind.QuartzJobExecute, InterceptorEmitterFamily.Scheduler, InterceptorMethodShape.AsyncTask, InterceptorSignalOwnership.Trace, InterceptorErrorPolicy.Exception, InterceptorDurationPolicy.None, TraceBody: new TraceInterceptorBodyDescriptor("Quartz", "job", AsyncObservation: new TraceAsyncObservationDescriptor("global::Qyl.OpenTelemetry.AutoInstrumentation.QylInterceptedQuartz.ObserveAsync"), RuntimeHelper: new TraceRuntimeHelperDescriptor("global::Qyl.OpenTelemetry.AutoInstrumentation.QylInterceptedQuartz", "StartActivity", "RecordException"))),
            new InterceptorEmissionDescriptor(InterceptorKind.StackExchangeRedisCommandAsync, InterceptorEmitterFamily.Cache, InterceptorMethodShape.AsyncValue, InterceptorSignalOwnership.Trace, InterceptorErrorPolicy.Exception, InterceptorDurationPolicy.None, TraceBody: new TraceInterceptorBodyDescriptor("StackExchangeRedis", "database", RuntimeHelper: new TraceRuntimeHelperDescriptor("global::Qyl.OpenTelemetry.AutoInstrumentation.QylInterceptedRedis", "StartCommandActivity", "RecordException", TraceStartActivityArgumentKind.RedisOperationName))),
            new InterceptorEmissionDescriptor(InterceptorKind.GraphQlDocumentExecuter, InterceptorEmitterFamily.GraphQl, InterceptorMethodShape.AsyncTask, InterceptorSignalOwnership.Trace, InterceptorErrorPolicy.Exception, InterceptorDurationPolicy.None, TraceBody: new TraceInterceptorBodyDescriptor("GraphQl", "executer", AsyncObservation: new TraceAsyncObservationDescriptor("global::Qyl.OpenTelemetry.AutoInstrumentation.QylInterceptedGraphQl.ObserveAsync"), ActivityEnrichment: new TraceActivityEnrichmentDescriptor("global::Qyl.OpenTelemetry.AutoInstrumentation.QylInterceptedGraphQl", "RecordExecutionOptions", TraceActivityEnrichmentArgumentKind.GraphQlExecutionOptions), RuntimeHelper: new TraceRuntimeHelperDescriptor("global::Qyl.OpenTelemetry.AutoInstrumentation.QylInterceptedGraphQl", "StartActivity", "RecordException"))),
            new InterceptorEmissionDescriptor(InterceptorKind.EntityFrameworkCoreDbContext, InterceptorEmitterFamily.Database, InterceptorMethodShape.AsyncOrSyncValue, InterceptorSignalOwnership.Trace, InterceptorErrorPolicy.Exception, InterceptorDurationPolicy.None, TraceBody: new TraceInterceptorBodyDescriptor("EntityFrameworkCoreDbContext", "dbContext", RuntimeHelper: new TraceRuntimeHelperDescriptor("global::Qyl.OpenTelemetry.AutoInstrumentation.QylInterceptedEntityFrameworkCore", "StartActivity", "RecordException", TraceStartActivityArgumentKind.TargetMethodName))),
            new InterceptorEmissionDescriptor(InterceptorKind.EntityFrameworkCoreQueryable, InterceptorEmitterFamily.Database, InterceptorMethodShape.AsyncOrSyncValue, InterceptorSignalOwnership.Trace, InterceptorErrorPolicy.Exception, InterceptorDurationPolicy.None, TraceBody: new TraceInterceptorBodyDescriptor("EntityFrameworkCoreQueryable", "query", RuntimeHelper: new TraceRuntimeHelperDescriptor("global::Qyl.OpenTelemetry.AutoInstrumentation.QylInterceptedEntityFrameworkCore", "StartActivity", "RecordException", TraceStartActivityArgumentKind.TargetMethodName))),
            new InterceptorEmissionDescriptor(InterceptorKind.MongoDbCollection, InterceptorEmitterFamily.Database, InterceptorMethodShape.AsyncOrSyncValue, InterceptorSignalOwnership.Trace, InterceptorErrorPolicy.Exception, InterceptorDurationPolicy.None, TraceBody: new TraceInterceptorBodyDescriptor("MongoDb", "collection", AsyncObservation: new TraceAsyncObservationDescriptor("global::Qyl.OpenTelemetry.AutoInstrumentation.QylInterceptedMongoDb.ObserveAsync"), RuntimeHelper: new TraceRuntimeHelperDescriptor("global::Qyl.OpenTelemetry.AutoInstrumentation.QylInterceptedMongoDb", "StartActivity", "RecordException", TraceStartActivityArgumentKind.TargetMethodName))),
            new InterceptorEmissionDescriptor(InterceptorKind.DbCommand, InterceptorEmitterFamily.Database, InterceptorMethodShape.AsyncOrSyncValue, InterceptorSignalOwnership.TraceAndMetric, InterceptorErrorPolicy.Exception, InterceptorDurationPolicy.RuntimeMetric, DbCommandBody: new DbCommandBodyDescriptor("DbCommand", "command", "global::Qyl.OpenTelemetry.AutoInstrumentation.QylInterceptedDbCommand", "global::Qyl.OpenTelemetry.AutoInstrumentation.QylInterceptedDbCommand", "GetTimestamp", "StartActivity", "ObserveAsync", "RecordException", "RecordDuration")),
            new InterceptorEmissionDescriptor(InterceptorKind.RabbitMqBasicPublish, InterceptorEmitterFamily.Messaging, InterceptorMethodShape.AsyncOrSyncVoid, InterceptorSignalOwnership.Trace, InterceptorErrorPolicy.Exception, InterceptorDurationPolicy.None, TraceBody: new TraceInterceptorBodyDescriptor("RabbitMq", "channel", RuntimeHelper: new TraceRuntimeHelperDescriptor("global::Qyl.OpenTelemetry.AutoInstrumentation.QylInterceptedRabbitMq", "StartPublishActivity", "RecordException", TraceStartActivityArgumentKind.RabbitMqExchange))),
            new InterceptorEmissionDescriptor(InterceptorKind.ILoggerExtensionLog, InterceptorEmitterFamily.Logging, InterceptorMethodShape.Void, InterceptorSignalOwnership.Log, InterceptorErrorPolicy.RuntimeDelegate, InterceptorDurationPolicy.None, LoggerBody: new LoggerBodyDescriptor(LoggerInterceptorBodyKind.LoggerExtensionLog, "LoggerExtensions", "global::Qyl.OpenTelemetry.AutoInstrumentation.QylInterceptedLogger")),
            new InterceptorEmissionDescriptor(InterceptorKind.ILoggerLog, InterceptorEmitterFamily.Logging, InterceptorMethodShape.Void, InterceptorSignalOwnership.Log, InterceptorErrorPolicy.RuntimeDelegate, InterceptorDurationPolicy.None, LoggerBody: new LoggerBodyDescriptor(LoggerInterceptorBodyKind.ILoggerLog, "ILogger_Log", "global::Qyl.OpenTelemetry.AutoInstrumentation.QylInterceptedLogger")),
            new InterceptorEmissionDescriptor(InterceptorKind.NLogLogger, InterceptorEmitterFamily.Logging, InterceptorMethodShape.Void, InterceptorSignalOwnership.Log, InterceptorErrorPolicy.Exception, InterceptorDurationPolicy.None, ExternalLoggerBody: new ExternalLoggerBodyDescriptor("global::Qyl.OpenTelemetry.AutoInstrumentation.QylInterceptedExternalLogger", "global::Qyl.OpenTelemetry.AutoInstrumentation.QylInstrumentationDomains.LogNLog")),
            new InterceptorEmissionDescriptor(InterceptorKind.Log4NetLogger, InterceptorEmitterFamily.Logging, InterceptorMethodShape.Void, InterceptorSignalOwnership.Log, InterceptorErrorPolicy.Exception, InterceptorDurationPolicy.None, ExternalLoggerBody: new ExternalLoggerBodyDescriptor("global::Qyl.OpenTelemetry.AutoInstrumentation.QylInterceptedExternalLogger", "global::Qyl.OpenTelemetry.AutoInstrumentation.QylInstrumentationDomains.LogLog4Net")));
}
