using ANcpLua.Roslyn.Utilities;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Qyl.OpenTelemetry.AutoInstrumentation.SourceGenerators;

/// <summary>
/// Telemetry CONSUMER — the first consumer of the <see cref="QylSemanticContractProducer"/> contract.
/// In its standard phase it binds the pre-compilation <c>[QylSemanticBinding]</c> attributes (visible
/// because they were emitted into the initial compilation) and emits an AOT-safe recorder per bound
/// type: pure <c>activity.SetTag(...)</c>, no reflection, no IL rewrite. The generated telemetry is
/// compiled into the application.
///
/// <para>Inert by design: with no contract (no <c>[QylSemanticBinding]</c> types in the compilation)
/// it emits nothing.</para>
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class QylSemanticTelemetryGenerator : IIncrementalGenerator
{
    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(context.CompilationProvider, static (context, compilation) =>
        {
            var marker = compilation.GetTypeByMetadataName(QylSemanticContractProducer.BindingAttributeMetadataName);
            if (marker is null)
                return;

            var boundTypes = CollectBoundTypes(compilation, marker);
            if (boundTypes.Count is 0)
                return;

            context.AddSource("QylSemanticTelemetry.g.cs", SourceText.From(EmitRecorders(boundTypes), Encoding.UTF8));
        });
    }

    private readonly record struct BoundType(string TypeFqn, string SimpleName, IReadOnlyList<(string Property, string Attribute)> Bindings);

    private static List<BoundType> CollectBoundTypes(Compilation compilation, INamedTypeSymbol marker)
    {
        var result = new List<BoundType>();
        foreach (var type in EnumerateSourceTypes(compilation.GlobalNamespace))
        {
            var bindings = new List<(string Property, string Attribute)>();
            foreach (var attribute in type.GetAttributes())
            {
                if (SymbolEqualityComparer.Default.Equals(attribute.AttributeClass, marker) &&
                    attribute.GetConstructorArgument<string>(0) is { } property &&
                    attribute.GetConstructorArgument<string>(1) is { } semanticAttribute)
                {
                    bindings.Add((property, semanticAttribute));
                }
            }

            if (bindings.Count > 0)
            {
                result.Add(new BoundType(
                    type.ToDisplayString(),
                    type.Name,
                    bindings.OrderBy(static binding => binding.Property, StringComparer.Ordinal).ToList()));
            }
        }

        return result.OrderBy(static bound => bound.TypeFqn, StringComparer.Ordinal).ToList();
    }

    private static IEnumerable<INamedTypeSymbol> EnumerateSourceTypes(INamespaceSymbol namespaceSymbol)
    {
        foreach (var type in namespaceSymbol.GetTypeMembers())
        {
            if (type.Locations.Any(static location => location.IsInSource))
                yield return type;
        }

        foreach (var child in namespaceSymbol.GetNamespaceMembers())
        {
            foreach (var type in EnumerateSourceTypes(child))
                yield return type;
        }
    }

    private static string EmitRecorders(List<BoundType> boundTypes)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/> AOT-safe semantic telemetry generated from the qyl semantic contract.");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("namespace Qyl.OpenTelemetry.AutoInstrumentation.Generated;");

        foreach (var bound in boundTypes)
        {
            builder.AppendLine($"/// <summary>Records OpenTelemetry semantic-convention tags for <see cref=\"global::{bound.TypeFqn}\"/>. Pure SetTag; no reflection.</summary>");
            builder.AppendLine($"internal static class {bound.SimpleName}Telemetry");
            builder.AppendLine("{");
            builder.AppendLine($"    public static void Record(global::System.Diagnostics.Activity? activity, global::{bound.TypeFqn} value)");
            builder.AppendLine("    {");
            builder.AppendLine("        if (activity is null) return;");
            foreach (var (property, attribute) in bound.Bindings)
                builder.AppendLine($"        activity.SetTag(\"{Escape(attribute)}\", value.{property});");
            builder.AppendLine("    }");
            builder.AppendLine("}");
        }

        return builder.ToString();
    }

    private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
