using ANcpLua.Roslyn.Utilities;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Qyl.OpenTelemetry.AutoInstrumentation.SourceGenerators;

/// <summary>
/// Semantic-contract PRODUCER. Reads <c>*.qyl-semantic-contract.tsv</c> additional files and emits,
/// via <c>RegisterPreCompilationSourceOutput</c> (RSEXPERIMENTAL007), the shared
/// <c>[QylSemanticBinding(property, attribute)]</c> attribute plus attribute-decorated
/// <c>partial</c>s of the user's types into the INITIAL compilation.
///
/// <para>Because the output lands in the initial compilation, it is visible to every other
/// generator's standard phase — qyl's own <see cref="QylSemanticTelemetryGenerator"/> is the first
/// consumer, and third-party generators (logging, metrics, validation) can bind the same contract
/// without referencing qyl. Within qyl's own assembly the split is redundant; it exists to publish
/// the contract across the generator boundary.</para>
///
/// <para>Inert by design: with no contract additional file (every existing demo), it emits nothing,
/// so it cannot affect projects that do not opt in.</para>
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class QylSemanticContractProducer : IIncrementalGenerator
{
    internal const string ContractFileSuffix = "qyl-semantic-contract.tsv";
    internal const string GeneratedNamespace = "Qyl.OpenTelemetry.AutoInstrumentation.Generated";
    internal const string BindingAttributeMetadataName = GeneratedNamespace + ".QylSemanticBindingAttribute";

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var contract = context.AdditionalTextsProvider
            .Where(static text => text.Path.Replace('\\', '/').EndsWithIgnoreCase(ContractFileSuffix))
            .Select(static (text, cancellationToken) => text.GetText(cancellationToken)?.ToString() ?? string.Empty)
            .Collect();

        context.RegisterPreCompilationSourceOutput(contract, static (precompilation, texts) =>
        {
            var rows = ParseContract(string.Concat(texts));
            if (rows.Count is 0)
                return;

            precompilation.AddSource("QylSemanticBindingAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8));

            foreach (var byType in rows.GroupBy(static row => row.TypeFqn, StringComparer.Ordinal))
            {
                precompilation.AddSource(
                    byType.Key.Replace('.', '_') + ".SemanticContract.g.cs",
                    SourceText.From(BuildContractPartial(byType.Key, byType.ToList()), Encoding.UTF8));
            }
        });
    }

    private const string AttributeSource =
"""
// <auto-generated/> shared semantic-contract vocabulary (pre-compilation phase).
#nullable enable
namespace Qyl.OpenTelemetry.AutoInstrumentation.Generated;

/// <summary>Binds a property of the annotated type to an OpenTelemetry attribute key. Emitted into
/// the initial compilation so any generator can read it from the semantic model.</summary>
[global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
internal sealed class QylSemanticBindingAttribute : global::System.Attribute
{
    public QylSemanticBindingAttribute(string property, string attribute)
    {
        Property = property;
        Attribute = attribute;
    }

    public string Property { get; }
    public string Attribute { get; }
}
""";

    private readonly record struct ContractRow(string TypeFqn, string Property, string Attribute);

    private static List<ContractRow> ParseContract(string tsv)
    {
        var rows = new List<ContractRow>();
        foreach (var rawLine in tsv.Split('\n'))
        {
            var line = rawLine.TrimEnd('\r');
            if (line.Length is 0 || line[0] is '#')
                continue;

            var columns = line.Split('\t');
            if (columns.Length < 3)
                continue;

            rows.Add(new ContractRow(columns[0].Trim(), columns[1].Trim(), columns[2].Trim()));
        }

        return rows;
    }

    private static string BuildContractPartial(string typeFqn, List<ContractRow> rows)
    {
        // Top-level types only: a dotted FQN cannot encode nested-type ('Outer+Inner') containment.
        var lastDot = typeFqn.LastIndexOf('.');
        var namespaceName = lastDot < 0 ? null : typeFqn.Substring(0, lastDot);
        var typeName = lastDot < 0 ? typeFqn : typeFqn.Substring(lastDot + 1);

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/> compiler-visible semantic contract (pre-compilation phase).");
        builder.AppendLine("#nullable enable");
        if (namespaceName is not null)
        {
            builder.AppendLine($"namespace {namespaceName};");
            builder.AppendLine();
        }

        foreach (var row in rows)
        {
            builder.AppendLine(
                $"[global::{GeneratedNamespace}.QylSemanticBindingAttribute(\"{Escape(row.Property)}\", \"{Escape(row.Attribute)}\")]");
        }

        // No access modifier: a partial part without one merges with a public/internal user part
        // without an accessibility conflict. The user's type must be declared `partial class`.
        builder.AppendLine($"partial class {typeName} {{ }}");
        return builder.ToString();
    }

    private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
