using System.Collections.Immutable;
using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Qyl.OpenTelemetry.AutoInstrumentation.SourceGenerators;

/// <summary>
/// Emits the qyl Telemetry Capability Graph (TCG): a machine-readable manifest of every telemetry
/// capability qyl can produce, baked as a compile-time <c>const</c> into the core assembly.
/// </summary>
/// <remarks>
/// First-Light step 1 of the self-describing-observability substrate. Instead of leaving an external
/// entity to discover a service's telemetry surface by sampling exported spans over time, the binary
/// <em>declares</em> its complete possible OpenTelemetry surface — derived deterministically from the
/// instrumentation contract. Each capability is tagged with <c>provenance</c> (whether the attribute
/// keys are owned at compile time by an interceptor/init lane, or carried at runtime by a listener),
/// which is exactly the distinction a consumer cannot recover from samples alone.
///
/// <para>
/// Like <see cref="SemConvRegistryGenerator"/>, the generator runs only inside the compiler and emits
/// only into the <c>Qyl.OpenTelemetry.AutoInstrumentation</c> assembly. The manifest is a pure function
/// of <see cref="InstrumentationContract.Items"/>, so the output is byte-reproducible.
/// </para>
/// </remarks>
[Generator(LanguageNames.CSharp)]
public sealed class TelemetryCapabilityGraphGenerator : IIncrementalGenerator
{
    private const string CoreAssemblyName = "Qyl.OpenTelemetry.AutoInstrumentation";
    private const string SchemaVersion = "0.1.0-draft";
    private const string GeneratorId =
        "Qyl.OpenTelemetry.AutoInstrumentation.SourceGenerators.TelemetryCapabilityGraphGenerator";

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var emitToThisAssembly = context.CompilationProvider.Select(
            static (compilation, _) =>
                string.Equals(compilation.AssemblyName, CoreAssemblyName, StringComparison.Ordinal));

        context.RegisterSourceOutput(emitToThisAssembly, static (sourceContext, emit) =>
        {
            if (!emit)
                return;

            sourceContext.AddSource(
                "QylTelemetryCapabilityGraph.g.cs",
                SourceText.From(EmitSource(), Encoding.UTF8));
        });
    }

    private static string EmitSource()
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("namespace Qyl.OpenTelemetry.AutoInstrumentation.Internal;");
        builder.AppendLine();
        builder.AppendLine("/// <summary>");
        builder.AppendLine("/// The qyl Telemetry Capability Graph: the complete, machine-readable manifest of every");
        builder.AppendLine("/// telemetry capability this build can produce, generated from the instrumentation contract.");
        builder.AppendLine("/// </summary>");
        builder.AppendLine("internal static class QylTelemetryCapabilityGraph");
        builder.AppendLine("{");
        builder.AppendLine("    /// <summary>The Telemetry Capability Graph serialized as compact JSON (schema " + SchemaVersion + ").</summary>");
        builder.Append("    public const string Json = ");
        AppendCSharpStringLiteral(builder, BuildManifestJson());
        builder.AppendLine(";");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string BuildManifestJson()
    {
        var items = InstrumentationContract.Items;

        var traces = 0;
        var metrics = 0;
        var logs = 0;
        foreach (var item in items)
        {
            switch (item.Signal)
            {
                case InstrumentationSignal.Traces:
                    traces++;
                    break;
                case InstrumentationSignal.Metrics:
                    metrics++;
                    break;
                case InstrumentationSignal.Logs:
                    logs++;
                    break;
            }
        }

        var json = new StringBuilder();
        json.Append('{');
        AppendProperty(json, "schemaVersion", SchemaVersion);
        json.Append(',');
        AppendProperty(json, "generator", GeneratorId);
        json.Append(',');
        json.Append("\"capabilityCount\":").Append(items.Length.ToString(CultureInfo.InvariantCulture));
        json.Append(',');
        json.Append("\"signals\":{");
        json.Append("\"traces\":").Append(traces.ToString(CultureInfo.InvariantCulture)).Append(',');
        json.Append("\"metrics\":").Append(metrics.ToString(CultureInfo.InvariantCulture)).Append(',');
        json.Append("\"logs\":").Append(logs.ToString(CultureInfo.InvariantCulture));
        json.Append("},");
        json.Append("\"capabilities\":[");
        for (var i = 0; i < items.Length; i++)
        {
            if (i > 0)
                json.Append(',');
            AppendCapability(json, items[i]);
        }

        json.Append(']');
        json.Append('}');
        return json.ToString();
    }

    private static void AppendCapability(StringBuilder json, in InstrumentationContractItem item)
    {
        json.Append('{');
        AppendProperty(json, "id", item.ContractItemId);
        json.Append(',');
        AppendProperty(json, "key", item.Key);
        json.Append(',');
        AppendProperty(json, "signal", SignalName(item.Signal));
        json.Append(',');
        AppendProperty(json, "lane", item.Lane.ToString());
        json.Append(',');
        AppendProperty(json, "status", item.QylStatus.ToString());
        json.Append(',');
        AppendProperty(json, "payloadAccess", item.PayloadAccess.ToString());
        json.Append(',');
        AppendProperty(json, "provenance", Provenance(item.Lane));
        json.Append(',');
        AppendProperty(json, "instrumentationId", item.InstrumentationId);
        json.Append(',');
        AppendProperty(json, "supportedVersions", item.SupportedVersions);
        json.Append(',');
        AppendProperty(json, "owner", item.PrimaryOwner);
        json.Append(',');
        AppendStringArray(json, "libraries", item.Libraries);
        json.Append(',');
        AppendStringArray(json, "attributes", item.AttributeNames);
        json.Append('}');
    }

    private static string SignalName(InstrumentationSignal signal) => signal switch
    {
        InstrumentationSignal.Traces => "traces",
        InstrumentationSignal.Metrics => "metrics",
        InstrumentationSignal.Logs => "logs",
        _ => "none",
    };

    // The vision's load-bearing distinction: which attribute keys are owned at compile time
    // (interceptor / framework-init lanes) versus carried as runtime payload values (listener lanes).
    private static string Provenance(InstrumentationContractLane lane) => lane switch
    {
        InstrumentationContractLane.SourceInterceptor => "compile-time",
        InstrumentationContractLane.FrameworkInitialization => "compile-time",
        InstrumentationContractLane.RuntimePublicTelemetry => "runtime",
        InstrumentationContractLane.OfficialLibraryHook => "runtime",
        InstrumentationContractLane.EnvironmentControl => "control",
        InstrumentationContractLane.InstrumentationOption => "control",
        InstrumentationContractLane.UnsupportedNativeAot => "unsupported",
        _ => "unknown",
    };

    private static void AppendProperty(StringBuilder json, string name, string value)
    {
        AppendJsonString(json, name);
        json.Append(':');
        AppendJsonString(json, value);
    }

    private static void AppendStringArray(StringBuilder json, string name, ImmutableArray<string> values)
    {
        AppendJsonString(json, name);
        json.Append(":[");
        for (var i = 0; i < values.Length; i++)
        {
            if (i > 0)
                json.Append(',');
            AppendJsonString(json, values[i]);
        }

        json.Append(']');
    }

    private static void AppendJsonString(StringBuilder json, string value)
    {
        json.Append('"');
        foreach (var c in value)
        {
            switch (c)
            {
                case '"':
                    json.Append("\\\"");
                    break;
                case '\\':
                    json.Append("\\\\");
                    break;
                case '\n':
                    json.Append("\\n");
                    break;
                case '\r':
                    json.Append("\\r");
                    break;
                case '\t':
                    json.Append("\\t");
                    break;
                default:
                    if (c < ' ')
                        json.Append("\\u").Append(((int)c).ToString("x4", CultureInfo.InvariantCulture));
                    else
                        json.Append(c);
                    break;
            }
        }

        json.Append('"');
    }

    private static void AppendCSharpStringLiteral(StringBuilder builder, string value)
    {
        builder.Append('"');
        builder.Append(value.Replace("\\", "\\\\").Replace("\"", "\\\""));
        builder.Append('"');
    }
}
