// <auto-generated/>
// Regenerate with tools/generate-contract-artifacts.py --write.
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace Qyl.AutoInstrumentation.SourceGenerators;

internal enum InstrumentationContractKind
{
    SignalSpecificInstrumentationPromise,
    GlobalEnvironmentControl,
    InstrumentationOption,
}

internal enum InstrumentationSignal
{
    None,
    Traces,
    Metrics,
    Logs,
}

internal enum InstrumentationContractLane
{
    SourceInterceptor,
    RuntimePublicTelemetry,
    FrameworkInitialization,
    OfficialLibraryHook,
    EnvironmentControl,
    InstrumentationOption,
    UnsupportedNativeAot,
}

internal enum QylContractStatus
{
    Implemented,
    ControlBound,
    OptionBound,
    ResearchRequired,
    UnsupportedNativeAot,
}

internal enum SourceVisibility
{
    UserCode,
    LibraryInternal,
    Both,
    NotApplicable,
}

internal enum PayloadAccess
{
    TypedPublic,
    ReflectionRequired,
    NotApplicable,
}

internal enum QylEvidenceLevel
{
    None,
    VerifiedNativeAot,
    VerifiedManaged,
    CompileBindingOnly,
    OptionBound,
}

internal readonly record struct InstrumentationContractItem(
    int Index,
    string ContractItemId,
    InstrumentationContractKind Kind,
    string Key,
    InstrumentationSignal Signal,
    string InstrumentationId,
    string EnvironmentVariable,
    string SupportedVersions,
    ImmutableArray<string> Libraries,
    ImmutableArray<string> InstrumentationTypes,
    string Promise,
    ImmutableArray<string> AttributeNames,
    InstrumentationContractLane Lane,
    QylContractStatus QylStatus,
    SourceVisibility SourceVisibility,
    PayloadAccess PayloadAccess,
    QylEvidenceLevel EvidenceLevel,
    string PrimaryOwner,
    ImmutableArray<string> Evidence);

internal static class InstrumentationContract
{
    public const int SignalSpecificInstrumentationPromiseCount = 37;
    public const int GlobalEnvironmentControlCount = 7;
    public const int InstrumentationOptionCount = 16;
    public const int TotalCount =
        SignalSpecificInstrumentationPromiseCount +
        GlobalEnvironmentControlCount +
        InstrumentationOptionCount;

    public const int TracesSignalSpecificPromiseCount = 26;
    public const int MetricsSignalSpecificPromiseCount = 8;
    public const int LogsSignalSpecificPromiseCount = 3;
    public const int UniqueInstrumentationIdCount = 31;
    public const int ImplementedSignalPromiseCount = 33;
    public const int SourceInterceptorSignalPromiseCount = 22;
    public const int RuntimePublicTelemetrySignalPromiseCount = 10;
    public const int UnsupportedNativeAotSignalPromiseCount = 4;

    public const string AspNetCoreComponentsMeterName = "Microsoft.AspNetCore.Components";
    public const string AspNetCoreComponentsNavigationMetricName = "aspnetcore.components.navigation";

    public static readonly ImmutableArray<string> ImplementedSignalKeys =
        ImmutableArray.Create(
            "signals.traces.ADONET",
            "signals.traces.ASPNETCORE",
            "signals.traces.AZURE",
            "signals.traces.ELASTICSEARCH",
            "signals.traces.ELASTICTRANSPORT",
            "signals.traces.ENTITYFRAMEWORKCORE",
            "signals.traces.GRAPHQL",
            "signals.traces.GRPCNETCLIENT",
            "signals.traces.HTTPCLIENT",
            "signals.traces.KAFKA",
            "signals.traces.MASSTRANSIT",
            "signals.traces.MONGODB",
            "signals.traces.MYSQLCONNECTOR",
            "signals.traces.MYSQLDATA",
            "signals.traces.NPGSQL",
            "signals.traces.NSERVICEBUS",
            "signals.traces.ORACLEMDA",
            "signals.traces.RABBITMQ",
            "signals.traces.QUARTZ",
            "signals.traces.SQLCLIENT",
            "signals.traces.SQLITE",
            "signals.traces.STACKEXCHANGEREDIS",
            "signals.traces.WCFCLIENT",
            "signals.metrics.ASPNETCORE",
            "signals.metrics.HTTPCLIENT",
            "signals.metrics.NETRUNTIME",
            "signals.metrics.NPGSQL",
            "signals.metrics.NSERVICEBUS",
            "signals.metrics.PROCESS",
            "signals.metrics.SQLCLIENT",
            "signals.logs.ILOGGER",
            "signals.logs.LOG4NET",
            "signals.logs.NLOG"
        );

    public static readonly ImmutableArray<string> SourceInterceptorSignalKeys =
        ImmutableArray.Create(
            "signals.traces.ADONET",
            "signals.traces.ELASTICSEARCH",
            "signals.traces.ELASTICTRANSPORT",
            "signals.traces.GRAPHQL",
            "signals.traces.HTTPCLIENT",
            "signals.traces.KAFKA",
            "signals.traces.MASSTRANSIT",
            "signals.traces.MONGODB",
            "signals.traces.MYSQLCONNECTOR",
            "signals.traces.MYSQLDATA",
            "signals.traces.NPGSQL",
            "signals.traces.NSERVICEBUS",
            "signals.traces.ORACLEMDA",
            "signals.traces.RABBITMQ",
            "signals.traces.QUARTZ",
            "signals.traces.SQLCLIENT",
            "signals.traces.SQLITE",
            "signals.traces.STACKEXCHANGEREDIS",
            "signals.traces.WCFCLIENT",
            "signals.logs.ILOGGER",
            "signals.logs.LOG4NET",
            "signals.logs.NLOG"
        );

    public static readonly ImmutableArray<string> RuntimePublicTelemetrySignalKeys =
        ImmutableArray.Create(
            "signals.traces.ASPNETCORE",
            "signals.traces.ENTITYFRAMEWORKCORE",
            "signals.traces.GRPCNETCLIENT",
            "signals.metrics.ASPNETCORE",
            "signals.metrics.HTTPCLIENT",
            "signals.metrics.NETRUNTIME",
            "signals.metrics.NPGSQL",
            "signals.metrics.NSERVICEBUS",
            "signals.metrics.PROCESS",
            "signals.metrics.SQLCLIENT"
        );

    public static readonly ImmutableArray<string> UnsupportedNativeAotSignalKeys =
        ImmutableArray.Create(
            "signals.traces.ASPNET",
            "signals.traces.WCFCORE",
            "signals.traces.WCFSERVICE",
            "signals.metrics.ASPNET"
        );

    public static readonly ImmutableArray<InstrumentationContractItem> Items =
        ImmutableArray.Create(
            new InstrumentationContractItem(1, "OTEL_DOTNET_AUTO_CONTRACT_001", InstrumentationContractKind.SignalSpecificInstrumentationPromise, "signals.traces.ADONET", InstrumentationSignal.Traces, "ADONET", "OTEL_DOTNET_AUTO_TRACES_ADONET_INSTRUMENTATION_ENABLED", "System.Data.Common >=4.0.0 && <11.0.0; System.Data for .NET Framework >=2.0.0 && <5.0.0; netstandard >=2.0.0 && <3.0.0", ImmutableArray.Create("ADO.NET"), ImmutableArray.Create("bytecode"), "Generic ADO.NET instrumentation covers DbCommand methods. Only implementations for overridden methods are covered. Implementations using the C# new keyword typically need specific implementations. Does not cover libraries covered by SQLCLIENT, NPGSQL, MYSQLDATA, MYSQLCONNECTOR, ORACLEMDA, or SQLITE.", ImmutableArray<string>.Empty, InstrumentationContractLane.SourceInterceptor, QylContractStatus.Implemented, SourceVisibility.UserCode, PayloadAccess.NotApplicable, QylEvidenceLevel.CompileBindingOnly, "QylAutoInstrumentationGenerator", ImmutableArray.Create("src/Qyl.AutoInstrumentation.SourceGenerators/QylAutoInstrumentationGenerator.cs", "tools/verify-source-interceptor-consumer.py")),
            new InstrumentationContractItem(2, "OTEL_DOTNET_AUTO_CONTRACT_002", InstrumentationContractKind.SignalSpecificInstrumentationPromise, "signals.traces.ASPNET", InstrumentationSignal.Traces, "ASPNET", "OTEL_DOTNET_AUTO_TRACES_ASPNET_INSTRUMENTATION_ENABLED", "*", ImmutableArray.Create("ASP.NET (.NET Framework) MVC / WebApi"), ImmutableArray.Create("source", "bytecode"), "Only integrated pipeline mode is supported.", ImmutableArray<string>.Empty, InstrumentationContractLane.UnsupportedNativeAot, QylContractStatus.UnsupportedNativeAot, SourceVisibility.UserCode, PayloadAccess.ReflectionRequired, QylEvidenceLevel.None, "unsupported by qyl NativeAOT substrate", ImmutableArray.Create("docs/coverage-matrix.md")),
            new InstrumentationContractItem(3, "OTEL_DOTNET_AUTO_CONTRACT_003", InstrumentationContractKind.SignalSpecificInstrumentationPromise, "signals.traces.ASPNETCORE", InstrumentationSignal.Traces, "ASPNETCORE", "OTEL_DOTNET_AUTO_TRACES_ASPNETCORE_INSTRUMENTATION_ENABLED", "*", ImmutableArray.Create("ASP.NET Core"), ImmutableArray.Create("source"), "signals.traces.ASPNETCORE instrumentation promise.", ImmutableArray<string>.Empty, InstrumentationContractLane.RuntimePublicTelemetry, QylContractStatus.Implemented, SourceVisibility.Both, PayloadAccess.TypedPublic, QylEvidenceLevel.VerifiedNativeAot, "Qyl public telemetry listeners/meters", ImmutableArray.Create("src/Qyl.AutoInstrumentation.DiagnosticListeners", "src/Qyl.AutoInstrumentation/QylMetricMeters.cs", "tools/verify-otlp-collector-fixtures.py")),
            new InstrumentationContractItem(4, "OTEL_DOTNET_AUTO_CONTRACT_004", InstrumentationContractKind.SignalSpecificInstrumentationPromise, "signals.traces.AZURE", InstrumentationSignal.Traces, "AZURE", "OTEL_DOTNET_AUTO_TRACES_AZURE_INSTRUMENTATION_ENABLED", "Azure.* prefixed packages released after 2021-10-01", ImmutableArray.Create("Azure SDK"), ImmutableArray.Create("source"), "signals.traces.AZURE instrumentation promise.", ImmutableArray<string>.Empty, InstrumentationContractLane.FrameworkInitialization, QylContractStatus.Implemented, SourceVisibility.UserCode, PayloadAccess.NotApplicable, QylEvidenceLevel.CompileBindingOnly, "QylAutoInstrumentationGenerator framework initialization", ImmutableArray.Create("src/Qyl.AutoInstrumentation.SourceGenerators/QylAutoInstrumentationGenerator.cs", "tools/verify-source-interceptor-consumer.py")),
            new InstrumentationContractItem(5, "OTEL_DOTNET_AUTO_CONTRACT_005", InstrumentationContractKind.SignalSpecificInstrumentationPromise, "signals.traces.ELASTICSEARCH", InstrumentationSignal.Traces, "ELASTICSEARCH", "OTEL_DOTNET_AUTO_TRACES_ELASTICSEARCH_INSTRUMENTATION_ENABLED", ">=8.0.0 && <8.10.0", ImmutableArray.Create("Elastic.Clients.Elasticsearch"), ImmutableArray.Create("source"), "Version >=8.10.0 is supported by ELASTICTRANSPORT instrumentation.", ImmutableArray<string>.Empty, InstrumentationContractLane.SourceInterceptor, QylContractStatus.Implemented, SourceVisibility.UserCode, PayloadAccess.NotApplicable, QylEvidenceLevel.CompileBindingOnly, "QylAutoInstrumentationGenerator", ImmutableArray.Create("src/Qyl.AutoInstrumentation.SourceGenerators/QylAutoInstrumentationGenerator.cs", "tools/verify-source-interceptor-consumer.py")),
            new InstrumentationContractItem(6, "OTEL_DOTNET_AUTO_CONTRACT_006", InstrumentationContractKind.SignalSpecificInstrumentationPromise, "signals.traces.ELASTICTRANSPORT", InstrumentationSignal.Traces, "ELASTICTRANSPORT", "OTEL_DOTNET_AUTO_TRACES_ELASTICTRANSPORT_INSTRUMENTATION_ENABLED", ">=0.4.16", ImmutableArray.Create("Elastic.Transport"), ImmutableArray.Create("source"), "signals.traces.ELASTICTRANSPORT instrumentation promise.", ImmutableArray<string>.Empty, InstrumentationContractLane.SourceInterceptor, QylContractStatus.Implemented, SourceVisibility.UserCode, PayloadAccess.NotApplicable, QylEvidenceLevel.CompileBindingOnly, "QylAutoInstrumentationGenerator", ImmutableArray.Create("src/Qyl.AutoInstrumentation.SourceGenerators/QylAutoInstrumentationGenerator.cs", "tools/verify-source-interceptor-consumer.py")),
            new InstrumentationContractItem(7, "OTEL_DOTNET_AUTO_CONTRACT_007", InstrumentationContractKind.SignalSpecificInstrumentationPromise, "signals.traces.ENTITYFRAMEWORKCORE", InstrumentationSignal.Traces, "ENTITYFRAMEWORKCORE", "OTEL_DOTNET_AUTO_TRACES_ENTITYFRAMEWORKCORE_INSTRUMENTATION_ENABLED", ">=6.0.12", ImmutableArray.Create("Microsoft.EntityFrameworkCore"), ImmutableArray.Create("source"), "signals.traces.ENTITYFRAMEWORKCORE instrumentation promise.", ImmutableArray<string>.Empty, InstrumentationContractLane.RuntimePublicTelemetry, QylContractStatus.Implemented, SourceVisibility.Both, PayloadAccess.TypedPublic, QylEvidenceLevel.VerifiedNativeAot, "Qyl public telemetry listeners/meters", ImmutableArray.Create("src/Qyl.AutoInstrumentation.DiagnosticListeners", "src/Qyl.AutoInstrumentation/QylMetricMeters.cs", "tools/verify-otlp-collector-fixtures.py")),
            new InstrumentationContractItem(8, "OTEL_DOTNET_AUTO_CONTRACT_008", InstrumentationContractKind.SignalSpecificInstrumentationPromise, "signals.traces.GRAPHQL", InstrumentationSignal.Traces, "GRAPHQL", "OTEL_DOTNET_AUTO_TRACES_GRAPHQL_INSTRUMENTATION_ENABLED", ">=7.5.0", ImmutableArray.Create("GraphQL"), ImmutableArray.Create("source"), "signals.traces.GRAPHQL instrumentation promise.", ImmutableArray<string>.Empty, InstrumentationContractLane.SourceInterceptor, QylContractStatus.Implemented, SourceVisibility.UserCode, PayloadAccess.NotApplicable, QylEvidenceLevel.CompileBindingOnly, "QylAutoInstrumentationGenerator", ImmutableArray.Create("src/Qyl.AutoInstrumentation.SourceGenerators/QylAutoInstrumentationGenerator.cs", "tools/verify-source-interceptor-consumer.py")),
            new InstrumentationContractItem(9, "OTEL_DOTNET_AUTO_CONTRACT_009", InstrumentationContractKind.SignalSpecificInstrumentationPromise, "signals.traces.GRPCNETCLIENT", InstrumentationSignal.Traces, "GRPCNETCLIENT", "OTEL_DOTNET_AUTO_TRACES_GRPCNETCLIENT_INSTRUMENTATION_ENABLED", ">=2.52.0 && <3.0.0", ImmutableArray.Create("Grpc.Net.Client"), ImmutableArray.Create("source"), "signals.traces.GRPCNETCLIENT instrumentation promise.", ImmutableArray<string>.Empty, InstrumentationContractLane.RuntimePublicTelemetry, QylContractStatus.Implemented, SourceVisibility.Both, PayloadAccess.TypedPublic, QylEvidenceLevel.CompileBindingOnly, "Qyl public telemetry listeners/meters", ImmutableArray.Create("src/Qyl.AutoInstrumentation.DiagnosticListeners", "src/Qyl.AutoInstrumentation/QylMetricMeters.cs", "tools/verify-otlp-collector-fixtures.py")),
            new InstrumentationContractItem(10, "OTEL_DOTNET_AUTO_CONTRACT_010", InstrumentationContractKind.SignalSpecificInstrumentationPromise, "signals.traces.HTTPCLIENT", InstrumentationSignal.Traces, "HTTPCLIENT", "OTEL_DOTNET_AUTO_TRACES_HTTPCLIENT_INSTRUMENTATION_ENABLED", "*", ImmutableArray.Create("System.Net.Http.HttpClient", "System.Net.HttpWebRequest"), ImmutableArray.Create("source"), "signals.traces.HTTPCLIENT instrumentation promise.", ImmutableArray<string>.Empty, InstrumentationContractLane.SourceInterceptor, QylContractStatus.Implemented, SourceVisibility.Both, PayloadAccess.NotApplicable, QylEvidenceLevel.VerifiedNativeAot, "QylAutoInstrumentationGenerator", ImmutableArray.Create("src/Qyl.AutoInstrumentation.SourceGenerators/QylAutoInstrumentationGenerator.cs", "tools/verify-source-interceptor-consumer.py")),
            new InstrumentationContractItem(11, "OTEL_DOTNET_AUTO_CONTRACT_011", InstrumentationContractKind.SignalSpecificInstrumentationPromise, "signals.traces.KAFKA", InstrumentationSignal.Traces, "KAFKA", "OTEL_DOTNET_AUTO_TRACES_KAFKA_INSTRUMENTATION_ENABLED", ">=1.4.0 && <3.0.0", ImmutableArray.Create("Confluent.Kafka"), ImmutableArray.Create("bytecode"), "Confluent.Kafka is supported from version >=1.8.2 on ARM64 for Windows and Linux, and >=1.9.2 on macOS.", ImmutableArray<string>.Empty, InstrumentationContractLane.SourceInterceptor, QylContractStatus.Implemented, SourceVisibility.UserCode, PayloadAccess.NotApplicable, QylEvidenceLevel.CompileBindingOnly, "QylAutoInstrumentationGenerator", ImmutableArray.Create("src/Qyl.AutoInstrumentation.SourceGenerators/QylAutoInstrumentationGenerator.cs", "tools/verify-source-interceptor-consumer.py")),
            new InstrumentationContractItem(12, "OTEL_DOTNET_AUTO_CONTRACT_012", InstrumentationContractKind.SignalSpecificInstrumentationPromise, "signals.traces.MASSTRANSIT", InstrumentationSignal.Traces, "MASSTRANSIT", "OTEL_DOTNET_AUTO_TRACES_MASSTRANSIT_INSTRUMENTATION_ENABLED", ">=8.0.0", ImmutableArray.Create("MassTransit"), ImmutableArray.Create("source"), "signals.traces.MASSTRANSIT instrumentation promise.", ImmutableArray<string>.Empty, InstrumentationContractLane.SourceInterceptor, QylContractStatus.Implemented, SourceVisibility.UserCode, PayloadAccess.NotApplicable, QylEvidenceLevel.CompileBindingOnly, "QylAutoInstrumentationGenerator", ImmutableArray.Create("src/Qyl.AutoInstrumentation.SourceGenerators/QylAutoInstrumentationGenerator.cs", "tools/verify-source-interceptor-consumer.py")),
            new InstrumentationContractItem(13, "OTEL_DOTNET_AUTO_CONTRACT_013", InstrumentationContractKind.SignalSpecificInstrumentationPromise, "signals.traces.MONGODB", InstrumentationSignal.Traces, "MONGODB", "OTEL_DOTNET_AUTO_TRACES_MONGODB_INSTRUMENTATION_ENABLED", ">=2.7.0", ImmutableArray.Create("MongoDB.Driver.Core", "MongoDB.Driver"), ImmutableArray.Create("source", "bytecode"), "MongoDB.Driver needs bytecode instrumentation only for versions <3.7.0. Versions >=3.7.0 use only source instrumentation.", ImmutableArray<string>.Empty, InstrumentationContractLane.SourceInterceptor, QylContractStatus.Implemented, SourceVisibility.UserCode, PayloadAccess.NotApplicable, QylEvidenceLevel.CompileBindingOnly, "QylAutoInstrumentationGenerator", ImmutableArray.Create("src/Qyl.AutoInstrumentation.SourceGenerators/QylAutoInstrumentationGenerator.cs", "tools/verify-source-interceptor-consumer.py")),
            new InstrumentationContractItem(14, "OTEL_DOTNET_AUTO_CONTRACT_014", InstrumentationContractKind.SignalSpecificInstrumentationPromise, "signals.traces.MYSQLCONNECTOR", InstrumentationSignal.Traces, "MYSQLCONNECTOR", "OTEL_DOTNET_AUTO_TRACES_MYSQLCONNECTOR_INSTRUMENTATION_ENABLED", ">=2.0.0", ImmutableArray.Create("MySqlConnector"), ImmutableArray.Create("source"), "signals.traces.MYSQLCONNECTOR instrumentation promise.", ImmutableArray<string>.Empty, InstrumentationContractLane.SourceInterceptor, QylContractStatus.Implemented, SourceVisibility.UserCode, PayloadAccess.NotApplicable, QylEvidenceLevel.CompileBindingOnly, "QylAutoInstrumentationGenerator", ImmutableArray.Create("src/Qyl.AutoInstrumentation.SourceGenerators/QylAutoInstrumentationGenerator.cs", "tools/verify-source-interceptor-consumer.py")),
            new InstrumentationContractItem(15, "OTEL_DOTNET_AUTO_CONTRACT_015", InstrumentationContractKind.SignalSpecificInstrumentationPromise, "signals.traces.MYSQLDATA", InstrumentationSignal.Traces, "MYSQLDATA", "OTEL_DOTNET_AUTO_TRACES_MYSQLDATA_INSTRUMENTATION_ENABLED", ">=8.1.0", ImmutableArray.Create("MySql.Data"), ImmutableArray.Create("source"), "signals.traces.MYSQLDATA instrumentation promise.", ImmutableArray<string>.Empty, InstrumentationContractLane.SourceInterceptor, QylContractStatus.Implemented, SourceVisibility.UserCode, PayloadAccess.NotApplicable, QylEvidenceLevel.CompileBindingOnly, "QylAutoInstrumentationGenerator", ImmutableArray.Create("src/Qyl.AutoInstrumentation.SourceGenerators/QylAutoInstrumentationGenerator.cs", "tools/verify-source-interceptor-consumer.py")),
            new InstrumentationContractItem(16, "OTEL_DOTNET_AUTO_CONTRACT_016", InstrumentationContractKind.SignalSpecificInstrumentationPromise, "signals.traces.NPGSQL", InstrumentationSignal.Traces, "NPGSQL", "OTEL_DOTNET_AUTO_TRACES_NPGSQL_INSTRUMENTATION_ENABLED", ">=6.0.0", ImmutableArray.Create("Npgsql"), ImmutableArray.Create("source"), "signals.traces.NPGSQL instrumentation promise.", ImmutableArray<string>.Empty, InstrumentationContractLane.SourceInterceptor, QylContractStatus.Implemented, SourceVisibility.UserCode, PayloadAccess.NotApplicable, QylEvidenceLevel.CompileBindingOnly, "QylAutoInstrumentationGenerator", ImmutableArray.Create("src/Qyl.AutoInstrumentation.SourceGenerators/QylAutoInstrumentationGenerator.cs", "tools/verify-source-interceptor-consumer.py")),
            new InstrumentationContractItem(17, "OTEL_DOTNET_AUTO_CONTRACT_017", InstrumentationContractKind.SignalSpecificInstrumentationPromise, "signals.traces.NSERVICEBUS", InstrumentationSignal.Traces, "NSERVICEBUS", "OTEL_DOTNET_AUTO_TRACES_NSERVICEBUS_INSTRUMENTATION_ENABLED", ">=8.0.0 && <10.0.0", ImmutableArray.Create("NServiceBus"), ImmutableArray.Create("source", "bytecode"), "signals.traces.NSERVICEBUS instrumentation promise.", ImmutableArray<string>.Empty, InstrumentationContractLane.SourceInterceptor, QylContractStatus.Implemented, SourceVisibility.UserCode, PayloadAccess.NotApplicable, QylEvidenceLevel.CompileBindingOnly, "QylAutoInstrumentationGenerator", ImmutableArray.Create("src/Qyl.AutoInstrumentation.SourceGenerators/QylAutoInstrumentationGenerator.cs", "tools/verify-source-interceptor-consumer.py")),
            new InstrumentationContractItem(18, "OTEL_DOTNET_AUTO_CONTRACT_018", InstrumentationContractKind.SignalSpecificInstrumentationPromise, "signals.traces.ORACLEMDA", InstrumentationSignal.Traces, "ORACLEMDA", "OTEL_DOTNET_AUTO_TRACES_ORACLEMDA_INSTRUMENTATION_ENABLED", ">=23.4.0", ImmutableArray.Create("Oracle.ManagedDataAccess.Core", "Oracle.ManagedDataAccess"), ImmutableArray.Create("source"), "signals.traces.ORACLEMDA instrumentation promise.", ImmutableArray<string>.Empty, InstrumentationContractLane.SourceInterceptor, QylContractStatus.Implemented, SourceVisibility.UserCode, PayloadAccess.NotApplicable, QylEvidenceLevel.CompileBindingOnly, "QylAutoInstrumentationGenerator", ImmutableArray.Create("src/Qyl.AutoInstrumentation.SourceGenerators/QylAutoInstrumentationGenerator.cs", "tools/verify-source-interceptor-consumer.py")),
            new InstrumentationContractItem(19, "OTEL_DOTNET_AUTO_CONTRACT_019", InstrumentationContractKind.SignalSpecificInstrumentationPromise, "signals.traces.RABBITMQ", InstrumentationSignal.Traces, "RABBITMQ", "OTEL_DOTNET_AUTO_TRACES_RABBITMQ_INSTRUMENTATION_ENABLED", ">=5.0.0", ImmutableArray.Create("RabbitMQ.Client"), ImmutableArray.Create("source", "bytecode"), "RabbitMQ.Client needs bytecode instrumentation only for 5.* and 6.* versions. Versions >=7.0.0 use only source instrumentation.", ImmutableArray<string>.Empty, InstrumentationContractLane.SourceInterceptor, QylContractStatus.Implemented, SourceVisibility.UserCode, PayloadAccess.NotApplicable, QylEvidenceLevel.CompileBindingOnly, "QylAutoInstrumentationGenerator", ImmutableArray.Create("src/Qyl.AutoInstrumentation.SourceGenerators/QylAutoInstrumentationGenerator.cs", "tools/verify-source-interceptor-consumer.py")),
            new InstrumentationContractItem(20, "OTEL_DOTNET_AUTO_CONTRACT_020", InstrumentationContractKind.SignalSpecificInstrumentationPromise, "signals.traces.QUARTZ", InstrumentationSignal.Traces, "QUARTZ", "OTEL_DOTNET_AUTO_TRACES_QUARTZ_INSTRUMENTATION_ENABLED", ">=3.4.0", ImmutableArray.Create("Quartz"), ImmutableArray.Create("source"), "signals.traces.QUARTZ instrumentation promise.", ImmutableArray<string>.Empty, InstrumentationContractLane.SourceInterceptor, QylContractStatus.Implemented, SourceVisibility.UserCode, PayloadAccess.NotApplicable, QylEvidenceLevel.VerifiedManaged, "QylAutoInstrumentationGenerator", ImmutableArray.Create("src/Qyl.AutoInstrumentation.SourceGenerators/QylAutoInstrumentationGenerator.cs", "tools/verify-source-interceptor-consumer.py", "demos/Qyl.RealQuartzDemo", "tools/verify-real-quartz-demo.py")),
            new InstrumentationContractItem(21, "OTEL_DOTNET_AUTO_CONTRACT_021", InstrumentationContractKind.SignalSpecificInstrumentationPromise, "signals.traces.SQLCLIENT", InstrumentationSignal.Traces, "SQLCLIENT", "OTEL_DOTNET_AUTO_TRACES_SQLCLIENT_INSTRUMENTATION_ENABLED", "*", ImmutableArray.Create("Microsoft.Data.SqlClient", "System.Data.SqlClient", "System.Data"), ImmutableArray.Create("source"), "System.Data.SqlClient is deprecated. Microsoft.Data.SqlClient v3.* is not supported on .NET Framework due to an OpenTelemetry .NET issue. System.Data.SqlClient is supported from version 4.8.5.", ImmutableArray<string>.Empty, InstrumentationContractLane.SourceInterceptor, QylContractStatus.Implemented, SourceVisibility.UserCode, PayloadAccess.NotApplicable, QylEvidenceLevel.VerifiedNativeAot, "QylAutoInstrumentationGenerator", ImmutableArray.Create("src/Qyl.AutoInstrumentation.SourceGenerators/QylAutoInstrumentationGenerator.cs", "tools/verify-source-interceptor-consumer.py")),
            new InstrumentationContractItem(22, "OTEL_DOTNET_AUTO_CONTRACT_022", InstrumentationContractKind.SignalSpecificInstrumentationPromise, "signals.traces.SQLITE", InstrumentationSignal.Traces, "SQLITE", "OTEL_DOTNET_AUTO_TRACES_SQLITE_INSTRUMENTATION_ENABLED", ">=8.0.0 && <11.0.0", ImmutableArray.Create("Microsoft.Data.Sqlite"), ImmutableArray.Create("bytecode"), "signals.traces.SQLITE instrumentation promise.", ImmutableArray<string>.Empty, InstrumentationContractLane.SourceInterceptor, QylContractStatus.Implemented, SourceVisibility.UserCode, PayloadAccess.NotApplicable, QylEvidenceLevel.CompileBindingOnly, "QylAutoInstrumentationGenerator", ImmutableArray.Create("src/Qyl.AutoInstrumentation.SourceGenerators/QylAutoInstrumentationGenerator.cs", "tools/verify-source-interceptor-consumer.py")),
            new InstrumentationContractItem(23, "OTEL_DOTNET_AUTO_CONTRACT_023", InstrumentationContractKind.SignalSpecificInstrumentationPromise, "signals.traces.STACKEXCHANGEREDIS", InstrumentationSignal.Traces, "STACKEXCHANGEREDIS", "OTEL_DOTNET_AUTO_TRACES_STACKEXCHANGEREDIS_INSTRUMENTATION_ENABLED", ">=2.6.122 && <3.0.0", ImmutableArray.Create("StackExchange.Redis"), ImmutableArray.Create("source", "bytecode"), "signals.traces.STACKEXCHANGEREDIS instrumentation promise.", ImmutableArray<string>.Empty, InstrumentationContractLane.SourceInterceptor, QylContractStatus.Implemented, SourceVisibility.UserCode, PayloadAccess.NotApplicable, QylEvidenceLevel.CompileBindingOnly, "QylAutoInstrumentationGenerator", ImmutableArray.Create("src/Qyl.AutoInstrumentation.SourceGenerators/QylAutoInstrumentationGenerator.cs", "tools/verify-source-interceptor-consumer.py")),
            new InstrumentationContractItem(24, "OTEL_DOTNET_AUTO_CONTRACT_024", InstrumentationContractKind.SignalSpecificInstrumentationPromise, "signals.traces.WCFCLIENT", InstrumentationSignal.Traces, "WCFCLIENT", "OTEL_DOTNET_AUTO_TRACES_WCFCLIENT_INSTRUMENTATION_ENABLED", "*", ImmutableArray.Create("WCF"), ImmutableArray.Create("source", "bytecode"), "signals.traces.WCFCLIENT instrumentation promise.", ImmutableArray<string>.Empty, InstrumentationContractLane.SourceInterceptor, QylContractStatus.Implemented, SourceVisibility.UserCode, PayloadAccess.NotApplicable, QylEvidenceLevel.CompileBindingOnly, "QylAutoInstrumentationGenerator", ImmutableArray.Create("src/Qyl.AutoInstrumentation.SourceGenerators/QylAutoInstrumentationGenerator.cs", "tools/verify-source-interceptor-consumer.py")),
            new InstrumentationContractItem(25, "OTEL_DOTNET_AUTO_CONTRACT_025", InstrumentationContractKind.SignalSpecificInstrumentationPromise, "signals.traces.WCFCORE", InstrumentationSignal.Traces, "WCFCORE", "OTEL_DOTNET_AUTO_TRACES_WCFCORE_INSTRUMENTATION_ENABLED", ">=1.8.0", ImmutableArray.Create("CoreWCF.Primitives"), ImmutableArray.Create("source"), "signals.traces.WCFCORE instrumentation promise.", ImmutableArray<string>.Empty, InstrumentationContractLane.UnsupportedNativeAot, QylContractStatus.UnsupportedNativeAot, SourceVisibility.LibraryInternal, PayloadAccess.ReflectionRequired, QylEvidenceLevel.None, "unsupported by qyl NativeAOT substrate", ImmutableArray.Create("docs/coverage-matrix.md")),
            new InstrumentationContractItem(26, "OTEL_DOTNET_AUTO_CONTRACT_026", InstrumentationContractKind.SignalSpecificInstrumentationPromise, "signals.traces.WCFSERVICE", InstrumentationSignal.Traces, "WCFSERVICE", "OTEL_DOTNET_AUTO_TRACES_WCFSERVICE_INSTRUMENTATION_ENABLED", "*", ImmutableArray.Create("WCF"), ImmutableArray.Create("source", "bytecode"), "signals.traces.WCFSERVICE instrumentation promise.", ImmutableArray<string>.Empty, InstrumentationContractLane.UnsupportedNativeAot, QylContractStatus.UnsupportedNativeAot, SourceVisibility.LibraryInternal, PayloadAccess.ReflectionRequired, QylEvidenceLevel.None, "unsupported by qyl NativeAOT substrate", ImmutableArray.Create("docs/coverage-matrix.md")),
            new InstrumentationContractItem(27, "OTEL_DOTNET_AUTO_CONTRACT_027", InstrumentationContractKind.SignalSpecificInstrumentationPromise, "signals.metrics.ASPNET", InstrumentationSignal.Metrics, "ASPNET", "OTEL_DOTNET_AUTO_METRICS_ASPNET_INSTRUMENTATION_ENABLED", "*", ImmutableArray.Create("ASP.NET Framework"), ImmutableArray.Create("source", "bytecode"), "ASP.NET metrics are generated only if the AspNet trace instrumentation is also enabled.", ImmutableArray<string>.Empty, InstrumentationContractLane.UnsupportedNativeAot, QylContractStatus.UnsupportedNativeAot, SourceVisibility.UserCode, PayloadAccess.ReflectionRequired, QylEvidenceLevel.None, "unsupported by qyl NativeAOT substrate", ImmutableArray.Create("docs/coverage-matrix.md")),
            new InstrumentationContractItem(28, "OTEL_DOTNET_AUTO_CONTRACT_028", InstrumentationContractKind.SignalSpecificInstrumentationPromise, "signals.metrics.ASPNETCORE", InstrumentationSignal.Metrics, "ASPNETCORE", "OTEL_DOTNET_AUTO_METRICS_ASPNETCORE_INSTRUMENTATION_ENABLED", "*", ImmutableArray.Create("ASP.NET Core"), ImmutableArray.Create("source"), "ASP.NET Core metrics", ImmutableArray<string>.Empty, InstrumentationContractLane.RuntimePublicTelemetry, QylContractStatus.Implemented, SourceVisibility.LibraryInternal, PayloadAccess.TypedPublic, QylEvidenceLevel.CompileBindingOnly, "Qyl public telemetry listeners/meters", ImmutableArray.Create("src/Qyl.AutoInstrumentation.DiagnosticListeners", "src/Qyl.AutoInstrumentation/QylMetricMeters.cs", "tools/verify-otlp-collector-fixtures.py")),
            new InstrumentationContractItem(29, "OTEL_DOTNET_AUTO_CONTRACT_029", InstrumentationContractKind.SignalSpecificInstrumentationPromise, "signals.metrics.HTTPCLIENT", InstrumentationSignal.Metrics, "HTTPCLIENT", "OTEL_DOTNET_AUTO_METRICS_HTTPCLIENT_INSTRUMENTATION_ENABLED", "*", ImmutableArray.Create("System.Net.Http.HttpClient", "System.Net.HttpWebRequest"), ImmutableArray.Create("source"), "HttpClient metrics", ImmutableArray<string>.Empty, InstrumentationContractLane.RuntimePublicTelemetry, QylContractStatus.Implemented, SourceVisibility.Both, PayloadAccess.TypedPublic, QylEvidenceLevel.CompileBindingOnly, "Qyl public telemetry listeners/meters", ImmutableArray.Create("src/Qyl.AutoInstrumentation.DiagnosticListeners", "src/Qyl.AutoInstrumentation/QylMetricMeters.cs", "tools/verify-otlp-collector-fixtures.py")),
            new InstrumentationContractItem(30, "OTEL_DOTNET_AUTO_CONTRACT_030", InstrumentationContractKind.SignalSpecificInstrumentationPromise, "signals.metrics.NETRUNTIME", InstrumentationSignal.Metrics, "NETRUNTIME", "OTEL_DOTNET_AUTO_METRICS_NETRUNTIME_INSTRUMENTATION_ENABLED", "*", ImmutableArray.Create("OpenTelemetry.Instrumentation.Runtime"), ImmutableArray.Create("source"), "Runtime metrics", ImmutableArray<string>.Empty, InstrumentationContractLane.RuntimePublicTelemetry, QylContractStatus.Implemented, SourceVisibility.LibraryInternal, PayloadAccess.TypedPublic, QylEvidenceLevel.CompileBindingOnly, "Qyl public telemetry listeners/meters", ImmutableArray.Create("src/Qyl.AutoInstrumentation.DiagnosticListeners", "src/Qyl.AutoInstrumentation/QylMetricMeters.cs", "tools/verify-otlp-collector-fixtures.py")),
            new InstrumentationContractItem(31, "OTEL_DOTNET_AUTO_CONTRACT_031", InstrumentationContractKind.SignalSpecificInstrumentationPromise, "signals.metrics.NPGSQL", InstrumentationSignal.Metrics, "NPGSQL", "OTEL_DOTNET_AUTO_METRICS_NPGSQL_INSTRUMENTATION_ENABLED", ">=6.0.0", ImmutableArray.Create("Npgsql"), ImmutableArray.Create("source"), "Npgsql metrics", ImmutableArray<string>.Empty, InstrumentationContractLane.RuntimePublicTelemetry, QylContractStatus.Implemented, SourceVisibility.LibraryInternal, PayloadAccess.TypedPublic, QylEvidenceLevel.CompileBindingOnly, "Qyl public telemetry listeners/meters", ImmutableArray.Create("src/Qyl.AutoInstrumentation.DiagnosticListeners", "src/Qyl.AutoInstrumentation/QylMetricMeters.cs", "tools/verify-otlp-collector-fixtures.py")),
            new InstrumentationContractItem(32, "OTEL_DOTNET_AUTO_CONTRACT_032", InstrumentationContractKind.SignalSpecificInstrumentationPromise, "signals.metrics.NSERVICEBUS", InstrumentationSignal.Metrics, "NSERVICEBUS", "OTEL_DOTNET_AUTO_METRICS_NSERVICEBUS_INSTRUMENTATION_ENABLED", ">=8.0.0 && <10.0.0", ImmutableArray.Create("NServiceBus"), ImmutableArray.Create("source", "bytecode"), "NServiceBus metrics", ImmutableArray<string>.Empty, InstrumentationContractLane.RuntimePublicTelemetry, QylContractStatus.Implemented, SourceVisibility.LibraryInternal, PayloadAccess.TypedPublic, QylEvidenceLevel.CompileBindingOnly, "Qyl public telemetry listeners/meters", ImmutableArray.Create("src/Qyl.AutoInstrumentation.DiagnosticListeners", "src/Qyl.AutoInstrumentation/QylMetricMeters.cs", "tools/verify-otlp-collector-fixtures.py")),
            new InstrumentationContractItem(33, "OTEL_DOTNET_AUTO_CONTRACT_033", InstrumentationContractKind.SignalSpecificInstrumentationPromise, "signals.metrics.PROCESS", InstrumentationSignal.Metrics, "PROCESS", "OTEL_DOTNET_AUTO_METRICS_PROCESS_INSTRUMENTATION_ENABLED", "*", ImmutableArray.Create("OpenTelemetry.Instrumentation.Process"), ImmutableArray.Create("source"), "Process metrics", ImmutableArray<string>.Empty, InstrumentationContractLane.RuntimePublicTelemetry, QylContractStatus.Implemented, SourceVisibility.LibraryInternal, PayloadAccess.TypedPublic, QylEvidenceLevel.CompileBindingOnly, "Qyl public telemetry listeners/meters", ImmutableArray.Create("src/Qyl.AutoInstrumentation.DiagnosticListeners", "src/Qyl.AutoInstrumentation/QylMetricMeters.cs", "tools/verify-otlp-collector-fixtures.py")),
            new InstrumentationContractItem(34, "OTEL_DOTNET_AUTO_CONTRACT_034", InstrumentationContractKind.SignalSpecificInstrumentationPromise, "signals.metrics.SQLCLIENT", InstrumentationSignal.Metrics, "SQLCLIENT", "OTEL_DOTNET_AUTO_METRICS_SQLCLIENT_INSTRUMENTATION_ENABLED", "*", ImmutableArray.Create("Microsoft.Data.SqlClient", "System.Data.SqlClient", "System.Data"), ImmutableArray.Create("source"), "System.Data.SqlClient is deprecated. Microsoft.Data.SqlClient v3.* is not supported on .NET Framework due to an OpenTelemetry .NET issue. System.Data.SqlClient is supported from version 4.8.5.", ImmutableArray<string>.Empty, InstrumentationContractLane.RuntimePublicTelemetry, QylContractStatus.Implemented, SourceVisibility.LibraryInternal, PayloadAccess.TypedPublic, QylEvidenceLevel.CompileBindingOnly, "Qyl public telemetry listeners/meters", ImmutableArray.Create("src/Qyl.AutoInstrumentation.DiagnosticListeners", "src/Qyl.AutoInstrumentation/QylMetricMeters.cs", "tools/verify-otlp-collector-fixtures.py")),
            new InstrumentationContractItem(35, "OTEL_DOTNET_AUTO_CONTRACT_035", InstrumentationContractKind.SignalSpecificInstrumentationPromise, "signals.logs.ILOGGER", InstrumentationSignal.Logs, "ILOGGER", "OTEL_DOTNET_AUTO_LOGS_ILOGGER_INSTRUMENTATION_ENABLED", ">=8.0.0", ImmutableArray.Create("Microsoft.Extensions.Logging"), ImmutableArray.Create("bytecode", "source"), "For ASP.NET Core applications, LoggingBuilder instrumentation can be enabled without using the .NET CLR Profiler by setting ASPNETCORE_HOSTINGSTARTUPASSEMBLIES=OpenTelemetry.AutoInstrumentation.AspNetCoreBootstrapper.", ImmutableArray<string>.Empty, InstrumentationContractLane.SourceInterceptor, QylContractStatus.Implemented, SourceVisibility.UserCode, PayloadAccess.NotApplicable, QylEvidenceLevel.VerifiedNativeAot, "QylAutoInstrumentationGenerator", ImmutableArray.Create("src/Qyl.AutoInstrumentation.SourceGenerators/QylAutoInstrumentationGenerator.cs", "tools/verify-source-interceptor-consumer.py")),
            new InstrumentationContractItem(36, "OTEL_DOTNET_AUTO_CONTRACT_036", InstrumentationContractKind.SignalSpecificInstrumentationPromise, "signals.logs.LOG4NET", InstrumentationSignal.Logs, "LOG4NET", "OTEL_DOTNET_AUTO_LOGS_LOG4NET_INSTRUMENTATION_ENABLED", ">=2.0.13 && <4.0.0", ImmutableArray.Create("log4net"), ImmutableArray.Create("bytecode"), "Instrumentation provides both trace context injection and logs bridge.", ImmutableArray<string>.Empty, InstrumentationContractLane.SourceInterceptor, QylContractStatus.Implemented, SourceVisibility.UserCode, PayloadAccess.NotApplicable, QylEvidenceLevel.CompileBindingOnly, "QylAutoInstrumentationGenerator", ImmutableArray.Create("src/Qyl.AutoInstrumentation.SourceGenerators/QylAutoInstrumentationGenerator.cs", "tools/verify-source-interceptor-consumer.py")),
            new InstrumentationContractItem(37, "OTEL_DOTNET_AUTO_CONTRACT_037", InstrumentationContractKind.SignalSpecificInstrumentationPromise, "signals.logs.NLOG", InstrumentationSignal.Logs, "NLOG", "OTEL_DOTNET_AUTO_LOGS_NLOG_INSTRUMENTATION_ENABLED", ">=5.0.0 && <7.0.0", ImmutableArray.Create("NLog"), ImmutableArray.Create("bytecode"), "Instrumentation provides both trace context injection and logs bridge.", ImmutableArray<string>.Empty, InstrumentationContractLane.SourceInterceptor, QylContractStatus.Implemented, SourceVisibility.UserCode, PayloadAccess.NotApplicable, QylEvidenceLevel.CompileBindingOnly, "QylAutoInstrumentationGenerator", ImmutableArray.Create("src/Qyl.AutoInstrumentation.SourceGenerators/QylAutoInstrumentationGenerator.cs", "tools/verify-source-interceptor-consumer.py")),
            new InstrumentationContractItem(38, "OTEL_DOTNET_AUTO_CONTRACT_038", InstrumentationContractKind.GlobalEnvironmentControl, "global_environment_controls.OTEL_DOTNET_AUTO_INSTRUMENTATION_ENABLED", InstrumentationSignal.None, "", "OTEL_DOTNET_AUTO_INSTRUMENTATION_ENABLED", "", ImmutableArray<string>.Empty, ImmutableArray<string>.Empty, "Enables all instrumentations.", ImmutableArray<string>.Empty, InstrumentationContractLane.EnvironmentControl, QylContractStatus.ControlBound, SourceVisibility.NotApplicable, PayloadAccess.NotApplicable, QylEvidenceLevel.OptionBound, "QylAutoInstrumentationOptions", ImmutableArray.Create("src/Qyl.AutoInstrumentation/QylAutoInstrumentationOptions.cs", "tools/verify-contract-invariants.py")),
            new InstrumentationContractItem(39, "OTEL_DOTNET_AUTO_CONTRACT_039", InstrumentationContractKind.GlobalEnvironmentControl, "global_environment_controls.OTEL_DOTNET_AUTO_TRACES_INSTRUMENTATION_ENABLED", InstrumentationSignal.Traces, "", "OTEL_DOTNET_AUTO_TRACES_INSTRUMENTATION_ENABLED", "", ImmutableArray<string>.Empty, ImmutableArray<string>.Empty, "Enables all trace instrumentations. Overrides OTEL_DOTNET_AUTO_INSTRUMENTATION_ENABLED.", ImmutableArray<string>.Empty, InstrumentationContractLane.EnvironmentControl, QylContractStatus.ControlBound, SourceVisibility.NotApplicable, PayloadAccess.NotApplicable, QylEvidenceLevel.OptionBound, "QylAutoInstrumentationOptions", ImmutableArray.Create("src/Qyl.AutoInstrumentation/QylAutoInstrumentationOptions.cs", "tools/verify-contract-invariants.py")),
            new InstrumentationContractItem(40, "OTEL_DOTNET_AUTO_CONTRACT_040", InstrumentationContractKind.GlobalEnvironmentControl, "global_environment_controls.OTEL_DOTNET_AUTO_TRACES_{0}_INSTRUMENTATION_ENABLED", InstrumentationSignal.Traces, "", "OTEL_DOTNET_AUTO_TRACES_{0}_INSTRUMENTATION_ENABLED", "", ImmutableArray<string>.Empty, ImmutableArray<string>.Empty, "Configuration pattern for enabling a specific trace instrumentation, where {0} is the uppercase ID of the instrumentation. Overrides OTEL_DOTNET_AUTO_TRACES_INSTRUMENTATION_ENABLED.", ImmutableArray<string>.Empty, InstrumentationContractLane.EnvironmentControl, QylContractStatus.ControlBound, SourceVisibility.NotApplicable, PayloadAccess.NotApplicable, QylEvidenceLevel.OptionBound, "QylAutoInstrumentationOptions", ImmutableArray.Create("src/Qyl.AutoInstrumentation/QylAutoInstrumentationOptions.cs", "tools/verify-contract-invariants.py")),
            new InstrumentationContractItem(41, "OTEL_DOTNET_AUTO_CONTRACT_041", InstrumentationContractKind.GlobalEnvironmentControl, "global_environment_controls.OTEL_DOTNET_AUTO_METRICS_INSTRUMENTATION_ENABLED", InstrumentationSignal.Metrics, "", "OTEL_DOTNET_AUTO_METRICS_INSTRUMENTATION_ENABLED", "", ImmutableArray<string>.Empty, ImmutableArray<string>.Empty, "Disables all metric instrumentations. Overrides OTEL_DOTNET_AUTO_INSTRUMENTATION_ENABLED.", ImmutableArray<string>.Empty, InstrumentationContractLane.EnvironmentControl, QylContractStatus.ControlBound, SourceVisibility.NotApplicable, PayloadAccess.NotApplicable, QylEvidenceLevel.OptionBound, "QylAutoInstrumentationOptions", ImmutableArray.Create("src/Qyl.AutoInstrumentation/QylAutoInstrumentationOptions.cs", "tools/verify-contract-invariants.py")),
            new InstrumentationContractItem(42, "OTEL_DOTNET_AUTO_CONTRACT_042", InstrumentationContractKind.GlobalEnvironmentControl, "global_environment_controls.OTEL_DOTNET_AUTO_METRICS_{0}_INSTRUMENTATION_ENABLED", InstrumentationSignal.Metrics, "", "OTEL_DOTNET_AUTO_METRICS_{0}_INSTRUMENTATION_ENABLED", "", ImmutableArray<string>.Empty, ImmutableArray<string>.Empty, "Configuration pattern for enabling a specific metric instrumentation, where {0} is the uppercase ID of the instrumentation. Overrides OTEL_DOTNET_AUTO_METRICS_INSTRUMENTATION_ENABLED.", ImmutableArray<string>.Empty, InstrumentationContractLane.EnvironmentControl, QylContractStatus.ControlBound, SourceVisibility.NotApplicable, PayloadAccess.NotApplicable, QylEvidenceLevel.OptionBound, "QylAutoInstrumentationOptions", ImmutableArray.Create("src/Qyl.AutoInstrumentation/QylAutoInstrumentationOptions.cs", "tools/verify-contract-invariants.py")),
            new InstrumentationContractItem(43, "OTEL_DOTNET_AUTO_CONTRACT_043", InstrumentationContractKind.GlobalEnvironmentControl, "global_environment_controls.OTEL_DOTNET_AUTO_LOGS_INSTRUMENTATION_ENABLED", InstrumentationSignal.Logs, "", "OTEL_DOTNET_AUTO_LOGS_INSTRUMENTATION_ENABLED", "", ImmutableArray<string>.Empty, ImmutableArray<string>.Empty, "Disables all log instrumentations. Overrides OTEL_DOTNET_AUTO_INSTRUMENTATION_ENABLED.", ImmutableArray<string>.Empty, InstrumentationContractLane.EnvironmentControl, QylContractStatus.ControlBound, SourceVisibility.NotApplicable, PayloadAccess.NotApplicable, QylEvidenceLevel.OptionBound, "QylAutoInstrumentationOptions", ImmutableArray.Create("src/Qyl.AutoInstrumentation/QylAutoInstrumentationOptions.cs", "tools/verify-contract-invariants.py")),
            new InstrumentationContractItem(44, "OTEL_DOTNET_AUTO_CONTRACT_044", InstrumentationContractKind.GlobalEnvironmentControl, "global_environment_controls.OTEL_DOTNET_AUTO_LOGS_{0}_INSTRUMENTATION_ENABLED", InstrumentationSignal.Logs, "", "OTEL_DOTNET_AUTO_LOGS_{0}_INSTRUMENTATION_ENABLED", "", ImmutableArray<string>.Empty, ImmutableArray<string>.Empty, "Configuration pattern for enabling a specific log instrumentation, where {0} is the uppercase ID of the instrumentation. Overrides OTEL_DOTNET_AUTO_LOGS_INSTRUMENTATION_ENABLED.", ImmutableArray<string>.Empty, InstrumentationContractLane.EnvironmentControl, QylContractStatus.ControlBound, SourceVisibility.NotApplicable, PayloadAccess.NotApplicable, QylEvidenceLevel.OptionBound, "QylAutoInstrumentationOptions", ImmutableArray.Create("src/Qyl.AutoInstrumentation/QylAutoInstrumentationOptions.cs", "tools/verify-contract-invariants.py")),
            new InstrumentationContractItem(45, "OTEL_DOTNET_AUTO_CONTRACT_045", InstrumentationContractKind.InstrumentationOption, "instrumentation_options.OTEL_DOTNET_AUTO_ENTITYFRAMEWORKCORE_SET_DBSTATEMENT_FOR_TEXT", InstrumentationSignal.Traces, "ENTITYFRAMEWORKCORE", "OTEL_DOTNET_AUTO_ENTITYFRAMEWORKCORE_SET_DBSTATEMENT_FOR_TEXT", "", ImmutableArray<string>.Empty, ImmutableArray<string>.Empty, "Whether Entity Framework Core instrumentation can pass SQL statements through the db.statement attribute. Queries might contain sensitive information. If set to false, db.statement is recorded only for executing stored procedures.", ImmutableArray.Create("db.statement"), InstrumentationContractLane.InstrumentationOption, QylContractStatus.OptionBound, SourceVisibility.NotApplicable, PayloadAccess.NotApplicable, QylEvidenceLevel.OptionBound, "QylAutoInstrumentationOptions", ImmutableArray.Create("src/Qyl.AutoInstrumentation/QylAutoInstrumentationOptions.cs", "tools/verify-contract-invariants.py")),
            new InstrumentationContractItem(46, "OTEL_DOTNET_AUTO_CONTRACT_046", InstrumentationContractKind.InstrumentationOption, "instrumentation_options.OTEL_DOTNET_AUTO_GRAPHQL_SET_DOCUMENT", InstrumentationSignal.Traces, "GRAPHQL", "OTEL_DOTNET_AUTO_GRAPHQL_SET_DOCUMENT", "", ImmutableArray<string>.Empty, ImmutableArray<string>.Empty, "Whether GraphQL instrumentation can pass raw queries through the graphql.document attribute. Queries might contain sensitive information.", ImmutableArray.Create("graphql.document"), InstrumentationContractLane.InstrumentationOption, QylContractStatus.OptionBound, SourceVisibility.NotApplicable, PayloadAccess.NotApplicable, QylEvidenceLevel.OptionBound, "QylAutoInstrumentationOptions", ImmutableArray.Create("src/Qyl.AutoInstrumentation/QylAutoInstrumentationOptions.cs", "tools/verify-contract-invariants.py")),
            new InstrumentationContractItem(47, "OTEL_DOTNET_AUTO_CONTRACT_047", InstrumentationContractKind.InstrumentationOption, "instrumentation_options.OTEL_DOTNET_AUTO_ORACLEMDA_SET_DBSTATEMENT_FOR_TEXT", InstrumentationSignal.Traces, "ORACLEMDA", "OTEL_DOTNET_AUTO_ORACLEMDA_SET_DBSTATEMENT_FOR_TEXT", "", ImmutableArray<string>.Empty, ImmutableArray<string>.Empty, "Whether Oracle Client instrumentation can pass SQL statements through the db.statement attribute. Queries might contain sensitive information. If set to false, db.statement is recorded only for executing stored procedures.", ImmutableArray.Create("db.statement"), InstrumentationContractLane.InstrumentationOption, QylContractStatus.OptionBound, SourceVisibility.NotApplicable, PayloadAccess.NotApplicable, QylEvidenceLevel.OptionBound, "QylAutoInstrumentationOptions", ImmutableArray.Create("src/Qyl.AutoInstrumentation/QylAutoInstrumentationOptions.cs", "tools/verify-contract-invariants.py")),
            new InstrumentationContractItem(48, "OTEL_DOTNET_AUTO_CONTRACT_048", InstrumentationContractKind.InstrumentationOption, "instrumentation_options.OTEL_DOTNET_AUTO_SQLCLIENT_SET_DBSTATEMENT_FOR_TEXT", InstrumentationSignal.Traces, "SQLCLIENT", "OTEL_DOTNET_AUTO_SQLCLIENT_SET_DBSTATEMENT_FOR_TEXT", "", ImmutableArray<string>.Empty, ImmutableArray<string>.Empty, "Whether SQL Client instrumentation can pass SQL statements through the db.statement attribute. Queries might contain sensitive information. If set to false, db.statement is recorded only for executing stored procedures.", ImmutableArray.Create("db.statement"), InstrumentationContractLane.InstrumentationOption, QylContractStatus.OptionBound, SourceVisibility.NotApplicable, PayloadAccess.NotApplicable, QylEvidenceLevel.OptionBound, "QylAutoInstrumentationOptions", ImmutableArray.Create("src/Qyl.AutoInstrumentation/QylAutoInstrumentationOptions.cs", "tools/verify-contract-invariants.py")),
            new InstrumentationContractItem(49, "OTEL_DOTNET_AUTO_CONTRACT_049", InstrumentationContractKind.InstrumentationOption, "instrumentation_options.OTEL_DOTNET_AUTO_TRACES_ASPNET_INSTRUMENTATION_CAPTURE_REQUEST_HEADERS", InstrumentationSignal.Traces, "ASPNET", "OTEL_DOTNET_AUTO_TRACES_ASPNET_INSTRUMENTATION_CAPTURE_REQUEST_HEADERS", "", ImmutableArray<string>.Empty, ImmutableArray<string>.Empty, "Comma-separated list of HTTP header names. ASP.NET instrumentations capture HTTP request header values for all configured header names.", ImmutableArray.Create("http.request.header"), InstrumentationContractLane.InstrumentationOption, QylContractStatus.OptionBound, SourceVisibility.NotApplicable, PayloadAccess.NotApplicable, QylEvidenceLevel.OptionBound, "QylAutoInstrumentationOptions", ImmutableArray.Create("src/Qyl.AutoInstrumentation/QylAutoInstrumentationOptions.cs", "tools/verify-contract-invariants.py")),
            new InstrumentationContractItem(50, "OTEL_DOTNET_AUTO_CONTRACT_050", InstrumentationContractKind.InstrumentationOption, "instrumentation_options.OTEL_DOTNET_AUTO_TRACES_ASPNET_INSTRUMENTATION_CAPTURE_RESPONSE_HEADERS", InstrumentationSignal.Traces, "ASPNET", "OTEL_DOTNET_AUTO_TRACES_ASPNET_INSTRUMENTATION_CAPTURE_RESPONSE_HEADERS", "", ImmutableArray<string>.Empty, ImmutableArray<string>.Empty, "Comma-separated list of HTTP header names. ASP.NET instrumentations capture HTTP response header values for all configured header names.", ImmutableArray.Create("http.response.header"), InstrumentationContractLane.InstrumentationOption, QylContractStatus.OptionBound, SourceVisibility.NotApplicable, PayloadAccess.NotApplicable, QylEvidenceLevel.OptionBound, "QylAutoInstrumentationOptions", ImmutableArray.Create("src/Qyl.AutoInstrumentation/QylAutoInstrumentationOptions.cs", "tools/verify-contract-invariants.py")),
            new InstrumentationContractItem(51, "OTEL_DOTNET_AUTO_CONTRACT_051", InstrumentationContractKind.InstrumentationOption, "instrumentation_options.OTEL_DOTNET_AUTO_TRACES_ASPNETCORE_INSTRUMENTATION_CAPTURE_REQUEST_HEADERS", InstrumentationSignal.Traces, "ASPNETCORE", "OTEL_DOTNET_AUTO_TRACES_ASPNETCORE_INSTRUMENTATION_CAPTURE_REQUEST_HEADERS", "", ImmutableArray<string>.Empty, ImmutableArray<string>.Empty, "Comma-separated list of HTTP header names. ASP.NET Core instrumentations capture HTTP request header values for all configured header names.", ImmutableArray.Create("http.request.header"), InstrumentationContractLane.InstrumentationOption, QylContractStatus.OptionBound, SourceVisibility.NotApplicable, PayloadAccess.NotApplicable, QylEvidenceLevel.OptionBound, "QylAutoInstrumentationOptions", ImmutableArray.Create("src/Qyl.AutoInstrumentation/QylAutoInstrumentationOptions.cs", "tools/verify-contract-invariants.py")),
            new InstrumentationContractItem(52, "OTEL_DOTNET_AUTO_CONTRACT_052", InstrumentationContractKind.InstrumentationOption, "instrumentation_options.OTEL_DOTNET_AUTO_TRACES_ASPNETCORE_INSTRUMENTATION_CAPTURE_RESPONSE_HEADERS", InstrumentationSignal.Traces, "ASPNETCORE", "OTEL_DOTNET_AUTO_TRACES_ASPNETCORE_INSTRUMENTATION_CAPTURE_RESPONSE_HEADERS", "", ImmutableArray<string>.Empty, ImmutableArray<string>.Empty, "Comma-separated list of HTTP header names. ASP.NET Core instrumentations capture HTTP response header values for all configured header names.", ImmutableArray.Create("http.response.header"), InstrumentationContractLane.InstrumentationOption, QylContractStatus.OptionBound, SourceVisibility.NotApplicable, PayloadAccess.NotApplicable, QylEvidenceLevel.OptionBound, "QylAutoInstrumentationOptions", ImmutableArray.Create("src/Qyl.AutoInstrumentation/QylAutoInstrumentationOptions.cs", "tools/verify-contract-invariants.py")),
            new InstrumentationContractItem(53, "OTEL_DOTNET_AUTO_CONTRACT_053", InstrumentationContractKind.InstrumentationOption, "instrumentation_options.OTEL_DOTNET_AUTO_TRACES_GRPCNETCLIENT_INSTRUMENTATION_CAPTURE_REQUEST_METADATA", InstrumentationSignal.Traces, "GRPCNETCLIENT", "OTEL_DOTNET_AUTO_TRACES_GRPCNETCLIENT_INSTRUMENTATION_CAPTURE_REQUEST_METADATA", "", ImmutableArray<string>.Empty, ImmutableArray<string>.Empty, "Comma-separated list of gRPC metadata names. Grpc.Net.Client instrumentations capture gRPC request metadata values for all configured metadata names.", ImmutableArray.Create("grpc.request.metadata"), InstrumentationContractLane.InstrumentationOption, QylContractStatus.OptionBound, SourceVisibility.NotApplicable, PayloadAccess.NotApplicable, QylEvidenceLevel.OptionBound, "QylAutoInstrumentationOptions", ImmutableArray.Create("src/Qyl.AutoInstrumentation/QylAutoInstrumentationOptions.cs", "tools/verify-contract-invariants.py")),
            new InstrumentationContractItem(54, "OTEL_DOTNET_AUTO_CONTRACT_054", InstrumentationContractKind.InstrumentationOption, "instrumentation_options.OTEL_DOTNET_AUTO_TRACES_GRPCNETCLIENT_INSTRUMENTATION_CAPTURE_RESPONSE_METADATA", InstrumentationSignal.Traces, "GRPCNETCLIENT", "OTEL_DOTNET_AUTO_TRACES_GRPCNETCLIENT_INSTRUMENTATION_CAPTURE_RESPONSE_METADATA", "", ImmutableArray<string>.Empty, ImmutableArray<string>.Empty, "Comma-separated list of gRPC metadata names. Grpc.Net.Client instrumentations capture gRPC response metadata values for all configured metadata names.", ImmutableArray.Create("grpc.response.metadata"), InstrumentationContractLane.InstrumentationOption, QylContractStatus.OptionBound, SourceVisibility.NotApplicable, PayloadAccess.NotApplicable, QylEvidenceLevel.OptionBound, "QylAutoInstrumentationOptions", ImmutableArray.Create("src/Qyl.AutoInstrumentation/QylAutoInstrumentationOptions.cs", "tools/verify-contract-invariants.py")),
            new InstrumentationContractItem(55, "OTEL_DOTNET_AUTO_CONTRACT_055", InstrumentationContractKind.InstrumentationOption, "instrumentation_options.OTEL_DOTNET_AUTO_TRACES_HTTP_INSTRUMENTATION_CAPTURE_REQUEST_HEADERS", InstrumentationSignal.Traces, "HTTPCLIENT", "OTEL_DOTNET_AUTO_TRACES_HTTP_INSTRUMENTATION_CAPTURE_REQUEST_HEADERS", "", ImmutableArray<string>.Empty, ImmutableArray<string>.Empty, "Comma-separated list of HTTP header names. HTTP Client instrumentations capture HTTP request header values for all configured header names.", ImmutableArray.Create("http.request.header"), InstrumentationContractLane.InstrumentationOption, QylContractStatus.OptionBound, SourceVisibility.NotApplicable, PayloadAccess.NotApplicable, QylEvidenceLevel.OptionBound, "QylAutoInstrumentationOptions", ImmutableArray.Create("src/Qyl.AutoInstrumentation/QylAutoInstrumentationOptions.cs", "tools/verify-contract-invariants.py")),
            new InstrumentationContractItem(56, "OTEL_DOTNET_AUTO_CONTRACT_056", InstrumentationContractKind.InstrumentationOption, "instrumentation_options.OTEL_DOTNET_AUTO_TRACES_HTTP_INSTRUMENTATION_CAPTURE_RESPONSE_HEADERS", InstrumentationSignal.Traces, "HTTPCLIENT", "OTEL_DOTNET_AUTO_TRACES_HTTP_INSTRUMENTATION_CAPTURE_RESPONSE_HEADERS", "", ImmutableArray<string>.Empty, ImmutableArray<string>.Empty, "Comma-separated list of HTTP header names. HTTP Client instrumentations capture HTTP response header values for all configured header names.", ImmutableArray.Create("http.response.header"), InstrumentationContractLane.InstrumentationOption, QylContractStatus.OptionBound, SourceVisibility.NotApplicable, PayloadAccess.NotApplicable, QylEvidenceLevel.OptionBound, "QylAutoInstrumentationOptions", ImmutableArray.Create("src/Qyl.AutoInstrumentation/QylAutoInstrumentationOptions.cs", "tools/verify-contract-invariants.py")),
            new InstrumentationContractItem(57, "OTEL_DOTNET_AUTO_CONTRACT_057", InstrumentationContractKind.InstrumentationOption, "instrumentation_options.OTEL_DOTNET_EXPERIMENTAL_ASPNETCORE_DISABLE_URL_QUERY_REDACTION", InstrumentationSignal.Traces, "ASPNETCORE", "OTEL_DOTNET_EXPERIMENTAL_ASPNETCORE_DISABLE_URL_QUERY_REDACTION", "", ImmutableArray<string>.Empty, ImmutableArray<string>.Empty, "Whether ASP.NET Core instrumentation turns off redaction of the url.query attribute value.", ImmutableArray.Create("url.query"), InstrumentationContractLane.InstrumentationOption, QylContractStatus.OptionBound, SourceVisibility.NotApplicable, PayloadAccess.NotApplicable, QylEvidenceLevel.OptionBound, "QylAutoInstrumentationOptions", ImmutableArray.Create("src/Qyl.AutoInstrumentation/QylAutoInstrumentationOptions.cs", "tools/verify-contract-invariants.py")),
            new InstrumentationContractItem(58, "OTEL_DOTNET_AUTO_CONTRACT_058", InstrumentationContractKind.InstrumentationOption, "instrumentation_options.OTEL_DOTNET_EXPERIMENTAL_HTTPCLIENT_DISABLE_URL_QUERY_REDACTION", InstrumentationSignal.Traces, "HTTPCLIENT", "OTEL_DOTNET_EXPERIMENTAL_HTTPCLIENT_DISABLE_URL_QUERY_REDACTION", "", ImmutableArray<string>.Empty, ImmutableArray<string>.Empty, "Whether HTTP client instrumentation turns off redaction of the url.full attribute value.", ImmutableArray.Create("url.full"), InstrumentationContractLane.InstrumentationOption, QylContractStatus.OptionBound, SourceVisibility.NotApplicable, PayloadAccess.NotApplicable, QylEvidenceLevel.OptionBound, "QylAutoInstrumentationOptions", ImmutableArray.Create("src/Qyl.AutoInstrumentation/QylAutoInstrumentationOptions.cs", "tools/verify-contract-invariants.py")),
            new InstrumentationContractItem(59, "OTEL_DOTNET_AUTO_CONTRACT_059", InstrumentationContractKind.InstrumentationOption, "instrumentation_options.OTEL_DOTNET_EXPERIMENTAL_ASPNET_DISABLE_URL_QUERY_REDACTION", InstrumentationSignal.Traces, "ASPNET", "OTEL_DOTNET_EXPERIMENTAL_ASPNET_DISABLE_URL_QUERY_REDACTION", "", ImmutableArray<string>.Empty, ImmutableArray<string>.Empty, "Whether ASP.NET instrumentation turns off redaction of the url.query attribute value.", ImmutableArray.Create("url.query"), InstrumentationContractLane.InstrumentationOption, QylContractStatus.OptionBound, SourceVisibility.NotApplicable, PayloadAccess.NotApplicable, QylEvidenceLevel.OptionBound, "QylAutoInstrumentationOptions", ImmutableArray.Create("src/Qyl.AutoInstrumentation/QylAutoInstrumentationOptions.cs", "tools/verify-contract-invariants.py")),
            new InstrumentationContractItem(60, "OTEL_DOTNET_AUTO_CONTRACT_060", InstrumentationContractKind.InstrumentationOption, "instrumentation_options.OTEL_DOTNET_AUTO_SQLCLIENT_NETFX_ILREWRITE_ENABLED", InstrumentationSignal.Traces, "SQLCLIENT", "OTEL_DOTNET_AUTO_SQLCLIENT_NETFX_ILREWRITE_ENABLED", "", ImmutableArray<string>.Empty, ImmutableArray<string>.Empty, "Enables IL rewriting of SqlCommand on .NET Framework to ensure CommandText is present for SqlClient instrumentation, which is required for db.query.text and db.query.summary to be populated. Previously, CommandText was only available for stored procedures. With this setting enabled, it is also available for raw queries. This changes the behavior of events emitted by SqlEventSource, which might impact other parts of the application if this mechanism is used.", ImmutableArray.Create("db.query.text", "db.query.summary"), InstrumentationContractLane.InstrumentationOption, QylContractStatus.OptionBound, SourceVisibility.NotApplicable, PayloadAccess.NotApplicable, QylEvidenceLevel.OptionBound, "QylAutoInstrumentationOptions", ImmutableArray.Create("src/Qyl.AutoInstrumentation/QylAutoInstrumentationOptions.cs", "tools/verify-contract-invariants.py"))
        );

    public static string EmitGeneratedManifestSource()
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("namespace Qyl.AutoInstrumentation.Generated;");
        builder.AppendLine();
        builder.AppendLine("internal static class QylGeneratedInstrumentationContract");
        builder.AppendLine("{");
        builder.AppendLine($"    public const int SignalSpecificInstrumentationPromiseCount = {SignalSpecificInstrumentationPromiseCount};");
        builder.AppendLine($"    public const int GlobalEnvironmentControlCount = {GlobalEnvironmentControlCount};");
        builder.AppendLine($"    public const int InstrumentationOptionCount = {InstrumentationOptionCount};");
        builder.AppendLine($"    public const int TotalCount = {TotalCount};");
        builder.AppendLine($"    public const int TracesSignalSpecificPromiseCount = {TracesSignalSpecificPromiseCount};");
        builder.AppendLine($"    public const int MetricsSignalSpecificPromiseCount = {MetricsSignalSpecificPromiseCount};");
        builder.AppendLine($"    public const int LogsSignalSpecificPromiseCount = {LogsSignalSpecificPromiseCount};");
        builder.AppendLine($"    public const int UniqueInstrumentationIdCount = {UniqueInstrumentationIdCount};");
        builder.AppendLine($"    public const int ImplementedSignalPromiseCount = {ImplementedSignalPromiseCount};");
        builder.AppendLine($"    public const int SourceInterceptorSignalPromiseCount = {SourceInterceptorSignalPromiseCount};");
        builder.AppendLine($"    public const int RuntimePublicTelemetrySignalPromiseCount = {RuntimePublicTelemetrySignalPromiseCount};");
        builder.AppendLine($"    public const int UnsupportedNativeAotSignalPromiseCount = {UnsupportedNativeAotSignalPromiseCount};");
        builder.AppendLine("    public const string AspNetCoreComponentsMeterName = \"Microsoft.AspNetCore.Components\";");
        builder.AppendLine("    public const string AspNetCoreComponentsNavigationMetricName = \"aspnetcore.components.navigation\";");
        builder.AppendLine();
        EmitStringArray(builder, "ItemIds", Items.Select(static item => item.Key));
        EmitStringArray(builder, "SignalKeys", Items.Where(static item => item.Kind is InstrumentationContractKind.SignalSpecificInstrumentationPromise).Select(static item => item.Key));
        EmitStringArray(builder, "ImplementedSignalKeys", ImplementedSignalKeys);
        EmitStringArray(builder, "SourceInterceptorSignalKeys", SourceInterceptorSignalKeys);
        EmitStringArray(builder, "RuntimePublicTelemetrySignalKeys", RuntimePublicTelemetrySignalKeys);
        EmitStringArray(builder, "UnsupportedNativeAotSignalKeys", UnsupportedNativeAotSignalKeys);
        EmitStringArray(builder, "GlobalEnvironmentControls", Items.Where(static item => item.Kind is InstrumentationContractKind.GlobalEnvironmentControl).Select(static item => item.EnvironmentVariable));
        EmitStringArray(builder, "InstrumentationOptions", Items.Where(static item => item.Kind is InstrumentationContractKind.InstrumentationOption).Select(static item => item.EnvironmentVariable));
        builder.AppendLine("}");
        return builder.ToString();
    }

    public static InstrumentationContractItem? TryGetImplementedSignal(string key)
        => TryGetSignal(key, static item => item.QylStatus is QylContractStatus.Implemented);

    public static InstrumentationContractItem? TryGetSourceInterceptorSignal(string key)
        => TryGetSignal(key, static item => item is { QylStatus: QylContractStatus.Implemented, Lane: InstrumentationContractLane.SourceInterceptor });

    public static InstrumentationContractItem? TryGetSupportedSignal(string key)
        => TryGetSignal(key, static _ => true);

    private static InstrumentationContractItem? TryGetSignal(string key, Func<InstrumentationContractItem, bool> predicate)
    {
        foreach (var item in Items)
        {
            if (item.Kind is InstrumentationContractKind.SignalSpecificInstrumentationPromise &&
                predicate(item) &&
                string.Equals(item.Key, key, StringComparison.Ordinal))
            {
                return item;
            }
        }

        return null;
    }

    private static void EmitStringArray(StringBuilder builder, string name, IEnumerable<string> values)
    {
        builder.Append("    public static string[] ");
        builder.Append(name);
        builder.AppendLine(" => new[]");
        builder.AppendLine("    {");

        foreach (var value in values)
        {
            builder.Append("        \"");
            builder.Append(value.Replace("\\", "\\\\").Replace("\"", "\\\""));
            builder.AppendLine("\",");
        }

        builder.AppendLine("    };");
        builder.AppendLine();
    }
}
