using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Qyl.AutoInstrumentation.SourceGenerators;

[Generator(LanguageNames.CSharp)]
public sealed class QylAutoInstrumentationGenerator : IIncrementalGenerator
{
    private static readonly SymbolDisplayFormat FullyQualifiedFormat =
        SymbolDisplayFormat.FullyQualifiedFormat;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static output =>
        {
            output.AddSource(
                "QylGeneratedInstrumentationContract.g.cs",
                SourceText.From(InstrumentationContract.EmitGeneratedManifestSource(), Encoding.UTF8));
        });

        var interceptedInvocations = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is InvocationExpressionSyntax,
                static (syntaxContext, cancellationToken) => TryCreateInterceptedInvocation(syntaxContext, cancellationToken))
            .Where(static invocation => invocation is not null)
            .Collect();

        context.RegisterSourceOutput(interceptedInvocations, static (sourceContext, invocations) =>
        {
            EmitInterceptors(sourceContext, invocations);
        });
    }

    private static InterceptedInvocation? TryCreateInterceptedInvocation(
        GeneratorSyntaxContext context,
        CancellationToken cancellationToken)
    {
        var invocation = (InvocationExpressionSyntax)context.Node;
        if (string.Equals(context.SemanticModel.Compilation.AssemblyName, "Qyl.AutoInstrumentation", StringComparison.Ordinal))
            return null;

        if (context.SemanticModel.GetSymbolInfo(invocation, cancellationToken).Symbol is not IMethodSymbol symbol)
            return null;

        if (!TryGetHttpClientInvocation(symbol, out var method, out var shape, out var contractId))
            return null;

        if (InstrumentationContract.TryGetSupportedSignal(contractId) is null)
            return null;

        var interceptableLocation = context.SemanticModel.GetInterceptableLocation(invocation, cancellationToken);
        if (interceptableLocation is null)
            return null;

        return new InterceptedInvocation(contractId, method, shape, interceptableLocation);
    }

    private static void EmitInterceptors(
        SourceProductionContext context,
        ImmutableArray<InterceptedInvocation?> nullableInvocations)
    {
        if (nullableInvocations.IsDefaultOrEmpty)
            return;

        var invocations = nullableInvocations
            .Where(static invocation => invocation is not null)
            .Select(static invocation => invocation!.Value)
            .Distinct()
            .ToArray();

        if (invocations.Length is 0)
            return;

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("namespace System.Runtime.CompilerServices");
        builder.AppendLine("{");
        builder.AppendLine("    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]");
        builder.AppendLine("    internal sealed class InterceptsLocationAttribute : global::System.Attribute");
        builder.AppendLine("    {");
        builder.AppendLine("        public InterceptsLocationAttribute(int version, string data) { }");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("namespace Qyl.AutoInstrumentation.Generated");
        builder.AppendLine("{");
        builder.AppendLine("    internal static class QylHttpClientInterceptors");
        builder.AppendLine("    {");

        for (var index = 0; index < invocations.Length; index++)
            EmitHttpClientInterceptor(builder, invocations[index], index);

        builder.AppendLine("    }");
        builder.AppendLine("}");

        context.AddSource("QylAutoInstrumentation.HttpClient.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
    }

    private static void EmitHttpClientInterceptor(
        StringBuilder builder,
        InterceptedInvocation invocation,
        int index)
    {
        var attribute = Microsoft.CodeAnalysis.CSharp.CSharpExtensions.GetInterceptsLocationAttributeSyntax(invocation.Location);

        builder.Append("        ");
        builder.AppendLine(attribute);

        switch (invocation.Shape)
        {
            case HttpClientParameterShape.SendRequest:
                builder.AppendLine($"        public static global::System.Threading.Tasks.Task<global::System.Net.Http.HttpResponseMessage> {invocation.Method}_{index}(this global::System.Net.Http.HttpClient client, global::System.Net.Http.HttpRequestMessage request)");
                builder.AppendLine("            => global::Qyl.AutoInstrumentation.QylInterceptedHttpClient.SendAsync(client, request);");
                break;

            case HttpClientParameterShape.SendRequestCancellationToken:
                builder.AppendLine($"        public static global::System.Threading.Tasks.Task<global::System.Net.Http.HttpResponseMessage> {invocation.Method}_{index}(this global::System.Net.Http.HttpClient client, global::System.Net.Http.HttpRequestMessage request, global::System.Threading.CancellationToken cancellationToken)");
                builder.AppendLine("            => global::Qyl.AutoInstrumentation.QylInterceptedHttpClient.SendAsync(client, request, cancellationToken);");
                break;

            case HttpClientParameterShape.SendRequestCompletionOption:
                builder.AppendLine($"        public static global::System.Threading.Tasks.Task<global::System.Net.Http.HttpResponseMessage> {invocation.Method}_{index}(this global::System.Net.Http.HttpClient client, global::System.Net.Http.HttpRequestMessage request, global::System.Net.Http.HttpCompletionOption completionOption)");
                builder.AppendLine("            => global::Qyl.AutoInstrumentation.QylInterceptedHttpClient.SendAsync(client, request, completionOption);");
                break;

            case HttpClientParameterShape.SendRequestCompletionOptionCancellationToken:
                builder.AppendLine($"        public static global::System.Threading.Tasks.Task<global::System.Net.Http.HttpResponseMessage> {invocation.Method}_{index}(this global::System.Net.Http.HttpClient client, global::System.Net.Http.HttpRequestMessage request, global::System.Net.Http.HttpCompletionOption completionOption, global::System.Threading.CancellationToken cancellationToken)");
                builder.AppendLine("            => global::Qyl.AutoInstrumentation.QylInterceptedHttpClient.SendAsync(client, request, completionOption, cancellationToken);");
                break;

            case HttpClientParameterShape.RequestUriString:
                builder.AppendLine($"        public static global::System.Threading.Tasks.Task<global::System.Net.Http.HttpResponseMessage> {invocation.Method}_{index}(this global::System.Net.Http.HttpClient client, string? requestUri)");
                builder.AppendLine($"            => global::Qyl.AutoInstrumentation.QylInterceptedHttpClient.{invocation.Method}(client, requestUri);");
                break;

            case HttpClientParameterShape.RequestUriUri:
                builder.AppendLine($"        public static global::System.Threading.Tasks.Task<global::System.Net.Http.HttpResponseMessage> {invocation.Method}_{index}(this global::System.Net.Http.HttpClient client, global::System.Uri? requestUri)");
                builder.AppendLine($"            => global::Qyl.AutoInstrumentation.QylInterceptedHttpClient.{invocation.Method}(client, requestUri);");
                break;

            case HttpClientParameterShape.RequestUriStringCancellationToken:
                builder.AppendLine($"        public static global::System.Threading.Tasks.Task<global::System.Net.Http.HttpResponseMessage> {invocation.Method}_{index}(this global::System.Net.Http.HttpClient client, string? requestUri, global::System.Threading.CancellationToken cancellationToken)");
                builder.AppendLine($"            => global::Qyl.AutoInstrumentation.QylInterceptedHttpClient.{invocation.Method}(client, requestUri, cancellationToken);");
                break;

            case HttpClientParameterShape.RequestUriUriCancellationToken:
                builder.AppendLine($"        public static global::System.Threading.Tasks.Task<global::System.Net.Http.HttpResponseMessage> {invocation.Method}_{index}(this global::System.Net.Http.HttpClient client, global::System.Uri? requestUri, global::System.Threading.CancellationToken cancellationToken)");
                builder.AppendLine($"            => global::Qyl.AutoInstrumentation.QylInterceptedHttpClient.{invocation.Method}(client, requestUri, cancellationToken);");
                break;

            case HttpClientParameterShape.RequestUriStringCompletionOption:
                builder.AppendLine($"        public static global::System.Threading.Tasks.Task<global::System.Net.Http.HttpResponseMessage> {invocation.Method}_{index}(this global::System.Net.Http.HttpClient client, string? requestUri, global::System.Net.Http.HttpCompletionOption completionOption)");
                builder.AppendLine($"            => global::Qyl.AutoInstrumentation.QylInterceptedHttpClient.{invocation.Method}(client, requestUri, completionOption);");
                break;

            case HttpClientParameterShape.RequestUriUriCompletionOption:
                builder.AppendLine($"        public static global::System.Threading.Tasks.Task<global::System.Net.Http.HttpResponseMessage> {invocation.Method}_{index}(this global::System.Net.Http.HttpClient client, global::System.Uri? requestUri, global::System.Net.Http.HttpCompletionOption completionOption)");
                builder.AppendLine($"            => global::Qyl.AutoInstrumentation.QylInterceptedHttpClient.{invocation.Method}(client, requestUri, completionOption);");
                break;

            case HttpClientParameterShape.RequestUriStringCompletionOptionCancellationToken:
                builder.AppendLine($"        public static global::System.Threading.Tasks.Task<global::System.Net.Http.HttpResponseMessage> {invocation.Method}_{index}(this global::System.Net.Http.HttpClient client, string? requestUri, global::System.Net.Http.HttpCompletionOption completionOption, global::System.Threading.CancellationToken cancellationToken)");
                builder.AppendLine($"            => global::Qyl.AutoInstrumentation.QylInterceptedHttpClient.{invocation.Method}(client, requestUri, completionOption, cancellationToken);");
                break;

            case HttpClientParameterShape.RequestUriUriCompletionOptionCancellationToken:
                builder.AppendLine($"        public static global::System.Threading.Tasks.Task<global::System.Net.Http.HttpResponseMessage> {invocation.Method}_{index}(this global::System.Net.Http.HttpClient client, global::System.Uri? requestUri, global::System.Net.Http.HttpCompletionOption completionOption, global::System.Threading.CancellationToken cancellationToken)");
                builder.AppendLine($"            => global::Qyl.AutoInstrumentation.QylInterceptedHttpClient.{invocation.Method}(client, requestUri, completionOption, cancellationToken);");
                break;
        }

        builder.AppendLine();
    }

    private static bool TryGetHttpClientInvocation(
        IMethodSymbol symbol,
        out HttpClientMethod method,
        out HttpClientParameterShape shape,
        out string contractId)
    {
        method = default;
        shape = default;
        contractId = string.Empty;

        if (!IsType(symbol.ContainingType, "global::System.Net.Http.HttpClient") ||
            !IsType(symbol.ReturnType, "global::System.Threading.Tasks.Task<global::System.Net.Http.HttpResponseMessage>"))
        {
            return false;
        }

        if (string.Equals(symbol.Name, "SendAsync", StringComparison.Ordinal) &&
            TryGetSendAsyncShape(symbol, out shape))
        {
            method = HttpClientMethod.SendAsync;
            contractId = "http.client.send_async";
            return true;
        }

        if (string.Equals(symbol.Name, "GetAsync", StringComparison.Ordinal) &&
            TryGetRequestUriShape(symbol, allowCompletionOption: true, out shape))
        {
            method = HttpClientMethod.GetAsync;
            contractId = "http.client.get_async";
            return true;
        }

        if (string.Equals(symbol.Name, "DeleteAsync", StringComparison.Ordinal) &&
            TryGetRequestUriShape(symbol, allowCompletionOption: false, out shape))
        {
            method = HttpClientMethod.DeleteAsync;
            contractId = "http.client.delete_async";
            return true;
        }

        return false;
    }

    private static bool TryGetSendAsyncShape(IMethodSymbol symbol, out HttpClientParameterShape shape)
    {
        shape = default;
        if (symbol.Parameters.Length is < 1 or > 3 ||
            !IsType(symbol.Parameters[0].Type, "global::System.Net.Http.HttpRequestMessage"))
        {
            return false;
        }

        if (symbol.Parameters.Length is 1)
        {
            shape = HttpClientParameterShape.SendRequest;
            return true;
        }

        if (symbol.Parameters.Length is 2)
        {
            if (IsType(symbol.Parameters[1].Type, "global::System.Threading.CancellationToken"))
            {
                shape = HttpClientParameterShape.SendRequestCancellationToken;
                return true;
            }

            if (IsType(symbol.Parameters[1].Type, "global::System.Net.Http.HttpCompletionOption"))
            {
                shape = HttpClientParameterShape.SendRequestCompletionOption;
                return true;
            }
        }

        if (symbol.Parameters.Length is 3 &&
            IsType(symbol.Parameters[1].Type, "global::System.Net.Http.HttpCompletionOption") &&
            IsType(symbol.Parameters[2].Type, "global::System.Threading.CancellationToken"))
        {
            shape = HttpClientParameterShape.SendRequestCompletionOptionCancellationToken;
            return true;
        }

        return false;
    }

    private static bool TryGetRequestUriShape(
        IMethodSymbol symbol,
        bool allowCompletionOption,
        out HttpClientParameterShape shape)
    {
        shape = default;
        if (symbol.Parameters.Length is < 1 or > 3)
            return false;

        var firstIsString = IsType(symbol.Parameters[0].Type, "global::System.String");
        var firstIsUri = IsType(symbol.Parameters[0].Type, "global::System.Uri");
        if (!firstIsString && !firstIsUri)
            return false;

        if (symbol.Parameters.Length is 1)
        {
            shape = firstIsString ? HttpClientParameterShape.RequestUriString : HttpClientParameterShape.RequestUriUri;
            return true;
        }

        if (symbol.Parameters.Length is 2)
        {
            if (IsType(symbol.Parameters[1].Type, "global::System.Threading.CancellationToken"))
            {
                shape = firstIsString ? HttpClientParameterShape.RequestUriStringCancellationToken : HttpClientParameterShape.RequestUriUriCancellationToken;
                return true;
            }

            if (allowCompletionOption && IsType(symbol.Parameters[1].Type, "global::System.Net.Http.HttpCompletionOption"))
            {
                shape = firstIsString ? HttpClientParameterShape.RequestUriStringCompletionOption : HttpClientParameterShape.RequestUriUriCompletionOption;
                return true;
            }
        }

        if (allowCompletionOption &&
            symbol.Parameters.Length is 3 &&
            IsType(symbol.Parameters[1].Type, "global::System.Net.Http.HttpCompletionOption") &&
            IsType(symbol.Parameters[2].Type, "global::System.Threading.CancellationToken"))
        {
            shape = firstIsString ? HttpClientParameterShape.RequestUriStringCompletionOptionCancellationToken : HttpClientParameterShape.RequestUriUriCompletionOptionCancellationToken;
            return true;
        }

        return false;
    }

    private static bool IsType(ITypeSymbol? symbol, string fullyQualifiedMetadataName)
        => symbol?.ToDisplayString(FullyQualifiedFormat) == fullyQualifiedMetadataName;

    private enum HttpClientMethod
    {
        SendAsync,
        GetAsync,
        DeleteAsync,
    }

    private enum HttpClientParameterShape
    {
        SendRequest,
        SendRequestCancellationToken,
        SendRequestCompletionOption,
        SendRequestCompletionOptionCancellationToken,
        RequestUriString,
        RequestUriUri,
        RequestUriStringCancellationToken,
        RequestUriUriCancellationToken,
        RequestUriStringCompletionOption,
        RequestUriUriCompletionOption,
        RequestUriStringCompletionOptionCancellationToken,
        RequestUriUriCompletionOptionCancellationToken,
    }

    private readonly record struct InterceptedInvocation(
        string ContractId,
        HttpClientMethod Method,
        HttpClientParameterShape Shape,
        InterceptableLocation Location);
}
