using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Qyl.AutoInstrumentation.SourceGenerators;

[Generator(LanguageNames.CSharp)]
public sealed class QylAutoInstrumentationGenerator : IIncrementalGenerator
{
    private static readonly SymbolDisplayFormat FullyQualifiedFormat =
        SymbolDisplayFormat.FullyQualifiedFormat;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static output =>
        {
            output.AddSource(
                "QylGeneratedInstrumentationContract.g.cs",
                SourceText.From(InstrumentationContract.EmitGeneratedManifestSource(), Encoding.UTF8));
        });

        var interceptedInvocations = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is InvocationExpressionSyntax,
                static (syntaxContext, cancellationToken) => TryCreateInterceptedInvocation(syntaxContext, cancellationToken))
            .Where(static invocation => invocation is not null)
            .Collect();

        context.RegisterSourceOutput(interceptedInvocations, static (sourceContext, invocations) =>
        {
            EmitInterceptors(sourceContext, invocations);
        });
    }

    private static InterceptedInvocation? TryCreateInterceptedInvocation(
        GeneratorSyntaxContext context,
        CancellationToken cancellationToken)
    {
        var invocation = (InvocationExpressionSyntax)context.Node;
        if (string.Equals(context.SemanticModel.Compilation.AssemblyName, "Qyl.AutoInstrumentation", StringComparison.Ordinal))
            return null;

        if (context.SemanticModel.GetSymbolInfo(invocation, cancellationToken).Symbol is not IMethodSymbol symbol)
            return null;

        if (!TryGetHttpClientSendAsyncOverload(symbol, out var overload))
            return null;

        var contract = InstrumentationContract.TryGetSupportedSignal("http.client.send_async");
        if (contract is null)
            return null;

        var interceptableLocation = context.SemanticModel.GetInterceptableLocation(invocation, cancellationToken);
        if (interceptableLocation is null)
            return null;

        return new InterceptedInvocation(contract.Value.Id, overload, interceptableLocation);
    }

    private static void EmitInterceptors(
        SourceProductionContext context,
        ImmutableArray<InterceptedInvocation?> nullableInvocations)
    {
        if (nullableInvocations.IsDefaultOrEmpty)
            return;

        var invocations = nullableInvocations
            .Where(static invocation => invocation is not null)
            .Select(static invocation => invocation!.Value)
            .Distinct()
            .ToArray();

        if (invocations.Length is 0)
            return;

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("namespace System.Runtime.CompilerServices");
        builder.AppendLine("{");
        builder.AppendLine("    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]");
        builder.AppendLine("    internal sealed class InterceptsLocationAttribute : global::System.Attribute");
        builder.AppendLine("    {");
        builder.AppendLine("        public InterceptsLocationAttribute(int version, string data) { }");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("namespace Qyl.AutoInstrumentation.Generated");
        builder.AppendLine("{");
        builder.AppendLine("    internal static class QylHttpClientSendAsyncInterceptors");
        builder.AppendLine("    {");

        for (var index = 0; index < invocations.Length; index++)
            EmitHttpClientSendAsyncInterceptor(builder, invocations[index], index);

        builder.AppendLine("    }");
        builder.AppendLine("}");

        context.AddSource("QylAutoInstrumentation.HttpClientSendAsync.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
    }

    private static void EmitHttpClientSendAsyncInterceptor(
        StringBuilder builder,
        InterceptedInvocation invocation,
        int index)
    {
        var attribute = Microsoft.CodeAnalysis.CSharp.CSharpExtensions
            .GetInterceptsLocationAttributeSyntax(invocation.Location);

        builder.Append("        ");
        builder.AppendLine(attribute);

        switch (invocation.Overload)
        {
            case HttpClientSendAsyncOverload.Request:
                builder.AppendLine($"        public static global::System.Threading.Tasks.Task<global::System.Net.Http.HttpResponseMessage> SendAsync_{index}(this global::System.Net.Http.HttpClient client, global::System.Net.Http.HttpRequestMessage request)");
                builder.AppendLine("            => global::Qyl.AutoInstrumentation.QylInterceptedHttpClient.SendAsync(client, request);");
                break;

            case HttpClientSendAsyncOverload.RequestCancellationToken:
                builder.AppendLine($"        public static global::System.Threading.Tasks.Task<global::System.Net.Http.HttpResponseMessage> SendAsync_{index}(this global::System.Net.Http.HttpClient client, global::System.Net.Http.HttpRequestMessage request, global::System.Threading.CancellationToken cancellationToken)");
                builder.AppendLine("            => global::Qyl.AutoInstrumentation.QylInterceptedHttpClient.SendAsync(client, request, cancellationToken);");
                break;

            case HttpClientSendAsyncOverload.RequestCompletionOption:
                builder.AppendLine($"        public static global::System.Threading.Tasks.Task<global::System.Net.Http.HttpResponseMessage> SendAsync_{index}(this global::System.Net.Http.HttpClient client, global::System.Net.Http.HttpRequestMessage request, global::System.Net.Http.HttpCompletionOption completionOption)");
                builder.AppendLine("            => global::Qyl.AutoInstrumentation.QylInterceptedHttpClient.SendAsync(client, request, completionOption);");
                break;

            case HttpClientSendAsyncOverload.RequestCompletionOptionCancellationToken:
                builder.AppendLine($"        public static global::System.Threading.Tasks.Task<global::System.Net.Http.HttpResponseMessage> SendAsync_{index}(this global::System.Net.Http.HttpClient client, global::System.Net.Http.HttpRequestMessage request, global::System.Net.Http.HttpCompletionOption completionOption, global::System.Threading.CancellationToken cancellationToken)");
                builder.AppendLine("            => global::Qyl.AutoInstrumentation.QylInterceptedHttpClient.SendAsync(client, request, completionOption, cancellationToken);");
                break;
        }

        builder.AppendLine();
    }

    private static bool TryGetHttpClientSendAsyncOverload(
        IMethodSymbol symbol,
        out HttpClientSendAsyncOverload overload)
    {
        overload = default;

        if (!string.Equals(symbol.Name, "SendAsync", StringComparison.Ordinal) ||
            !IsType(symbol.ContainingType, "global::System.Net.Http.HttpClient") ||
            !IsType(symbol.ReturnType, "global::System.Threading.Tasks.Task<global::System.Net.Http.HttpResponseMessage>") ||
            symbol.Parameters.Length is < 1 or > 3 ||
            !IsType(symbol.Parameters[0].Type, "global::System.Net.Http.HttpRequestMessage"))
        {
            return false;
        }

        if (symbol.Parameters.Length is 1)
        {
            overload = HttpClientSendAsyncOverload.Request;
            return true;
        }

        if (symbol.Parameters.Length is 2)
        {
            if (IsType(symbol.Parameters[1].Type, "global::System.Threading.CancellationToken"))
            {
                overload = HttpClientSendAsyncOverload.RequestCancellationToken;
                return true;
            }

            if (IsType(symbol.Parameters[1].Type, "global::System.Net.Http.HttpCompletionOption"))
            {
                overload = HttpClientSendAsyncOverload.RequestCompletionOption;
                return true;
            }
        }

        if (symbol.Parameters.Length is 3 &&
            IsType(symbol.Parameters[1].Type, "global::System.Net.Http.HttpCompletionOption") &&
            IsType(symbol.Parameters[2].Type, "global::System.Threading.CancellationToken"))
        {
            overload = HttpClientSendAsyncOverload.RequestCompletionOptionCancellationToken;
            return true;
        }

        return false;
    }

    private static bool IsType(ITypeSymbol? symbol, string fullyQualifiedMetadataName)
        => symbol?.ToDisplayString(FullyQualifiedFormat) == fullyQualifiedMetadataName;

    private enum HttpClientSendAsyncOverload
    {
        Request,
        RequestCancellationToken,
        RequestCompletionOption,
        RequestCompletionOptionCancellationToken,
    }

    private readonly record struct InterceptedInvocation(
        string ContractId,
        HttpClientSendAsyncOverload Overload,
        InterceptableLocation Location);
}
