using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Qyl.AutoInstrumentation.SourceGenerators;

[Generator(LanguageNames.CSharp)]
public sealed class QylAutoInstrumentationGenerator : IIncrementalGenerator
{
    private static readonly SymbolDisplayFormat FullyQualifiedFormat =
        SymbolDisplayFormat.FullyQualifiedFormat;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static output =>
        {
            output.AddSource(
                "QylGeneratedInstrumentationContract.g.cs",
                SourceText.From(InstrumentationContract.EmitGeneratedManifestSource(), Encoding.UTF8));
        });

        var interceptedInvocations = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is InvocationExpressionSyntax,
                static (syntaxContext, cancellationToken) => TryCreateInterceptedInvocation(syntaxContext, cancellationToken))
            .Where(static invocation => invocation is not null)
            .Collect();

        context.RegisterSourceOutput(interceptedInvocations, static (sourceContext, invocations) =>
        {
            EmitInterceptors(sourceContext, invocations);
        });
    }

    private static InterceptedInvocation? TryCreateInterceptedInvocation(
        GeneratorSyntaxContext context,
        CancellationToken cancellationToken)
    {
        var invocation = (InvocationExpressionSyntax)context.Node;
        if (string.Equals(context.SemanticModel.Compilation.AssemblyName, "Qyl.AutoInstrumentation", StringComparison.Ordinal))
            return null;

        if (context.SemanticModel.GetSymbolInfo(invocation, cancellationToken).Symbol is not IMethodSymbol symbol)
            return null;

        if (!TryGetInvocation(symbol, out var target))
            return null;

        if (InstrumentationContract.TryGetSupportedSignal(target.ContractKey) is null)
            return null;

        var interceptableLocation = context.SemanticModel.GetInterceptableLocation(invocation, cancellationToken);
        if (interceptableLocation is null)
            return null;

        return new InterceptedInvocation(target, interceptableLocation);
    }

    private static bool TryGetInvocation(IMethodSymbol symbol, out InterceptorTarget target)
    {
        if (TryGetHttpClientInvocation(symbol, out target))
            return true;

        if (TryGetAspNetCoreRequestDelegateInvocation(symbol, out target))
            return true;

        if (TryGetDbCommandInvocation(symbol, out target))
            return true;

        target = default;
        return false;
    }

    private static void EmitInterceptors(
        SourceProductionContext context,
        ImmutableArray<InterceptedInvocation?> nullableInvocations)
    {
        if (nullableInvocations.IsDefaultOrEmpty)
            return;

        var invocations = nullableInvocations
            .Where(static invocation => invocation is not null)
            .Select(static invocation => invocation!.Value)
            .Distinct()
            .ToArray();

        if (invocations.Length is 0)
            return;

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("namespace System.Runtime.CompilerServices");
        builder.AppendLine("{");
        builder.AppendLine("    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]");
        builder.AppendLine("    internal sealed class InterceptsLocationAttribute : global::System.Attribute");
        builder.AppendLine("    {");
        builder.AppendLine("        public InterceptsLocationAttribute(int version, string data) { }");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("namespace Qyl.AutoInstrumentation.Generated");
        builder.AppendLine("{");
        builder.AppendLine("    internal static class QylGeneratedInterceptors");
        builder.AppendLine("    {");

        for (var index = 0; index < invocations.Length; index++)
        {
            var invocation = invocations[index];
            if (invocation.Target.Kind is InterceptorKind.HttpClient)
                EmitHttpClientInterceptor(builder, invocation, index);
            else if (invocation.Target.Kind is InterceptorKind.AspNetCoreRequestDelegate)
                EmitAspNetCoreRequestDelegateInterceptor(builder, invocation, index);
            else
                EmitDbCommandInterceptor(builder, invocation, index);
        }

        builder.AppendLine("    }");
        builder.AppendLine("}");

        context.AddSource("QylAutoInstrumentation.Interceptors.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
    }

    private static void EmitHttpClientInterceptor(StringBuilder builder, InterceptedInvocation invocation, int index)
    {
        var target = invocation.Target;
        EmitAttributeAndSignature(builder, invocation.Location, target.ReturnType, "HttpClient_" + target.MethodName, index, "global::System.Net.Http.HttpClient", "client", target.Parameters, isAsync: false);
        builder.Append("            => global::Qyl.AutoInstrumentation.QylInterceptedHttpClient.");
        builder.Append(target.MethodName);
        builder.Append("(client");
        AppendArgumentList(builder, target.Parameters, includeLeadingComma: true);
        builder.AppendLine(");");
        builder.AppendLine();
    }

    private static void EmitDbCommandInterceptor(StringBuilder builder, InterceptedInvocation invocation, int index)
    {
        var target = invocation.Target;
        EmitAttributeAndSignature(builder, invocation.Location, target.ReturnType, "DbCommand_" + target.MethodName, index, target.ReceiverType, "command", target.Parameters, target.IsAsync);
        builder.AppendLine("        {");
        builder.Append("            var activity = global::Qyl.AutoInstrumentation.QylInterceptedDbCommand.StartActivity(command, ");
        AppendStringLiteral(builder, target.InstrumentationId);
        builder.Append(", ");
        AppendStringLiteral(builder, target.MethodName);
        builder.AppendLine(");");
        builder.AppendLine("            try");
        builder.AppendLine("            {");

        if (target.IsAsync)
        {
            builder.Append("                var result = await command.");
            builder.Append(target.MethodName);
            builder.Append('(');
            AppendArgumentList(builder, target.Parameters, includeLeadingComma: false);
            builder.AppendLine(").ConfigureAwait(false);");
        }
        else
        {
            builder.Append("                var result = command.");
            builder.Append(target.MethodName);
            builder.Append('(');
            AppendArgumentList(builder, target.Parameters, includeLeadingComma: false);
            builder.AppendLine(");");
        }

        builder.AppendLine("                global::Qyl.AutoInstrumentation.QylInterceptedDbCommand.RecordSuccess(activity);");
        builder.AppendLine("                return result;");
        builder.AppendLine("            }");
        builder.AppendLine("            catch (global::System.Exception exception)");
        builder.AppendLine("            {");
        builder.AppendLine("                global::Qyl.AutoInstrumentation.QylInterceptedDbCommand.RecordException(activity, exception);");
        builder.AppendLine("                throw;");
        builder.AppendLine("            }");
        builder.AppendLine("            finally");
        builder.AppendLine("            {");
        builder.AppendLine("                activity?.Dispose();");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
    }

    private static void EmitAspNetCoreRequestDelegateInterceptor(StringBuilder builder, InterceptedInvocation invocation, int index)
    {
        var target = invocation.Target;
        EmitAttributeAndSignature(builder, invocation.Location, target.ReturnType, "AspNetCoreRequestDelegate_" + target.MethodName, index, target.ReceiverType, "requestDelegate", target.Parameters, isAsync: false);
        builder.AppendLine("            => global::Qyl.AutoInstrumentation.QylInterceptedAspNetCore.InvokeAsync(requestDelegate, p0);");
        builder.AppendLine();
    }

    private static void EmitAttributeAndSignature(
        StringBuilder builder,
        InterceptableLocation location,
        string returnType,
        string methodPrefix,
        int index,
        string receiverType,
        string receiverName,
        ImmutableArray<ParameterSpec> parameters,
        bool isAsync)
    {
        var attribute = Microsoft.CodeAnalysis.CSharp.CSharpExtensions.GetInterceptsLocationAttributeSyntax(location);
        builder.Append("        ");
        builder.AppendLine(attribute);
        builder.Append("        public static ");
        if (isAsync)
            builder.Append("async ");

        builder.Append(returnType);
        builder.Append(' ');
        builder.Append(methodPrefix);
        builder.Append('_');
        builder.Append(index.ToString(System.Globalization.CultureInfo.InvariantCulture));
        builder.Append("(this ");
        builder.Append(receiverType);
        builder.Append(' ');
        builder.Append(receiverName);
        AppendParameterList(builder, parameters);
        builder.AppendLine(")");
    }

    private static void AppendParameterList(StringBuilder builder, ImmutableArray<ParameterSpec> parameters)
    {
        foreach (var parameter in parameters)
        {
            builder.Append(", ");
            builder.Append(parameter.TypeName);
            builder.Append(' ');
            builder.Append(parameter.Name);
        }
    }

    private static void AppendArgumentList(StringBuilder builder, ImmutableArray<ParameterSpec> parameters, bool includeLeadingComma)
    {
        for (var i = 0; i < parameters.Length; i++)
        {
            if (i > 0 || includeLeadingComma)
                builder.Append(", ");

            builder.Append(parameters[i].Name);
        }
    }

    private static bool TryGetHttpClientInvocation(IMethodSymbol symbol, out InterceptorTarget target)
    {
        target = default;
        if (!IsType(symbol.ContainingType, "global::System.Net.Http.HttpClient"))
            return false;

        if (string.Equals(symbol.Name, "Send", StringComparison.Ordinal) &&
            IsType(symbol.ReturnType, "global::System.Net.Http.HttpResponseMessage") &&
            TryGetSendShape(symbol, out var parameters))
        {
            target = HttpTarget(symbol, "Send", "global::System.Net.Http.HttpResponseMessage", parameters);
            return true;
        }

        if (string.Equals(symbol.Name, "SendAsync", StringComparison.Ordinal) &&
            IsTaskOf(symbol.ReturnType, "global::System.Net.Http.HttpResponseMessage") &&
            TryGetSendShape(symbol, out parameters))
        {
            target = HttpTarget(symbol, "SendAsync", "global::System.Threading.Tasks.Task<global::System.Net.Http.HttpResponseMessage>", parameters);
            return true;
        }

        if (string.Equals(symbol.Name, "GetAsync", StringComparison.Ordinal) &&
            IsTaskOf(symbol.ReturnType, "global::System.Net.Http.HttpResponseMessage") &&
            TryGetRequestUriShape(symbol, allowCompletionOption: true, out parameters))
        {
            target = HttpTarget(symbol, "GetAsync", "global::System.Threading.Tasks.Task<global::System.Net.Http.HttpResponseMessage>", parameters);
            return true;
        }

        if (string.Equals(symbol.Name, "DeleteAsync", StringComparison.Ordinal) &&
            IsTaskOf(symbol.ReturnType, "global::System.Net.Http.HttpResponseMessage") &&
            TryGetRequestUriShape(symbol, allowCompletionOption: false, out parameters))
        {
            target = HttpTarget(symbol, "DeleteAsync", "global::System.Threading.Tasks.Task<global::System.Net.Http.HttpResponseMessage>", parameters);
            return true;
        }

        if (string.Equals(symbol.Name, "PostAsync", StringComparison.Ordinal) &&
            IsTaskOf(symbol.ReturnType, "global::System.Net.Http.HttpResponseMessage") &&
            TryGetRequestUriContentShape(symbol, out parameters))
        {
            target = HttpTarget(symbol, "PostAsync", "global::System.Threading.Tasks.Task<global::System.Net.Http.HttpResponseMessage>", parameters);
            return true;
        }

        if (string.Equals(symbol.Name, "PutAsync", StringComparison.Ordinal) &&
            IsTaskOf(symbol.ReturnType, "global::System.Net.Http.HttpResponseMessage") &&
            TryGetRequestUriContentShape(symbol, out parameters))
        {
            target = HttpTarget(symbol, "PutAsync", "global::System.Threading.Tasks.Task<global::System.Net.Http.HttpResponseMessage>", parameters);
            return true;
        }

        if (string.Equals(symbol.Name, "PatchAsync", StringComparison.Ordinal) &&
            IsTaskOf(symbol.ReturnType, "global::System.Net.Http.HttpResponseMessage") &&
            TryGetRequestUriContentShape(symbol, out parameters))
        {
            target = HttpTarget(symbol, "PatchAsync", "global::System.Threading.Tasks.Task<global::System.Net.Http.HttpResponseMessage>", parameters);
            return true;
        }

        if (string.Equals(symbol.Name, "GetStringAsync", StringComparison.Ordinal) &&
            IsTaskOf(symbol.ReturnType, "global::System.String") &&
            TryGetRequestUriShape(symbol, allowCompletionOption: false, out parameters))
        {
            target = HttpTarget(symbol, "GetStringAsync", "global::System.Threading.Tasks.Task<string>", parameters);
            return true;
        }

        if (string.Equals(symbol.Name, "GetByteArrayAsync", StringComparison.Ordinal) &&
            IsTaskOf(symbol.ReturnType, "global::System.Byte[]") &&
            TryGetRequestUriShape(symbol, allowCompletionOption: false, out parameters))
        {
            target = HttpTarget(symbol, "GetByteArrayAsync", "global::System.Threading.Tasks.Task<byte[]>", parameters);
            return true;
        }

        if (string.Equals(symbol.Name, "GetStreamAsync", StringComparison.Ordinal) &&
            IsTaskOf(symbol.ReturnType, "global::System.IO.Stream") &&
            TryGetRequestUriShape(symbol, allowCompletionOption: false, out parameters))
        {
            target = HttpTarget(symbol, "GetStreamAsync", "global::System.Threading.Tasks.Task<global::System.IO.Stream>", parameters);
            return true;
        }

        return false;
    }

    private static bool TryGetDbCommandInvocation(IMethodSymbol symbol, out InterceptorTarget target)
    {
        target = default;
        if (!InheritsFromOrIs(symbol.ContainingType, "global::System.Data.Common.DbCommand"))
            return false;

        var methodName = symbol.Name;
        var isAsync = methodName.EndsWith("Async", StringComparison.Ordinal);
        if (!TryGetDbCommandParameters(symbol, methodName, out var parameters))
            return false;

        if (!TryGetDbCommandReturn(symbol, methodName, isAsync, out var returnType))
            return false;

        var instrumentationId = GetDbInstrumentationId(symbol.ContainingType);
        target = new InterceptorTarget(
            InterceptorKind.DbCommand,
            "signals.traces." + instrumentationId,
            instrumentationId,
            CleanTypeName(symbol.ContainingType),
            methodName,
            returnType,
            parameters,
            isAsync);
        return true;
    }

    private static bool TryGetAspNetCoreRequestDelegateInvocation(IMethodSymbol symbol, out InterceptorTarget target)
    {
        target = default;
        if (!string.Equals(symbol.Name, "Invoke", StringComparison.Ordinal) ||
            !IsType(symbol.ContainingType, "global::Microsoft.AspNetCore.Http.RequestDelegate") ||
            !IsTask(symbol.ReturnType) ||
            symbol.Parameters.Length is not 1 ||
            !IsType(symbol.Parameters[0].Type, "global::Microsoft.AspNetCore.Http.HttpContext"))
        {
            return false;
        }

        target = new InterceptorTarget(
            InterceptorKind.AspNetCoreRequestDelegate,
            "signals.traces.ASPNETCORE",
            "ASPNETCORE",
            CleanTypeName(symbol.ContainingType),
            "Invoke",
            "global::System.Threading.Tasks.Task",
            Parameters(symbol),
            false);
        return true;
    }

    private static bool TryGetDbCommandParameters(IMethodSymbol symbol, string methodName, out ImmutableArray<ParameterSpec> parameters)
    {
        parameters = ImmutableArray<ParameterSpec>.Empty;
        if (string.Equals(methodName, "ExecuteReader", StringComparison.Ordinal))
            return TryGetDbExecuteReaderParameters(symbol, allowCancellationToken: false, out parameters);

        if (string.Equals(methodName, "ExecuteReaderAsync", StringComparison.Ordinal))
            return TryGetDbExecuteReaderParameters(symbol, allowCancellationToken: true, out parameters);

        if (string.Equals(methodName, "ExecuteScalar", StringComparison.Ordinal) ||
            string.Equals(methodName, "ExecuteNonQuery", StringComparison.Ordinal))
            return TryGetNoParameters(symbol, out parameters);

        if (string.Equals(methodName, "ExecuteScalarAsync", StringComparison.Ordinal) ||
            string.Equals(methodName, "ExecuteNonQueryAsync", StringComparison.Ordinal))
            return TryGetOptionalCancellationTokenParameters(symbol, out parameters);

        return false;
    }

    private static bool TryGetDbCommandReturn(IMethodSymbol symbol, string methodName, bool isAsync, out string returnType)
    {
        returnType = CleanTypeName(symbol.ReturnType);
        if (string.Equals(methodName, "ExecuteNonQuery", StringComparison.Ordinal))
            return symbol.ReturnType.SpecialType is SpecialType.System_Int32;

        if (string.Equals(methodName, "ExecuteScalar", StringComparison.Ordinal))
            return symbol.ReturnType.SpecialType is SpecialType.System_Object;

        if (string.Equals(methodName, "ExecuteReader", StringComparison.Ordinal))
            return InheritsFromOrIs(symbol.ReturnType, "global::System.Data.Common.DbDataReader");

        if (!isAsync || !TryGetTaskResult(symbol.ReturnType, out var taskResult))
            return false;

        if (string.Equals(methodName, "ExecuteNonQueryAsync", StringComparison.Ordinal))
            return taskResult.SpecialType is SpecialType.System_Int32;

        if (string.Equals(methodName, "ExecuteScalarAsync", StringComparison.Ordinal))
            return taskResult.SpecialType is SpecialType.System_Object;

        if (string.Equals(methodName, "ExecuteReaderAsync", StringComparison.Ordinal))
            return InheritsFromOrIs(taskResult, "global::System.Data.Common.DbDataReader");

        return false;
    }

    private static InterceptorTarget HttpTarget(IMethodSymbol symbol, string methodName, string returnType, ImmutableArray<ParameterSpec> parameters)
        => new(
            InterceptorKind.HttpClient,
            "signals.traces.HTTPCLIENT",
            "HTTPCLIENT",
            CleanTypeName(symbol.ContainingType),
            methodName,
            returnType,
            parameters,
            false);

    private static bool TryGetSendShape(IMethodSymbol symbol, out ImmutableArray<ParameterSpec> parameters)
    {
        parameters = ImmutableArray<ParameterSpec>.Empty;
        if (symbol.Parameters.Length is < 1 or > 3 ||
            !IsType(symbol.Parameters[0].Type, "global::System.Net.Http.HttpRequestMessage"))
        {
            return false;
        }

        if (symbol.Parameters.Length is 1)
        {
            parameters = Parameters(symbol);
            return true;
        }

        if (symbol.Parameters.Length is 2)
        {
            if (IsType(symbol.Parameters[1].Type, "global::System.Threading.CancellationToken") ||
                IsType(symbol.Parameters[1].Type, "global::System.Net.Http.HttpCompletionOption"))
            {
                parameters = Parameters(symbol);
                return true;
            }
        }

        if (symbol.Parameters.Length is 3 &&
            IsType(symbol.Parameters[1].Type, "global::System.Net.Http.HttpCompletionOption") &&
            IsType(symbol.Parameters[2].Type, "global::System.Threading.CancellationToken"))
        {
            parameters = Parameters(symbol);
            return true;
        }

        return false;
    }

    private static bool TryGetRequestUriShape(IMethodSymbol symbol, bool allowCompletionOption, out ImmutableArray<ParameterSpec> parameters)
    {
        parameters = ImmutableArray<ParameterSpec>.Empty;
        if (symbol.Parameters.Length is < 1 or > 3)
            return false;

        var firstIsString = IsType(symbol.Parameters[0].Type, "global::System.String");
        var firstIsUri = IsType(symbol.Parameters[0].Type, "global::System.Uri");
        if (!firstIsString && !firstIsUri)
            return false;

        if (symbol.Parameters.Length is 1)
        {
            parameters = Parameters(symbol);
            return true;
        }

        if (symbol.Parameters.Length is 2)
        {
            if (IsType(symbol.Parameters[1].Type, "global::System.Threading.CancellationToken") ||
                (allowCompletionOption && IsType(symbol.Parameters[1].Type, "global::System.Net.Http.HttpCompletionOption")))
            {
                parameters = Parameters(symbol);
                return true;
            }
        }

        if (allowCompletionOption &&
            symbol.Parameters.Length is 3 &&
            IsType(symbol.Parameters[1].Type, "global::System.Net.Http.HttpCompletionOption") &&
            IsType(symbol.Parameters[2].Type, "global::System.Threading.CancellationToken"))
        {
            parameters = Parameters(symbol);
            return true;
        }

        return false;
    }

    private static bool TryGetRequestUriContentShape(IMethodSymbol symbol, out ImmutableArray<ParameterSpec> parameters)
    {
        parameters = ImmutableArray<ParameterSpec>.Empty;
        if (symbol.Parameters.Length is not (2 or 3))
            return false;

        var firstIsString = IsType(symbol.Parameters[0].Type, "global::System.String");
        var firstIsUri = IsType(symbol.Parameters[0].Type, "global::System.Uri");
        if ((!firstIsString && !firstIsUri) ||
            !IsType(symbol.Parameters[1].Type, "global::System.Net.Http.HttpContent"))
        {
            return false;
        }

        if (symbol.Parameters.Length is 2 || IsType(symbol.Parameters[2].Type, "global::System.Threading.CancellationToken"))
        {
            parameters = Parameters(symbol);
            return true;
        }

        return false;
    }

    private static bool TryGetNoParameters(IMethodSymbol symbol, out ImmutableArray<ParameterSpec> parameters)
    {
        if (symbol.Parameters.Length is 0)
        {
            parameters = ImmutableArray<ParameterSpec>.Empty;
            return true;
        }

        parameters = ImmutableArray<ParameterSpec>.Empty;
        return false;
    }

    private static bool TryGetOptionalCancellationTokenParameters(IMethodSymbol symbol, out ImmutableArray<ParameterSpec> parameters)
    {
        if (symbol.Parameters.Length is 0)
        {
            parameters = ImmutableArray<ParameterSpec>.Empty;
            return true;
        }

        if (symbol.Parameters.Length is 1 && IsType(symbol.Parameters[0].Type, "global::System.Threading.CancellationToken"))
        {
            parameters = Parameters(symbol);
            return true;
        }

        parameters = ImmutableArray<ParameterSpec>.Empty;
        return false;
    }

    private static bool TryGetDbExecuteReaderParameters(IMethodSymbol symbol, bool allowCancellationToken, out ImmutableArray<ParameterSpec> parameters)
    {
        if (symbol.Parameters.Length is 0)
        {
            parameters = ImmutableArray<ParameterSpec>.Empty;
            return true;
        }

        if (symbol.Parameters.Length is 1)
        {
            if (IsType(symbol.Parameters[0].Type, "global::System.Data.CommandBehavior") ||
                (allowCancellationToken && IsType(symbol.Parameters[0].Type, "global::System.Threading.CancellationToken")))
            {
                parameters = Parameters(symbol);
                return true;
            }
        }

        if (allowCancellationToken &&
            symbol.Parameters.Length is 2 &&
            IsType(symbol.Parameters[0].Type, "global::System.Data.CommandBehavior") &&
            IsType(symbol.Parameters[1].Type, "global::System.Threading.CancellationToken"))
        {
            parameters = Parameters(symbol);
            return true;
        }

        parameters = ImmutableArray<ParameterSpec>.Empty;
        return false;
    }

    private static ImmutableArray<ParameterSpec> Parameters(IMethodSymbol symbol)
    {
        var builder = ImmutableArray.CreateBuilder<ParameterSpec>(symbol.Parameters.Length);
        for (var i = 0; i < symbol.Parameters.Length; i++)
            builder.Add(new ParameterSpec(CleanTypeName(symbol.Parameters[i].Type), "p" + i.ToString(System.Globalization.CultureInfo.InvariantCulture)));

        return builder.ToImmutable();
    }

    private static bool IsTaskOf(ITypeSymbol? symbol, string resultFullyQualifiedName)
        => TryGetTaskResult(symbol, out var result) && IsType(result, resultFullyQualifiedName);

    private static bool IsTask(ITypeSymbol? symbol)
        => IsType(symbol, "global::System.Threading.Tasks.Task");

    private static bool TryGetTaskResult(ITypeSymbol? symbol, out ITypeSymbol result)
    {
        result = null!;
        if (symbol is not INamedTypeSymbol named ||
            !IsType(named.ConstructedFrom, "global::System.Threading.Tasks.Task<TResult>") ||
            named.TypeArguments.Length is not 1)
        {
            return false;
        }

        result = named.TypeArguments[0];
        return true;
    }

    private static bool InheritsFromOrIs(ITypeSymbol? symbol, string fullyQualifiedName)
    {
        for (var current = symbol; current is not null; current = (current as INamedTypeSymbol)?.BaseType)
        {
            if (IsType(current, fullyQualifiedName))
                return true;
        }

        return false;
    }

    private static bool IsType(ITypeSymbol? symbol, string fullyQualifiedName)
    {
        if (symbol is null)
            return false;

        if (fullyQualifiedName is "global::System.String")
            return symbol.SpecialType is SpecialType.System_String;

        if (fullyQualifiedName is "global::System.Byte[]")
            return symbol is IArrayTypeSymbol { ElementType.SpecialType: SpecialType.System_Byte, Rank: 1 };

        if (fullyQualifiedName is "global::System.Object")
            return symbol.SpecialType is SpecialType.System_Object;

        var display = CleanTypeName(symbol);
        return string.Equals(display, fullyQualifiedName, StringComparison.Ordinal);
    }

    private static string GetDbInstrumentationId(ITypeSymbol type)
    {
        var display = CleanTypeName(type);
        if (display.StartsWith("global::Microsoft.Data.SqlClient.", StringComparison.Ordinal) ||
            display.StartsWith("global::System.Data.SqlClient.", StringComparison.Ordinal))
        {
            return "SQLCLIENT";
        }

        if (display.StartsWith("global::Microsoft.Data.Sqlite.", StringComparison.Ordinal))
            return "SQLITE";

        if (display.StartsWith("global::Npgsql.", StringComparison.Ordinal))
            return "NPGSQL";

        if (display.StartsWith("global::MySqlConnector.", StringComparison.Ordinal))
            return "MYSQLCONNECTOR";

        if (display.StartsWith("global::MySql.Data.", StringComparison.Ordinal))
            return "MYSQLDATA";

        if (display.StartsWith("global::Oracle.ManagedDataAccess.", StringComparison.Ordinal))
            return "ORACLEMDA";

        return "ADONET";
    }

    private static string CleanTypeName(ITypeSymbol symbol)
        => symbol.ToDisplayString(FullyQualifiedFormat).Replace("?", string.Empty);

    private static void AppendStringLiteral(StringBuilder builder, string value)
    {
        builder.Append('"');
        builder.Append(value.Replace("\\", "\\\\").Replace("\"", "\\\""));
        builder.Append('"');
    }

    private enum InterceptorKind
    {
        HttpClient,
        AspNetCoreRequestDelegate,
        DbCommand,
    }

    private readonly record struct ParameterSpec(string TypeName, string Name);

    private readonly record struct InterceptorTarget(
        InterceptorKind Kind,
        string ContractKey,
        string InstrumentationId,
        string ReceiverType,
        string MethodName,
        string ReturnType,
        ImmutableArray<ParameterSpec> Parameters,
        bool IsAsync);

    private readonly record struct InterceptedInvocation(InterceptorTarget Target, InterceptableLocation Location);
}
