// <auto-generated/>
#nullable enable
#pragma warning disable
namespace System.Runtime.CompilerServices
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : global::System.Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace Qyl.Telemetry.AutoInstrumentation.Generated
{
    internal static class QylGeneratedInterceptors
    {
        private const int RequiredQylGeneratedCodeAbi = global::Qyl.Telemetry.AutoInstrumentation.GeneratedCode.QylGeneratedCodeAbi.V21;

        // qyl-interceptor-manifest: {"interceptorKind":"DbCommand.Execute","signal":"traces","instrumentationId":"ADONET","additionalMetricIds":[],"contractKeys":["signals.traces.ADONET"]}
        // Intercepted call at /_qyl_generator_snapshot/Program.cs(3,13)
        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "eGGksfDdRGwrsWqffSjv1jgAAABQcm9ncmFtLmNz")]
        public static object DbCommand_ExecuteScalar_0(this global::SnapshotCommand receiver)
        {
            var metricStart = global::Qyl.Telemetry.AutoInstrumentation.GeneratedCode.QylInterceptedDbCommand.GetTimestamp();
            var activity = global::Qyl.Telemetry.AutoInstrumentation.GeneratedCode.QylInterceptedDbCommand.Execute(receiver, "ADONET", "ExecuteScalar");
            try
            {
                var result = receiver.ExecuteScalar();
                global::Qyl.Telemetry.AutoInstrumentation.GeneratedCode.QylInterceptedDbCommand.RecordDuration(metricStart, "ADONET");
                return result;
            }
            catch (global::System.Exception exception)
            {
                global::Qyl.Telemetry.AutoInstrumentation.GeneratedCode.QylInterceptedActivity.RecordException(activity, exception);
                global::Qyl.Telemetry.AutoInstrumentation.GeneratedCode.QylInterceptedDbCommand.RecordDuration(metricStart, "ADONET");
                throw;
            }
            finally
            {
                activity?.Dispose();
            }
        }

        // qyl-interceptor-manifest: {"interceptorKind":"DbCommand.Execute","signal":"traces","instrumentationId":"ADONET","additionalMetricIds":[],"contractKeys":["signals.traces.ADONET"]}
        // Intercepted call at /_qyl_generator_snapshot/Probe.cs(9,21)
        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "glSC8NWNHiYnnvfFTRrffO8BAABQcm9iZS5jcw==")]
        public static object DbCommand_ExecuteScalar_1(this global::SnapshotCommand receiver)
        {
            var metricStart = global::Qyl.Telemetry.AutoInstrumentation.GeneratedCode.QylInterceptedDbCommand.GetTimestamp();
            var activity = global::Qyl.Telemetry.AutoInstrumentation.GeneratedCode.QylInterceptedDbCommand.Execute(receiver, "ADONET", "ExecuteScalar");
            try
            {
                var result = receiver.ExecuteScalar();
                global::Qyl.Telemetry.AutoInstrumentation.GeneratedCode.QylInterceptedDbCommand.RecordDuration(metricStart, "ADONET");
                return result;
            }
            catch (global::System.Exception exception)
            {
                global::Qyl.Telemetry.AutoInstrumentation.GeneratedCode.QylInterceptedActivity.RecordException(activity, exception);
                global::Qyl.Telemetry.AutoInstrumentation.GeneratedCode.QylInterceptedDbCommand.RecordDuration(metricStart, "ADONET");
                throw;
            }
            finally
            {
                activity?.Dispose();
            }
        }

    }
}
