// <auto-generated/>
#nullable enable
#pragma warning disable
namespace System.Runtime.CompilerServices
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : global::System.Attribute
    {
        public InterceptsLocationAttribute(int version, string data)
        {
        }
    }
}

namespace Qyl.Telemetry.AutoInstrumentation.Generated
{
    internal static class QylGeneratedInterceptors
    {
        private const int RequiredQylGeneratedCodeAbi = global::Qyl.Telemetry.AutoInstrumentation.GeneratedCode.QylGeneratedCodeAbi.V10;

        // qyl-interceptor-manifest: {"interceptorKind":"HttpClient.Forward","signal":"traces","instrumentationId":"HTTPCLIENT","additionalMetricIds":["HTTPCLIENT"],"contractKeys":["signals.traces.HTTPCLIENT","signals.metrics.HTTPCLIENT"]}
        // Intercepted call at /_qyl_generator_snapshot/Program.cs(6,21)
        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "0T8NCMWQIrhqyFBG+phcs3kAAABQcm9ncmFtLmNz")]
        public static global::System.Threading.Tasks.Task<global::System.Net.Http.HttpResponseMessage> HttpClient_GetAsync_0(this global::System.Net.Http.HttpClient receiver, string p0)
            => global::Qyl.Telemetry.AutoInstrumentation.GeneratedCode.QylInterceptedHttpClient.GetAsync(receiver, p0);

        // qyl-interceptor-manifest: {"interceptorKind":"HttpClient.Forward","signal":"traces","instrumentationId":"HTTPCLIENT","additionalMetricIds":["HTTPCLIENT"],"contractKeys":["signals.traces.HTTPCLIENT","signals.metrics.HTTPCLIENT"]}
        // Intercepted call at /_qyl_generator_snapshot/Probe.cs(11,29)
        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "uk73+ILVjKhwjuVSYkMzfxACAABQcm9iZS5jcw==")]
        public static global::System.Threading.Tasks.Task<global::System.Net.Http.HttpResponseMessage> HttpClient_GetAsync_1(this global::System.Net.Http.HttpClient receiver, string p0)
            => global::Qyl.Telemetry.AutoInstrumentation.GeneratedCode.QylInterceptedHttpClient.GetAsync(receiver, p0);

    }
}
