// <auto-generated/> compiler-visible semantic contract (pre-compilation phase).
#nullable enable
namespace Qyl.Snapshot.Domain;

[global::Qyl.OpenTelemetry.AutoInstrumentation.Generated.QylSemanticBindingAttribute("CustomerId", "customer.id")]
[global::Qyl.OpenTelemetry.AutoInstrumentation.Generated.QylSemanticBindingAttribute("OrderId", "order.id")]
partial class OrderRequest { }
