// <auto-generated/>
namespace Qyl.OpenTelemetry.AutoInstrumentation.Generated;

internal static class QylGeneratedInstrumentationContract
{
    public const int SignalSpecificInstrumentationPromiseCount = 37;
    public const int GlobalEnvironmentControlCount = 7;
    public const int InstrumentationOptionCount = 16;
    public const int TotalCount = 60;
    public const int TracesSignalSpecificPromiseCount = 26;
    public const int MetricsSignalSpecificPromiseCount = 8;
    public const int LogsSignalSpecificPromiseCount = 3;
    public const int UniqueInstrumentationIdCount = 31;
    public const int ImplementedSignalPromiseCount = 33;
    public const int SourceInterceptorSignalPromiseCount = 24;
    public const int RuntimePublicTelemetrySignalPromiseCount = 8;
    public const int UnsupportedNativeAotSignalPromiseCount = 4;
    public const string AspNetCoreHostingMeterName = "Microsoft.AspNetCore.Hosting";
    public const string AspNetCoreRoutingMeterName = "Microsoft.AspNetCore.Routing";
    public const string AspNetCoreDiagnosticsMeterName = "Microsoft.AspNetCore.Diagnostics";
    public const string AspNetCoreRateLimitingMeterName = "Microsoft.AspNetCore.RateLimiting";
    public const string AspNetCoreHeaderParsingMeterName = "Microsoft.AspNetCore.HeaderParsing";
    public const string AspNetCoreServerKestrelMeterName = "Microsoft.AspNetCore.Server.Kestrel";
    public const string AspNetCoreHttpConnectionsMeterName = "Microsoft.AspNetCore.Http.Connections";
    public const string AspNetCoreAuthorizationMeterName = "Microsoft.AspNetCore.Authorization";
    public const string AspNetCoreAuthenticationMeterName = "Microsoft.AspNetCore.Authentication";
    public const string AspNetCoreComponentsMeterName = "Microsoft.AspNetCore.Components";
    public const string AspNetCoreComponentsLifecycleMeterName = "Microsoft.AspNetCore.Components.Lifecycle";
    public const string AspNetCoreComponentsServerCircuitsMeterName = "Microsoft.AspNetCore.Components.Server.Circuits";
    public const string NameResolutionMeterName = "System.Net.NameResolution";
    public const string NServiceBusIncomingPipelineMeterName = "NServiceBus.Core.Pipeline.Incoming";

    public static string[] ItemIds => new[]
    {
        "signals.traces.ADONET",
        "signals.traces.ASPNET",
        "signals.traces.ASPNETCORE",
        "signals.traces.AZURE",
        "signals.traces.ELASTICSEARCH",
        "signals.traces.ELASTICTRANSPORT",
        "signals.traces.ENTITYFRAMEWORKCORE",
        "signals.traces.GRAPHQL",
        "signals.traces.GRPCNETCLIENT",
        "signals.traces.HTTPCLIENT",
        "signals.traces.KAFKA",
        "signals.traces.MASSTRANSIT",
        "signals.traces.MONGODB",
        "signals.traces.MYSQLCONNECTOR",
        "signals.traces.MYSQLDATA",
        "signals.traces.NPGSQL",
        "signals.traces.NSERVICEBUS",
        "signals.traces.ORACLEMDA",
        "signals.traces.RABBITMQ",
        "signals.traces.QUARTZ",
        "signals.traces.SQLCLIENT",
        "signals.traces.SQLITE",
        "signals.traces.STACKEXCHANGEREDIS",
        "signals.traces.WCFCLIENT",
        "signals.traces.WCFCORE",
        "signals.traces.WCFSERVICE",
        "signals.metrics.ASPNET",
        "signals.metrics.ASPNETCORE",
        "signals.metrics.HTTPCLIENT",
        "signals.metrics.NETRUNTIME",
        "signals.metrics.NPGSQL",
        "signals.metrics.NSERVICEBUS",
        "signals.metrics.PROCESS",
        "signals.metrics.SQLCLIENT",
        "signals.logs.ILOGGER",
        "signals.logs.LOG4NET",
        "signals.logs.NLOG",
        "global_environment_controls.OTEL_DOTNET_AUTO_INSTRUMENTATION_ENABLED",
        "global_environment_controls.OTEL_DOTNET_AUTO_TRACES_INSTRUMENTATION_ENABLED",
        "global_environment_controls.OTEL_DOTNET_AUTO_TRACES_{0}_INSTRUMENTATION_ENABLED",
        "global_environment_controls.OTEL_DOTNET_AUTO_METRICS_INSTRUMENTATION_ENABLED",
        "global_environment_controls.OTEL_DOTNET_AUTO_METRICS_{0}_INSTRUMENTATION_ENABLED",
        "global_environment_controls.OTEL_DOTNET_AUTO_LOGS_INSTRUMENTATION_ENABLED",
        "global_environment_controls.OTEL_DOTNET_AUTO_LOGS_{0}_INSTRUMENTATION_ENABLED",
        "instrumentation_options.OTEL_DOTNET_AUTO_ENTITYFRAMEWORKCORE_SET_DBSTATEMENT_FOR_TEXT",
        "instrumentation_options.OTEL_DOTNET_AUTO_GRAPHQL_SET_DOCUMENT",
        "instrumentation_options.OTEL_DOTNET_AUTO_ORACLEMDA_SET_DBSTATEMENT_FOR_TEXT",
        "instrumentation_options.OTEL_DOTNET_AUTO_SQLCLIENT_SET_DBSTATEMENT_FOR_TEXT",
        "instrumentation_options.OTEL_DOTNET_AUTO_TRACES_ASPNET_INSTRUMENTATION_CAPTURE_REQUEST_HEADERS",
        "instrumentation_options.OTEL_DOTNET_AUTO_TRACES_ASPNET_INSTRUMENTATION_CAPTURE_RESPONSE_HEADERS",
        "instrumentation_options.OTEL_DOTNET_AUTO_TRACES_ASPNETCORE_INSTRUMENTATION_CAPTURE_REQUEST_HEADERS",
        "instrumentation_options.OTEL_DOTNET_AUTO_TRACES_ASPNETCORE_INSTRUMENTATION_CAPTURE_RESPONSE_HEADERS",
        "instrumentation_options.OTEL_DOTNET_AUTO_TRACES_GRPCNETCLIENT_INSTRUMENTATION_CAPTURE_REQUEST_METADATA",
        "instrumentation_options.OTEL_DOTNET_AUTO_TRACES_GRPCNETCLIENT_INSTRUMENTATION_CAPTURE_RESPONSE_METADATA",
        "instrumentation_options.OTEL_DOTNET_AUTO_TRACES_HTTP_INSTRUMENTATION_CAPTURE_REQUEST_HEADERS",
        "instrumentation_options.OTEL_DOTNET_AUTO_TRACES_HTTP_INSTRUMENTATION_CAPTURE_RESPONSE_HEADERS",
        "instrumentation_options.OTEL_DOTNET_EXPERIMENTAL_ASPNETCORE_DISABLE_URL_QUERY_REDACTION",
        "instrumentation_options.OTEL_DOTNET_EXPERIMENTAL_HTTPCLIENT_DISABLE_URL_QUERY_REDACTION",
        "instrumentation_options.OTEL_DOTNET_EXPERIMENTAL_ASPNET_DISABLE_URL_QUERY_REDACTION",
        "instrumentation_options.OTEL_DOTNET_AUTO_SQLCLIENT_NETFX_ILREWRITE_ENABLED",
    };

    public static string[] SignalKeys => new[]
    {
        "signals.traces.ADONET",
        "signals.traces.ASPNET",
        "signals.traces.ASPNETCORE",
        "signals.traces.AZURE",
        "signals.traces.ELASTICSEARCH",
        "signals.traces.ELASTICTRANSPORT",
        "signals.traces.ENTITYFRAMEWORKCORE",
        "signals.traces.GRAPHQL",
        "signals.traces.GRPCNETCLIENT",
        "signals.traces.HTTPCLIENT",
        "signals.traces.KAFKA",
        "signals.traces.MASSTRANSIT",
        "signals.traces.MONGODB",
        "signals.traces.MYSQLCONNECTOR",
        "signals.traces.MYSQLDATA",
        "signals.traces.NPGSQL",
        "signals.traces.NSERVICEBUS",
        "signals.traces.ORACLEMDA",
        "signals.traces.RABBITMQ",
        "signals.traces.QUARTZ",
        "signals.traces.SQLCLIENT",
        "signals.traces.SQLITE",
        "signals.traces.STACKEXCHANGEREDIS",
        "signals.traces.WCFCLIENT",
        "signals.traces.WCFCORE",
        "signals.traces.WCFSERVICE",
        "signals.metrics.ASPNET",
        "signals.metrics.ASPNETCORE",
        "signals.metrics.HTTPCLIENT",
        "signals.metrics.NETRUNTIME",
        "signals.metrics.NPGSQL",
        "signals.metrics.NSERVICEBUS",
        "signals.metrics.PROCESS",
        "signals.metrics.SQLCLIENT",
        "signals.logs.ILOGGER",
        "signals.logs.LOG4NET",
        "signals.logs.NLOG",
    };

    public static string[] ImplementedSignalKeys => new[]
    {
        "signals.traces.ADONET",
        "signals.traces.ASPNETCORE",
        "signals.traces.AZURE",
        "signals.traces.ELASTICSEARCH",
        "signals.traces.ELASTICTRANSPORT",
        "signals.traces.ENTITYFRAMEWORKCORE",
        "signals.traces.GRAPHQL",
        "signals.traces.GRPCNETCLIENT",
        "signals.traces.HTTPCLIENT",
        "signals.traces.KAFKA",
        "signals.traces.MASSTRANSIT",
        "signals.traces.MONGODB",
        "signals.traces.MYSQLCONNECTOR",
        "signals.traces.MYSQLDATA",
        "signals.traces.NPGSQL",
        "signals.traces.NSERVICEBUS",
        "signals.traces.ORACLEMDA",
        "signals.traces.RABBITMQ",
        "signals.traces.QUARTZ",
        "signals.traces.SQLCLIENT",
        "signals.traces.SQLITE",
        "signals.traces.STACKEXCHANGEREDIS",
        "signals.traces.WCFCLIENT",
        "signals.metrics.ASPNETCORE",
        "signals.metrics.HTTPCLIENT",
        "signals.metrics.NETRUNTIME",
        "signals.metrics.NPGSQL",
        "signals.metrics.NSERVICEBUS",
        "signals.metrics.PROCESS",
        "signals.metrics.SQLCLIENT",
        "signals.logs.ILOGGER",
        "signals.logs.LOG4NET",
        "signals.logs.NLOG",
    };

    public static string[] SourceInterceptorSignalKeys => new[]
    {
        "signals.traces.ADONET",
        "signals.traces.ELASTICSEARCH",
        "signals.traces.ELASTICTRANSPORT",
        "signals.traces.GRAPHQL",
        "signals.traces.KAFKA",
        "signals.traces.MASSTRANSIT",
        "signals.traces.MONGODB",
        "signals.traces.MYSQLCONNECTOR",
        "signals.traces.MYSQLDATA",
        "signals.traces.NPGSQL",
        "signals.traces.NSERVICEBUS",
        "signals.traces.ORACLEMDA",
        "signals.traces.RABBITMQ",
        "signals.traces.QUARTZ",
        "signals.traces.SQLCLIENT",
        "signals.traces.SQLITE",
        "signals.traces.STACKEXCHANGEREDIS",
        "signals.traces.WCFCLIENT",
        "signals.metrics.NPGSQL",
        "signals.metrics.NSERVICEBUS",
        "signals.metrics.SQLCLIENT",
        "signals.logs.ILOGGER",
        "signals.logs.LOG4NET",
        "signals.logs.NLOG",
    };

    public static string[] RuntimePublicTelemetrySignalKeys => new[]
    {
        "signals.traces.ASPNETCORE",
        "signals.traces.ENTITYFRAMEWORKCORE",
        "signals.traces.GRPCNETCLIENT",
        "signals.traces.HTTPCLIENT",
        "signals.metrics.ASPNETCORE",
        "signals.metrics.HTTPCLIENT",
        "signals.metrics.NETRUNTIME",
        "signals.metrics.PROCESS",
    };

    public static string[] UnsupportedNativeAotSignalKeys => new[]
    {
        "signals.traces.ASPNET",
        "signals.traces.WCFCORE",
        "signals.traces.WCFSERVICE",
        "signals.metrics.ASPNET",
    };

    public static string[] GlobalEnvironmentControls => new[]
    {
        "OTEL_DOTNET_AUTO_INSTRUMENTATION_ENABLED",
        "OTEL_DOTNET_AUTO_TRACES_INSTRUMENTATION_ENABLED",
        "OTEL_DOTNET_AUTO_TRACES_{0}_INSTRUMENTATION_ENABLED",
        "OTEL_DOTNET_AUTO_METRICS_INSTRUMENTATION_ENABLED",
        "OTEL_DOTNET_AUTO_METRICS_{0}_INSTRUMENTATION_ENABLED",
        "OTEL_DOTNET_AUTO_LOGS_INSTRUMENTATION_ENABLED",
        "OTEL_DOTNET_AUTO_LOGS_{0}_INSTRUMENTATION_ENABLED",
    };

    public static string[] InstrumentationOptions => new[]
    {
        "OTEL_DOTNET_AUTO_ENTITYFRAMEWORKCORE_SET_DBSTATEMENT_FOR_TEXT",
        "OTEL_DOTNET_AUTO_GRAPHQL_SET_DOCUMENT",
        "OTEL_DOTNET_AUTO_ORACLEMDA_SET_DBSTATEMENT_FOR_TEXT",
        "OTEL_DOTNET_AUTO_SQLCLIENT_SET_DBSTATEMENT_FOR_TEXT",
        "OTEL_DOTNET_AUTO_TRACES_ASPNET_INSTRUMENTATION_CAPTURE_REQUEST_HEADERS",
        "OTEL_DOTNET_AUTO_TRACES_ASPNET_INSTRUMENTATION_CAPTURE_RESPONSE_HEADERS",
        "OTEL_DOTNET_AUTO_TRACES_ASPNETCORE_INSTRUMENTATION_CAPTURE_REQUEST_HEADERS",
        "OTEL_DOTNET_AUTO_TRACES_ASPNETCORE_INSTRUMENTATION_CAPTURE_RESPONSE_HEADERS",
        "OTEL_DOTNET_AUTO_TRACES_GRPCNETCLIENT_INSTRUMENTATION_CAPTURE_REQUEST_METADATA",
        "OTEL_DOTNET_AUTO_TRACES_GRPCNETCLIENT_INSTRUMENTATION_CAPTURE_RESPONSE_METADATA",
        "OTEL_DOTNET_AUTO_TRACES_HTTP_INSTRUMENTATION_CAPTURE_REQUEST_HEADERS",
        "OTEL_DOTNET_AUTO_TRACES_HTTP_INSTRUMENTATION_CAPTURE_RESPONSE_HEADERS",
        "OTEL_DOTNET_EXPERIMENTAL_ASPNETCORE_DISABLE_URL_QUERY_REDACTION",
        "OTEL_DOTNET_EXPERIMENTAL_HTTPCLIENT_DISABLE_URL_QUERY_REDACTION",
        "OTEL_DOTNET_EXPERIMENTAL_ASPNET_DISABLE_URL_QUERY_REDACTION",
        "OTEL_DOTNET_AUTO_SQLCLIENT_NETFX_ILREWRITE_ENABLED",
    };

}
