// <auto-generated/> shared semantic-contract vocabulary (pre-compilation phase).
#nullable enable
namespace Qyl.OpenTelemetry.AutoInstrumentation.Generated;

/// <summary>Binds a property of the annotated type to an OpenTelemetry attribute key. Emitted into
/// the initial compilation so any generator can read it from the semantic model.</summary>
[global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
internal sealed class QylSemanticBindingAttribute : global::System.Attribute
{
    public QylSemanticBindingAttribute(string property, string attribute)
    {
        Property = property;
        Attribute = attribute;
    }

    public string Property { get; }
    public string Attribute { get; }
}