// <auto-generated/> AOT-safe semantic telemetry generated from the qyl semantic contract.
#nullable enable
namespace Qyl.OpenTelemetry.AutoInstrumentation.Generated;
/// <summary>Records OpenTelemetry semantic-convention tags for <see cref="global::Qyl.Snapshot.Domain.OrderRequest"/>. Pure SetTag; no reflection.</summary>
internal static class OrderRequestTelemetry
{
    public static void Record(global::System.Diagnostics.Activity? activity, global::Qyl.Snapshot.Domain.OrderRequest value)
    {
        if (activity is null) return;
        activity.SetTag("customer.id", value.CustomerId);
        activity.SetTag("order.id", value.OrderId);
    }
}
