// <auto-generated/>
#nullable enable
#pragma warning disable
namespace Qyl.AutoInstrumentation.Generated
{
    internal static class QylGeneratedInterceptors
    {
        // Intercepted call at /_qyl_generator_snapshot/Program.cs(5,8)
        [global::System.Runtime.CompilerServices.InterceptsLocationAttribute(1, "OrHTaGeKBKDZi8Kz3ulm2VQAAABQcm9ncmFtLmNz")]
        public static void ILogger_Log_0<TState>(
            this global::Microsoft.Extensions.Logging.ILogger logger,
            global::Microsoft.Extensions.Logging.LogLevel logLevel,
            global::Microsoft.Extensions.Logging.EventId eventId,
            TState state,
            global::System.Exception? exception,
            global::System.Func<TState, global::System.Exception?, string> formatter)
            => global::Qyl.AutoInstrumentation.QylInterceptedLogger.Log(logger, logLevel, eventId, state, exception, formatter);

    }
}
