// <auto-generated/>
#if NET8_0_OR_GREATER
using System.Runtime.CompilerServices;

namespace Qyl.OpenTelemetry.AutoInstrumentation.SqlClient;

internal static class QylSqlClientAutoInstrumentationConsumerBootstrap
{
    [ModuleInitializer]
    internal static void Initialize()
        => global::Qyl.OpenTelemetry.AutoInstrumentation.GeneratedCode.SqlClientAutoInstrumentationBootstrap.Boot();
}
#endif
