using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Qyl.Spike.Generator;

/// <summary>
/// GATE-0 probe. Proves the two-phase pre-compilation contract works end to end:
///   PHASE A (pre-compilation): emit a marker type into the INITIAL compilation, reading only
///           AdditionalTextsProvider (a permitted non-compilation input).
///   PHASE B (standard):        resolve that marker via GetTypeByMetadataName on the augmented
///           compilation; build-breaking error if it is null.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class PreCompilationSpikeGenerator : IIncrementalGenerator
{
    private const string ProbeMetadataName = "Qyl.Spike.Generated.PreCompilationProbe";

    private static readonly DiagnosticDescriptor CrossPhaseMissing = new(
        id: "QYLSPIKE001",
        title: "Pre-compilation marker not visible in standard phase",
        messageFormat: "GetTypeByMetadataName('{0}') returned null — pre-compilation source did NOT land in the initial compilation",
        category: "QylSpike",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor CrossPhaseOk = new(
        id: "QYLSPIKE002",
        title: "Pre-compilation marker resolved in standard phase",
        messageFormat: "GetTypeByMetadataName('{0}') resolved — pre-compilation source IS visible to the standard phase",
        category: "QylSpike",
        defaultSeverity: DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // ---- PHASE A: pre-compilation. ONLY non-compilation inputs allowed here. ----
        // Drive off AdditionalTextsProvider.Collect() so the type is emitted UNCONDITIONALLY
        // (advisor failure-variable #2): missing/empty additional files must not gate the type.
        var additionalCount = context.AdditionalTextsProvider
            .Collect()
            .Select(static (texts, _) => texts.Length);

        context.RegisterPreCompilationSourceOutput(additionalCount, static (spc, count) =>
        {
            var src =
$$"""
// <auto-generated/> emitted in the PRE-COMPILATION phase.
namespace Qyl.Spike.Generated;

/// <summary>Marker proving RegisterPreCompilationSourceOutput emitted into the initial compilation.</summary>
public static class PreCompilationProbe
{
    /// <summary>Count of AdditionalFiles the pre-compilation phase observed.</summary>
    public const int AdditionalFileCount = {{count}};
}
""";
            spc.AddSource("PreCompilationProbe.g.cs", SourceText.From(src, System.Text.Encoding.UTF8));
        });

        // ---- PHASE B: standard. Reads the augmented compilation (allowed here only). ----
        context.RegisterSourceOutput(context.CompilationProvider, static (spc, compilation) =>
        {
            var probe = compilation.GetTypeByMetadataName(ProbeMetadataName);
            if (probe is null)
            {
                spc.ReportDiagnostic(Diagnostic.Create(CrossPhaseMissing, Location.None, ProbeMetadataName));
                return;
            }

            spc.ReportDiagnostic(Diagnostic.Create(CrossPhaseOk, Location.None, ProbeMetadataName));
            spc.AddSource("StandardPhaseConfirmation.g.cs", SourceText.From(
$$"""
// <auto-generated/> emitted in the STANDARD phase AFTER binding the pre-compilation marker.
namespace Qyl.Spike.Generated;

/// <summary>Marker proving the standard phase bound a symbol declared by the pre-compilation phase.</summary>
public static class StandardPhaseConfirmation
{
    /// <summary>Echo of the value the pre-compilation phase baked into the marker.</summary>
    public const int ObservedAdditionalFileCount = PreCompilationProbe.AdditionalFileCount;
}
""", System.Text.Encoding.UTF8));
        });
    }
}
