// <auto-generated/>
#if NET8_0_OR_GREATER
using System.Runtime.CompilerServices;

namespace Qyl.OpenTelemetry.AutoInstrumentation.EntityFrameworkCore;

internal static class QylEntityFrameworkCoreAutoInstrumentationConsumerBootstrap
{
    [ModuleInitializer]
    internal static void Initialize()
        => global::Qyl.OpenTelemetry.AutoInstrumentation.GeneratedCode.EntityFrameworkCoreAutoInstrumentationBootstrap.Boot();
}
#endif
