// <auto-generated/>
#if NET8_0_OR_GREATER
using System.Runtime.CompilerServices;

namespace Qyl.AutoInstrumentation.SqlClient;

internal static class QylSqlClientAutoInstrumentationConsumerBootstrap
{
    [ModuleInitializer]
    internal static void Initialize()
        => SqlClientAutoInstrumentationBootstrap.Boot();
}
#endif
