#!/usr/bin/env python3
from __future__ import annotations

import filecmp
import shutil
import subprocess
from pathlib import Path

from generator_manifest_coverage import ManifestCoverageError, collect_live_manifest_artifact


ROOT = Path(__file__).resolve().parents[1]
FIXTURE_PROJECT = (
    ROOT
    / "tests"
    / "Qyl.Telemetry.AutoInstrumentation.SourceGenerators.Snapshots"
    / "Fixture"
    / "Qyl.Telemetry.AutoInstrumentation.SourceGenerators.Snapshots.Fixture.csproj"
)
FIXTURE_DIR = FIXTURE_PROJECT.parent
GENERATED_ROOT = ROOT / "artifacts" / "obj" / FIXTURE_PROJECT.stem / "generated"
VERIFIED_ROOT = FIXTURE_DIR.parent / "verified"
VERIFIED_MANIFEST_ARTIFACT = VERIFIED_ROOT / "QylAutoInstrumentation.ContractManifests.verified.jsonl"
RECEIVED_MANIFEST_ARTIFACT = GENERATED_ROOT / "QylAutoInstrumentation.ContractManifests.received.jsonl"

EXPECTED_FILES = {
    "QylAutoInstrumentation.Interceptors.g.verified.cs": "QylAutoInstrumentation.Interceptors.g.cs",
}

REQUIRED_INTERCEPTOR_TOKENS = [
    "// <auto-generated/>",
    "#nullable enable",
    "file sealed class InterceptsLocationAttribute",
    "namespace Qyl.Telemetry.AutoInstrumentation.Generated",
    "internal static class QylGeneratedInterceptors",
    "// Intercepted call at /_qyl_generator_snapshot/Program.cs",
    "[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(",
    "HttpClient_GetAsync_",
    "global::System.Net.Http.HttpClient receiver",
    "global::Qyl.Telemetry.AutoInstrumentation.GeneratedCode.QylInterceptedHttpClient.GetAsync(",
]

FORBIDDEN_INTERCEPTOR_TOKENS = [
    "System.Reflection",
    "Assembly.Load",
    "Activator.CreateInstance",
    "QylActivitySource",
    ".SetTag(",
]


def fail(message: str) -> None:
    raise SystemExit(message)


def run_build() -> str:
    if GENERATED_ROOT.exists():
        shutil.rmtree(GENERATED_ROOT)
    completed = subprocess.run(
        [
            "dotnet",
            "build",
            str(FIXTURE_PROJECT),
            "-c",
            "Release",
            "--disable-build-servers",
            "--no-incremental",
            "-m:1",
            "/nr:false",
            "-v",
            "normal",
            "-p:NuGetAudit=false",
            "-p:UseSharedCompilation=false",
        ],
        cwd=ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if completed.returncode != 0:
        fail(
            "generator snapshot fixture build failed\n"
            f"exit={completed.returncode}\nstdout={completed.stdout}\nstderr={completed.stderr}"
        )

    return completed.stdout + completed.stderr


def generated_files_by_name() -> dict[str, Path]:
    if not GENERATED_ROOT.exists():
        fail(f"missing generated output directory: {GENERATED_ROOT}")

    files = {
        path.name: path
        for path in GENERATED_ROOT.rglob("*.g.cs")
        if "Qyl.Telemetry.AutoInstrumentation.SourceGenerators" in path.parts
    }
    return files


def verify_interceptor_snapshot(text: str) -> None:
    for token in REQUIRED_INTERCEPTOR_TOKENS:
        if token not in text:
            fail(f"interceptor snapshot missing token: {token}")

    for token in FORBIDDEN_INTERCEPTOR_TOKENS:
        if token in text:
            fail(f"interceptor snapshot must not inline runtime telemetry behavior: {token}")


def compare_snapshots(files: dict[str, Path]) -> None:
    expected_generated = set(EXPECTED_FILES.values())
    actual_generated = set(files)
    missing = expected_generated - actual_generated
    unexpected = actual_generated - expected_generated
    if missing:
        fail(f"missing generated snapshot files: {sorted(missing)}")
    if unexpected:
        fail(f"unexpected generated snapshot files: {sorted(unexpected)}")

    for verified_name, generated_name in EXPECTED_FILES.items():
        verified = VERIFIED_ROOT / verified_name
        generated = files[generated_name]
        if not verified.exists():
            fail(f"missing verified snapshot: {verified}")
        if not filecmp.cmp(verified, generated, shallow=False):
            received = GENERATED_ROOT / verified_name.replace(".verified.cs", ".received.cs")
            shutil.copyfile(generated, received)
            fail(
                "generator snapshot mismatch\n"
                f"verified={verified}\n"
                f"received={received}"
            )

    verify_interceptor_snapshot((VERIFIED_ROOT / "QylAutoInstrumentation.Interceptors.g.verified.cs").read_text(encoding="utf-8"))


def compare_contract_manifest_coverage() -> None:
    if not VERIFIED_MANIFEST_ARTIFACT.exists():
        fail(f"missing verified generator manifest artifact: {VERIFIED_MANIFEST_ARTIFACT}")
    try:
        received = collect_live_manifest_artifact()
    except ManifestCoverageError as error:
        fail(str(error))

    verified = VERIFIED_MANIFEST_ARTIFACT.read_text(encoding="utf-8")
    if received == verified:
        return

    RECEIVED_MANIFEST_ARTIFACT.parent.mkdir(parents=True, exist_ok=True)
    RECEIVED_MANIFEST_ARTIFACT.write_text(received, encoding="utf-8")
    fail(
        "generator contract manifest snapshot mismatch\n"
        f"verified={VERIFIED_MANIFEST_ARTIFACT}\n"
        f"received={RECEIVED_MANIFEST_ARTIFACT}"
    )


def verify_shape_mismatch_diagnostic(build_output: str, interceptors: str) -> None:
    """A declared call site that does not fit its shape must report QYL1001 and emit no interceptor.

    Fixture/ShapeMismatch.cs calls QylUnmatchedClient.GetAsync(int). The receiver derives from
    System.Net.Http.HttpClient and the method name is declared, so the declaration matches; the
    signature returns Task<string> and does not fit the HttpClient shape. The generator must skip it
    and say so, rather than failing the consumer's build or dropping the call site in silence.
    """
    reported = {
        line.split("warning QYL1001:", 1)[1].strip().split(" [", 1)[0]
        for line in build_output.splitlines()
        if "warning QYL1001:" in line
    }
    if len(reported) != 1:
        fail(
            "expected exactly one distinct QYL1001 diagnostic from the snapshot fixture, got "
            f"{len(reported)}: {sorted(reported)}"
        )

    message = reported.pop()
    for token in ["QylUnmatchedClient", "GetAsync", "'HttpClient' shape", "not instrumented"]:
        if token not in message:
            fail(f"QYL1001 message missing {token!r}: {message}")

    # The whole point is that no interceptor is produced for the reported call site.
    for token in ["QylUnmatchedClient", "ShapeMismatch.cs"]:
        if token in interceptors:
            fail(f"an interceptor was emitted for the non-matching call site: {token}")

    print(f"  - QYL1001 reported once and no interceptor emitted: {message}")


def main() -> None:
    build_output = run_build()
    compare_snapshots(generated_files_by_name())
    verify_shape_mismatch_diagnostic(
        build_output,
        (VERIFIED_ROOT / "QylAutoInstrumentation.Interceptors.g.verified.cs").read_text(encoding="utf-8"),
    )
    compare_contract_manifest_coverage()
    print("generator-snapshots-ok")


if __name__ == "__main__":
    main()
