#!/usr/bin/env python3
from __future__ import annotations

import filecmp
import shutil
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
FIXTURE_PROJECT = (
    ROOT
    / "tests"
    / "Qyl.OpenTelemetry.AutoInstrumentation.SourceGenerators.Snapshots"
    / "Fixture"
    / "Qyl.OpenTelemetry.AutoInstrumentation.SourceGenerators.Snapshots.Fixture.csproj"
)
FIXTURE_DIR = FIXTURE_PROJECT.parent
GENERATED_ROOT = ROOT / "artifacts" / "obj" / FIXTURE_PROJECT.stem / "generated"
VERIFIED_ROOT = FIXTURE_DIR.parent / "verified"

EXPECTED_FILES = {
    "QylAutoInstrumentation.Interceptors.g.verified.cs": "QylAutoInstrumentation.Interceptors.g.cs",
}

REQUIRED_INTERCEPTOR_TOKENS = [
    "// <auto-generated/>",
    "#nullable enable",
    "file sealed class InterceptsLocationAttribute",
    "namespace Qyl.OpenTelemetry.AutoInstrumentation.Generated",
    "internal static class QylGeneratedInterceptors",
    "// Intercepted call at /_qyl_generator_snapshot/Program.cs",
    "[global::System.Runtime.CompilerServices.InterceptsLocationAttribute(",
    "ILogger_Log_",
    "global::Microsoft.Extensions.Logging.ILogger logger",
    "global::Qyl.OpenTelemetry.AutoInstrumentation.GeneratedCode.QylInterceptedLogger.Log(",
]

FORBIDDEN_INTERCEPTOR_TOKENS = [
    "System.Reflection",
    "Assembly.Load",
    "Activator.CreateInstance",
    "QylActivitySource",
    ".SetTag(",
]


def fail(message: str) -> None:
    raise SystemExit(message)


def run_build() -> None:
    if GENERATED_ROOT.exists():
        shutil.rmtree(GENERATED_ROOT)
    completed = subprocess.run(
        [
            "dotnet",
            "build",
            str(FIXTURE_PROJECT),
            "-c",
            "Release",
            "--no-incremental",
            "-v",
            "quiet",
        ],
        cwd=ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if completed.returncode != 0:
        fail(
            "generator snapshot fixture build failed\n"
            f"exit={completed.returncode}\nstdout={completed.stdout}\nstderr={completed.stderr}"
        )


def generated_files_by_name() -> dict[str, Path]:
    if not GENERATED_ROOT.exists():
        fail(f"missing generated output directory: {GENERATED_ROOT}")

    files = {
        path.name: path
        for path in GENERATED_ROOT.rglob("*.g.cs")
        if "Qyl.OpenTelemetry.AutoInstrumentation.SourceGenerators" in path.parts
    }
    return files


def verify_interceptor_snapshot(text: str) -> None:
    for token in REQUIRED_INTERCEPTOR_TOKENS:
        if token not in text:
            fail(f"interceptor snapshot missing token: {token}")

    for token in FORBIDDEN_INTERCEPTOR_TOKENS:
        if token in text:
            fail(f"interceptor snapshot must not inline runtime telemetry behavior: {token}")


def compare_snapshots(files: dict[str, Path]) -> None:
    expected_generated = set(EXPECTED_FILES.values())
    actual_generated = set(files)
    missing = expected_generated - actual_generated
    unexpected = actual_generated - expected_generated
    if missing:
        fail(f"missing generated snapshot files: {sorted(missing)}")
    if unexpected:
        fail(f"unexpected generated snapshot files: {sorted(unexpected)}")

    for verified_name, generated_name in EXPECTED_FILES.items():
        verified = VERIFIED_ROOT / verified_name
        generated = files[generated_name]
        if not verified.exists():
            fail(f"missing verified snapshot: {verified}")
        if not filecmp.cmp(verified, generated, shallow=False):
            received = GENERATED_ROOT / verified_name.replace(".verified.cs", ".received.cs")
            shutil.copyfile(generated, received)
            fail(
                "generator snapshot mismatch\n"
                f"verified={verified}\n"
                f"received={received}"
            )

    verify_interceptor_snapshot((VERIFIED_ROOT / "QylAutoInstrumentation.Interceptors.g.verified.cs").read_text(encoding="utf-8"))


def main() -> None:
    run_build()
    compare_snapshots(generated_files_by_name())
    print("generator-snapshots-ok")


if __name__ == "__main__":
    main()
