// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Update.Internal;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Qyl.RealEfCoreDemo.CompiledModels
{
    public partial class ProbeContextModel
    {
        private ProbeContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("cb80860c-deb0-41ea-89fa-f1079404b184"), entityTypeCount: 1)
        {
        }

        partial void Initialize()
        {
            var probeItem = ProbeItemEntityType.Create(this);

            ProbeItemEntityType.CreateAnnotations(probeItem);

            AddAnnotation("ProductVersion", "10.0.8");
            AddRuntimeAnnotation("Relational:RelationalModelFactory", () => CreateRelationalModel());
        }

        private IRelationalModel CreateRelationalModel()
        {
            var relationalModel = new RelationalModel(this);

            var probeItem = FindEntityType("Qyl.RealEfCoreDemo.ProbeItem")!;

            var defaultTableMappings = new List<TableMappingBase<ColumnMappingBase>>();
            probeItem.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings);
            var qylRealEfCoreDemoProbeItemTableBase = new TableBase("Qyl.RealEfCoreDemo.ProbeItem", null, relationalModel);
            var idColumnBase = new ColumnBase<ColumnMappingBase>("Id", "INTEGER", qylRealEfCoreDemoProbeItemTableBase);
            qylRealEfCoreDemoProbeItemTableBase.Columns.Add("Id", idColumnBase);
            var nameColumnBase = new ColumnBase<ColumnMappingBase>("Name", "TEXT", qylRealEfCoreDemoProbeItemTableBase);
            qylRealEfCoreDemoProbeItemTableBase.Columns.Add("Name", nameColumnBase);
            relationalModel.DefaultTables.Add("Qyl.RealEfCoreDemo.ProbeItem", qylRealEfCoreDemoProbeItemTableBase);
            var qylRealEfCoreDemoProbeItemMappingBase = new TableMappingBase<ColumnMappingBase>(probeItem, qylRealEfCoreDemoProbeItemTableBase, null);
            qylRealEfCoreDemoProbeItemTableBase.AddTypeMapping(qylRealEfCoreDemoProbeItemMappingBase, false);
            defaultTableMappings.Add(qylRealEfCoreDemoProbeItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase, probeItem.FindProperty("Id")!, qylRealEfCoreDemoProbeItemMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)nameColumnBase, probeItem.FindProperty("Name")!, qylRealEfCoreDemoProbeItemMappingBase);

            var tableMappings = new List<TableMapping>();
            probeItem.SetRuntimeAnnotation("Relational:TableMappings", tableMappings);
            var itemsTable = new Table("Items", null, relationalModel);
            var idColumn = new Column("Id", "INTEGER", itemsTable);
            itemsTable.Columns.Add("Id", idColumn);
            idColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<int>(idColumn);
            var nameColumn = new Column("Name", "TEXT", itemsTable);
            itemsTable.Columns.Add("Name", nameColumn);
            nameColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(nameColumn);
            relationalModel.Tables.Add(("Items", null), itemsTable);
            var itemsTableMapping = new TableMapping(probeItem, itemsTable, null);
            itemsTable.AddTypeMapping(itemsTableMapping, false);
            tableMappings.Add(itemsTableMapping);
            RelationalModel.CreateColumnMapping(idColumn, probeItem.FindProperty("Id")!, itemsTableMapping);
            RelationalModel.CreateColumnMapping(nameColumn, probeItem.FindProperty("Name")!, itemsTableMapping);
            var pK_Items = new UniqueConstraint("PK_Items", itemsTable, new[] { idColumn });
            itemsTable.PrimaryKey = pK_Items;
            pK_Items.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<int>(pK_Items));
            var pK_ItemsKey = RelationalModel.GetKey(this,
                "Qyl.RealEfCoreDemo.ProbeItem",
                new[] { "Id" });
            pK_Items.MappedKeys.Add(pK_ItemsKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_ItemsKey).Add(pK_Items);
            itemsTable.UniqueConstraints.Add("PK_Items", pK_Items);
            return relationalModel.MakeReadOnly();
        }
    }
}
