// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Qyl.RealEfCoreDemo;
using Qyl.RealEfCoreDemo.CompiledModels;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(ProbeContext), typeof(ProbeContextModel))]
